Distributed math architecture: computationalLib/test/interegated/AMQPConsumerServiceTests.cpp File Reference
AMQPConsumerServiceTests.cpp File Reference
#include <gtest/gtest.h>
#include "network_shared/AMQPConsumerService.h"
#include "network_shared/AMQPPublisherService.h"
#include "network_shared/amqpRestService.h"
#include "../GoogleCommon.h"
Classes
class AMQPConsumerSeviceTS
Functions
TEST (AMQP_COMMON_TS, ExtractHost_ValidURL)
TEST (AMQP_COMMON_TS, ExtractHost_InvalidURL)
TEST (AMQP_COMMON_TS, ConstructCString_SecureAndNonSecure)
TEST (AMQP_COMMON_TS, testConstructCaderss)
TEST_F (AMQPConsumerSeviceTS, TestConnect)
TEST_F (AMQPConsumerSeviceTS, TestProcessMessages)
TEST_F (AMQPConsumerSeviceTS, TestNoMessagesBeforeConnect)
TEST_F (AMQPConsumerSeviceTS, TestDisconnect)
TEST_F (AMQPConsumerSeviceTS, TestReconnectAfterDisconnect)
TEST_F (AMQPConsumerSeviceTS, TestConnectFailureEarlyExit)
int main (int argc, char **argv)
Variables
AuthParams g_serviceParams
Function Documentation
main()
int main (int argc, char ** argv)
References g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST() [1/4]
TEST (AMQP_COMMON_TS , ConstructCString_SecureAndNonSecure)
References amqp_common::ConstructCString().
TEST() [2/4]
TEST (AMQP_COMMON_TS , ExtractHost_InvalidURL)
References amqp_common::ExtractHost().
TEST() [3/4]
TEST (AMQP_COMMON_TS , ExtractHost_ValidURL)
References amqp_common::ExtractHost().
TEST() [4/4]
TEST (AMQP_COMMON_TS , testConstructCaderss)
References amqp_common::ConstructCAddress(), amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [1/6]
TEST_F (AMQPConsumerSeviceTS , TestConnect)
TEST_F() [2/6]
TEST_F (AMQPConsumerSeviceTS , TestConnectFailureEarlyExit)
TEST_F() [3/6]
TEST_F (AMQPConsumerSeviceTS , TestDisconnect)
TEST_F() [4/6]
TEST_F (AMQPConsumerSeviceTS , TestNoMessagesBeforeConnect)
TEST_F() [5/6]
TEST_F (AMQPConsumerSeviceTS , TestProcessMessages)
TEST_F() [6/6]
TEST_F (AMQPConsumerSeviceTS , TestReconnectAfterDisconnect)
Variable Documentation
g_serviceParams
AuthParams g_serviceParams
Referenced by main(), AMQPConsumerSeviceTS::SetUp(), DatabaseTestEnvironment::SetUp(), and TEST().