Distributed math architecture: computationalLib/test/interegated/AMQPPublisherTests.cpp File Reference
AMQPPublisherTests.cpp File Reference
#include <gtest/gtest.h>
#include "network_shared/AMQPPublisherService.h"
#include "network_shared/amqpRestService.h"
#include "network_shared/amqpCommon.h"
#include "../GoogleCommon.h"
Classes
class AMQPPublisherServiceTS
Functions
TEST_F (AMQPPublisherServiceTS, DefaultConstructorAndSetParameters)
TEST_F (AMQPPublisherServiceTS, ConstructorWithParams)
TEST_F (AMQPPublisherServiceTS, AddRemoveQueue)
TEST_F (AMQPPublisherServiceTS, PublishByIndexAndName)
TEST_F (AMQPPublisherServiceTS, PublishOutOfRangeThrows)
TEST_F (AMQPPublisherServiceTS, DisconnectCleanup)
TEST_F (AMQPPublisherServiceTS, ConnectFailureThrows)
int main (int argc, char **argv)
Variables
AuthParams g_serviceParams
Function Documentation
main()
int main (int argc, char ** argv)
References g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [1/7]
TEST_F (AMQPPublisherServiceTS , AddRemoveQueue)
References amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [2/7]
TEST_F (AMQPPublisherServiceTS , ConnectFailureThrows)
TEST_F() [3/7]
TEST_F (AMQPPublisherServiceTS , ConstructorWithParams)
References amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [4/7]
TEST_F (AMQPPublisherServiceTS , DefaultConstructorAndSetParameters)
References amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [5/7]
TEST_F (AMQPPublisherServiceTS , DisconnectCleanup)
References amqp_common::AMQPService::Connect(), amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, amqp_common::AMQPService::IsConnected(), test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [6/7]
TEST_F (AMQPPublisherServiceTS , PublishByIndexAndName)
References amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
TEST_F() [7/7]
TEST_F (AMQPPublisherServiceTS , PublishOutOfRangeThrows)
References amqp_common::ConstructCString(), amqp_common::ExtractHost(), g_serviceParams, test_common::AuthParams::host, test_common::AuthParams::password, and test_common::AuthParams::username.
Variable Documentation
g_serviceParams
AuthParams g_serviceParams
Referenced by main(), AMQPPublisherServiceTS::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().