Distributed math architecture: computationalLib/test/benchmark.cpp File Reference
benchmark.cpp File Reference
#include <iostream>
#include <utility>
#include <tuple>
#include <algorithm>
#include <omp.h>
#include "fileHandler.h"
#include "BenchmarkHandler.h"
#include "common/Generator.h"
#include "math_core/Dipoles.h"
#include "common/MeshCreator.h"
#include "common/sharedDeclarations.h"
Functions
void Func (int a, char b, uint c)
void Loop (const std::valarray< FloatType > &coordinates, auto &clk, dipoles::Dipoles &dipoles1, mesh_storage::MeshCreator &ms, size_t confNum, StateT st)
int main ()
Variables
constexpr auto kChararr = std::array<char, 3>{'a', 'b', 'c'}
constexpr auto kIntarr = std::array<int, 4>{1, 2, 3, 4}
constexpr FloatType kArange = 1e-6
auto normal_gen = generators::get_normal_generator(0.0, kArange * sqrt(2))
auto firstBench
auto nameGenerator1
const std::array< size_t, 5 > kRlims = {10, 50, 200, 500, 1000}
const std::array< size_t, 6 > kDivs
auto rangeFinder
auto secondBench
std::function< std::string(size_t)> nameGenerator2
auto thirdBench
auto nameGenerator3
auto fourthBench
auto nameGenerator4
auto fifthBench
auto nameGenerator5
Function Documentation
Func()
void Func (int a, char b, uint c)
Loop()
void Loop (const std::valarray< FloatType > & coordinates, auto & clk, dipoles::Dipoles & dipoles1, mesh_storage::MeshCreator & ms, size_t confNum, StateT st)
References dipoles::Dipoles::GetFullFunction(), dipoles::Dipoles::GetI2Function(), dipoles::Dipoles::GetIfunction(), dipoles::Dipoles::SetNewCoordinates(), and dipoles::Dipoles::Solve().
main()
int main ()
References fifthBench, firstBench, fourthBench, nameGenerator1, nameGenerator2, nameGenerator3, nameGenerator4, nameGenerator5, rangeFinder, bench_utils::BenchmarkHandler< range >::RunBenchmark(), secondBench, and thirdBench.
Variable Documentation
fifthBench
auto fifthBench
Referenced by main().
firstBench
auto firstBench
Initial value:
= []
    (auto &clk, file_utils::fileHandler &handler, size_t &mul, StateT st, size_t N) {
  auto conf_num = 1000;
  std::valarray<FloatType> coordinates(2 * N);
  std::generate(std::begin(coordinates), std::end(coordinates), normal_gen);
  dipoles::Dipoles dipoles1;
  mesh_storage::MeshCreator ms;
  ms.ConstructMeshes();
  Loop(coordinates, clk, dipoles1, ms, conf_num, st);
}
Referenced by main().
fourthBench
auto fourthBench
Referenced by main().
kArange
constexpr FloatType kArange = 1e-6 constexpr
kChararr
constexpr auto kChararr = std::array<char, 3>{'a', 'b', 'c'} constexpr
kDivs
const std::array<size_t, 6> kDivs
Initial value:
{
        1, 10, 40, 100, 200, 400
    }
kIntarr
constexpr auto kIntarr = std::array<int, 4>{1, 2, 3, 4} constexpr
kRlims
const std::array<size_t, 5> kRlims = {10, 50, 200, 500, 1000}
nameGenerator1
auto nameGenerator1
Initial value:
=
    [](StateT st, size_t N) {
      return EnumToStr(st, kStateToStr) + "_" + std::to_string(N);
    }
Referenced by main().
nameGenerator2
std::function<std::string(size_t)> nameGenerator2
Initial value:
=
    [](size_t N) {
      return std::to_string(N) + "_";
    }
Referenced by main().
nameGenerator3
auto nameGenerator3
Initial value:
=
    [](StateT st, size_t N) {
      return STR(EnumToStr(st, kStateToStr)) + "_" + std::to_string(N);
    }
Referenced by main().
nameGenerator4
auto nameGenerator4
Initial value:
=
    [](size_t confNum, size_t N) {
      return std::to_string(confNum) + "_" + std::to_string(N);
    }
Referenced by main().
nameGenerator5
auto nameGenerator5
Initial value:
=
    [](size_t thread_count, size_t N) {
      return std::to_string(thread_count) + "_" + std::to_string(N);
    }
Referenced by main().
normal_gen
auto normal_gen = generators::get_normal_generator(0.0, kArange * sqrt(2))
rangeFinder
auto rangeFinder
Initial value:
= [](size_t N) -> size_t {
  auto range_num = std::lower_bound(kRlims.begin(), kRlims.end(), N) - kRlims.begin();
  auto currdiv = kDivs[range_num];
  return currdiv;
}
Referenced by main().
secondBench
auto secondBench
Referenced by main().
thirdBench
auto thirdBench
Referenced by main().