Distributed math architecture: rest_utils::AuthHandler Class Reference
rest_utils::AuthHandler Class Reference abstract
Common interface for handling authentication.
#include <restUtils.h>
Public Member Functions
AuthHandler (bool active=true)
void SetActive (bool act)
void AddAuthorization (CURL *curl)
Protected Member Functions
virtual void AddAuth (CURL *curl)=0
Protected Attributes
bool active_
Can toggle off authorization.
Detailed Description
Common interface for handling authentication.
Classes that inherit must provide implementation for AddAuth.
Constructor & Destructor Documentation
AuthHandler()
rest_utils::AuthHandler::AuthHandler (bool active = true)
Member Function Documentation
AddAuth()
virtual void rest_utils::AuthHandler::AddAuth (CURL * curl) protected pure virtual
Implemented in rest_utils::BasicAuthHandler.
Referenced by AddAuthorization().
AddAuthorization()
void rest_utils::AuthHandler::AddAuthorization (CURL * curl)
References active_, and AddAuth().
Referenced by rest_utils::PerformCurlRequest().
SetActive()
void rest_utils::AuthHandler::SetActive (bool act)
References active_.
Member Data Documentation
active_
bool rest_utils::AuthHandler::active_ protected
Can toggle off authorization.
Referenced by rest_utils::BasicAuthHandler::AddAuth(), AddAuthorization(), and SetActive().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/restUtils.h
computationalLib/lib/network_shared/restUtils.cpp