Distributed math architecture: network_types::AMQPSQLCStr Class Reference
network_types::AMQPSQLCStr Class Reference
Structure to store and format AMQP connection string.
#include <connectionString.h>
Public Member Functions
AMQPSQLCStr ()
AMQPSQLCStr (std::string_view host_port, std::string_view user, std::string_view password, bool secure=false)
void FromString (std::string_view s) override
Parses fields from std::string_view.
std::string GetVerboseName () const override
Retrieves cString contents for verbose logging.
std::string_view GetHostPort () const
void SetHostPort (std::string_view host_port)
std::string_view GetUser () const
void SetUser (std::string_view user)
std::string_view GetPassword () const
void SetPassword (std::string_view password)
bool IsSecure () const
void SetSecure (bool secure)
Public Member Functions inherited from network_types::AbstractConnectionString
AbstractConnectionString ()=default
std::string to_string () const
explicit std::string type cast
operator std::string_view ()
implicit std::string_view cast
const char * CStr () const
Retrieves const char * representation.
bool operator== (const AbstractConnectionString &rhs) const
Protected Member Functions
void UpdateFormat () override
Private Attributes
std::string host_port_
std::string user_
std::string password_
bool secure_
Additional Inherited Members
Protected Attributes inherited from network_types::AbstractConnectionString
std::string formatted_string_
formatted string for c string
Detailed Description
Structure to store and format AMQP connection string.
Constructor & Destructor Documentation
AMQPSQLCStr() [1/2]
network_types::AMQPSQLCStr::AMQPSQLCStr ()
AMQPSQLCStr() [2/2]
network_types::AMQPSQLCStr::AMQPSQLCStr (std::string_view host_port, std::string_view user, std::string_view password, bool secure = false)
References UpdateFormat().
Member Function Documentation
FromString()
void network_types::AMQPSQLCStr::FromString (std::string_view s) override virtual
Parses fields from std::string_view.
Parameters
s
Implements network_types::AbstractConnectionString.
References host_port_, password_, secure_, UpdateFormat(), network_types::UrlDecode(), and user_.
GetHostPort()
std::string_view network_types::AMQPSQLCStr::GetHostPort () const
References host_port_.
GetPassword()
std::string_view network_types::AMQPSQLCStr::GetPassword () const
References password_.
GetUser()
std::string_view network_types::AMQPSQLCStr::GetUser () const
References user_.
GetVerboseName()
std::string network_types::AMQPSQLCStr::GetVerboseName () const override virtual
Retrieves cString contents for verbose logging.
Reimplemented from network_types::AbstractConnectionString.
References host_port_, and secure_.
Referenced by comp_services::ComputationNodeService::Connect().
IsSecure()
bool network_types::AMQPSQLCStr::IsSecure () const
References secure_.
SetHostPort()
void network_types::AMQPSQLCStr::SetHostPort (std::string_view host_port)
References host_port_, and UpdateFormat().
SetPassword()
void network_types::AMQPSQLCStr::SetPassword (std::string_view password)
References password_, and UpdateFormat().
SetSecure()
void network_types::AMQPSQLCStr::SetSecure (bool secure)
References secure_, and UpdateFormat().
SetUser()
void network_types::AMQPSQLCStr::SetUser (std::string_view user)
References UpdateFormat(), and user_.
UpdateFormat()
void network_types::AMQPSQLCStr::UpdateFormat () override protected virtual
Implements network_types::AbstractConnectionString.
References network_types::AbstractConnectionString::formatted_string_, host_port_, password_, secure_, and user_.
Referenced by AMQPSQLCStr(), FromString(), SetHostPort(), SetPassword(), SetSecure(), and SetUser().
Member Data Documentation
host_port_
std::string network_types::AMQPSQLCStr::host_port_ private
Referenced by FromString(), GetHostPort(), GetVerboseName(), SetHostPort(), and UpdateFormat().
password_
std::string network_types::AMQPSQLCStr::password_ private
Referenced by FromString(), GetPassword(), SetPassword(), and UpdateFormat().
secure_
bool network_types::AMQPSQLCStr::secure_ private
Referenced by FromString(), GetVerboseName(), IsSecure(), SetSecure(), and UpdateFormat().
user_
std::string network_types::AMQPSQLCStr::user_ private
Referenced by FromString(), GetUser(), SetUser(), and UpdateFormat().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/connectionString.h
computationalLib/lib/network_shared/connectionString.cpp