Distributed math architecture: db_service::DbService Class Reference
db_service::DbService Class Reference
Public Member Functions
DbService ()
DbService (const myConnString &conn_str)
~DbService ()
bool Connect ()
void Disconnect ()
bool IsConnected () const
IndexType CreateUser (std::string_view login, std::string_view password, std::string_view role="user")
Creates new user record.
IndexType CreateUser (const User &user)
bool AuthenticateUser (std::string_view login, std::string_view password)
Performs authentication attempt.
bool AuthenticateUser (const User &user)
void DeleteUser (IndexType user_id)
Deletes user record.
std::vector< User > ListUsers (IndexType page_num, IndexType page_size=50)
Retrieves user list in paginated form.
IndexType CreateExperiment (IndexType user_id, const Json::Value &parameters)
Create new Experiment record.
IndexType CreateExperiment (Experiment exp)
std::vector< Experiment > ListExperiments (IndexType user_id, IndexType page_num, IndexType page_size=50)
Retrieves list of Experiments for user_id.
void UpdateExperimentStatus (IndexType experiment_id, std::string_view status)
Experiment GetExperiment (IndexType experiment_id)
void UpdateIterationStatus (IndexType iteration_id, std::string_view status, const Json::Value &output_data=Json::Value())
IndexType CreateIteration (IndexType experiment_id, IndexType node_id, std::string_view iter_type)
Creates experiment record.
IndexType CreateIteration (const Iteration &iter)
Iteration GetIteration (IndexType iteration_id)
Gets iteration using its id.
std::vector< Iteration > ListIterations (IndexType experiment_id, IndexType page_num, IndexType page_size=50)
Retrieves iteration list for experiment_id.
IndexType RegisterNode (std::string_view ip_address, const shared::BenchResVec &benchmark_score)
Create node record.
IndexType RegisterNode (const Node &node)
void UpdateNodeStatus (IndexType node_id, std::string_view status)
Changes node status.
void UnregisterNode (IndexType node_id)
Deletes node.
Node GetNode (IndexType node_id)
Retrieves node record for id.
std::vector< Node > ListNodes (IndexType page_num, IndexType page_size=50)
Retrieves node list in paginated format.
IndexType Log (std::optional< IndexType > experiment_id, std::optional< IndexType > node_id, std::string_view severity, std::string_view message)
Logs with specified message.
IndexType Log (const db_common::Log &log)
std::vector< db_common::Log > ListLogs (IndexType page_num, IndexType page_size=50)
const myConnString & GetConnStr () const
void SetConnStr (const myConnString &conn_str)
ResType ExecuteTransaction (const std::function< ResType(TransactionT &)> &func)
ResType ExecuteSubTransaction (TransactionT &txn, const std::function< ResType(Subtransaction &)> &func, std::string_view sub_name="")
Constructor & Destructor Documentation
DbService() [1/2]
db_service::DbService::DbService ()
                     : conn_str_(), conn_(nullptr) {
}
DbService() [2/2]
db_service::DbService::DbService (const myConnString & conn_str)
                                                 : conn_str_(conn_str), conn_(nullptr) {
}
~DbService()
db_service::DbService::~DbService ()
                      {
  Disconnect();
}
References Disconnect().
Member Function Documentation
AuthenticateUser() [1/2]
bool db_service::DbService::AuthenticateUser (const User & user)
{
  return AuthenticateUser(user.login, user.hashed_password);
}
References db_common::User::hashed_password, and db_common::User::login.
AuthenticateUser() [2/2]
bool db_service::DbService::AuthenticateUser (std::string_view login, std::string_view password)
Performs authentication attempt.
Parameters
login
password
Returns
is_authenticated
{
  bool authenticated = false;
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT hashed_password FROM \"User\" WHERE login = $1";
    auto result = txn.exec(qq, pqxx::params{login}).one_row();
    if (result[0].as<std::string>() == password) {
      authenticated = true;
      std::string qq2 = "UPDATE \"User\" SET last_login = NOW() WHERE login = $1";
      txn.exec(qq2, pqxx::params{login});
    }
    return ResType();
  });
  return authenticated;
}
References ExecuteTransaction().
Connect()
bool db_service::DbService::Connect ()
{
  Reconnect();
  return true;
}
CreateExperiment() [1/2]
IndexType db_service::DbService::CreateExperiment (Experiment exp)
{
  return CreateExperiment(exp.user_id,exp.parameters);
}
References CreateExperiment(), db_common::Experiment::parameters, and db_common::Experiment::user_id.
CreateExperiment() [2/2]
IndexType db_service::DbService::CreateExperiment (IndexType user_id, const Json::Value & parameters)
Create new Experiment record.
Parameters
user_id
parameters
Returns
experiment_id
{
  IndexType experiment_id;
  ExecuteTransaction([&](TransactionT &txn) {
    Json::StreamWriterBuilder builder;
    std::string params_str = Json::writeString(builder, parameters);
    std::string qq = "INSERT INTO \"Experiment\" (user_id, parameters)"
                     " VALUES ($1, $2::jsonb)"
                     " RETURNING experiment_id";
    experiment_id = txn.exec(qq,
                             pqxx::params{ user_id, params_str}
                             ).one_row()[0].as<IndexType>();
    InnerLog(txn, std::nullopt,std::nullopt, "info", fmt::format("User {} created experiment ", user_id, experiment_id));
    return ResType();
  });
  return experiment_id;
}
References ExecuteTransaction().
Referenced by CreateExperiment().
CreateIteration() [1/2]
IndexType db_service::DbService::CreateIteration (const Iteration & iter)
{
  return CreateIteration(iter.experiment_id,
                         iter.node_id,
                         EnumToStr(iter.iter_t, kIterTypeToStr));
}
References enum_utils::EnumToStr(), db_common::Iteration::experiment_id, db_common::Iteration::iter_t, db_common::kIterTypeToStr, and db_common::Iteration::node_id.
CreateIteration() [2/2]
IndexType db_service::DbService::CreateIteration (IndexType experiment_id, IndexType node_id, std::string_view iter_type)
Creates experiment record.
Parameters
experiment_id
node_id
iter_type
Returns
iteration_id
{
  IndexType iteration_id;
  //todo use stream api
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "INSERT INTO \"Iteration\" (experiment_id, node_id, iter_t)"
                     " VALUES ($1, $2, $3)"
                     " RETURNING iteration_id";
    iteration_id = txn.exec(qq,
                            pqxx::params{experiment_id, node_id, iter_type}).one_row()[0].as<IndexType>();
    InnerLog(txn,experiment_id, node_id, "info", fmt::format("Iteration {} created for experiment {}", iteration_id, experiment_id));
    return ResType();
  });
  return iteration_id;
}
References ExecuteTransaction().
CreateUser() [1/2]
IndexType db_service::DbService::CreateUser (const User & user)
{
  return CreateUser(user.login, user.hashed_password, EnumToStr(user.role, kUserRoleToStr));
}
References enum_utils::EnumToStr(), db_common::User::hashed_password, db_common::kUserRoleToStr, db_common::User::login, and db_common::User::role.
CreateUser() [2/2]
IndexType db_service::DbService::CreateUser (std::string_view login, std::string_view password, std::string_view role = "user")
Creates new user record.
Parameters
login
password
role
Returns
userd_id
{
  IndexType user_id;
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "INSERT INTO \"User\" (login, hashed_password, role)"
                     " VALUES ($1, $2, $3)"
                     " RETURNING user_id";
    user_id = txn.exec(qq,pqxx::params{login, password, role}
    ).one_row()[0].as<IndexType>();
    return ResType();
  });
  return user_id;
}
References ExecuteTransaction().
DeleteUser()
void db_service::DbService::DeleteUser (IndexType user_id)
Deletes user record.
Parameters
user_id
{
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "DELETE FROM \"User\" WHERE user_id = $1";
    txn.exec(qq, pqxx::params{user_id});
    return ResType();
  });
}
References ExecuteTransaction().
Disconnect()
void db_service::DbService::Disconnect ()
{
  ::db_service::Disconnect(conn_);
}
References db_common::Disconnect().
Referenced by ~DbService().
ExecuteSubTransaction()
ResType db_service::DbService::ExecuteSubTransaction (TransactionT & txn, const std::function< ResType(Subtransaction &)> & func, std::string_view sub_name = "")
{
  return ::db_common::ExecuteSubTransaction(txn, func, sub_name);
}
ExecuteTransaction()
ResType db_service::DbService::ExecuteTransaction (const std::function< ResType(TransactionT &)> & func)
{
  return ::db_common::ExecuteTransaction(conn_, func, service_name, conn_str_);
}
Referenced by AuthenticateUser(), CreateExperiment(), CreateIteration(), CreateUser(), DeleteUser(), GetExperiment(), ListExperiments(), ListUsers(), UpdateExperimentStatus(), and UpdateIterationStatus().
GetConnStr()
const myConnString & db_service::DbService::GetConnStr () const
{
  return conn_str_;
}
GetExperiment()
Experiment db_service::DbService::GetExperiment (IndexType experiment_id)
{
  Experiment experiment;
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"Experiment\" WHERE experiment_id = $1";
    auto row = txn.exec(qq, pqxx::params{experiment_id}).one_row();
    experiment=std::move(Experiment(row));
    return ResType();
  });
  return experiment;
}
References ExecuteTransaction().
GetIteration()
Iteration db_service::DbService::GetIteration (IndexType iteration_id)
Gets iteration using its id.
Parameters
iteration_id
Returns
iteration
{
  Iteration result;
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"Iteration\" WHERE iteration_id = $1";
    auto row = txn.exec(qq, pqxx::params{iteration_id}).one_row();
    result = std::move(Iteration(row));
    return ResType();
  });
  return result;
}
References db_common::ExecuteTransaction().
GetNode()
Node db_service::DbService::GetNode (IndexType node_id)
Retrieves node record for id.
Parameters
node_id
Returns
node record
{
  auto result=ExecuteTransaction([&](TransactionT &txn) {
    using namespace print_utils;
    auto qq="SELECT * FROM \"Node\" WHERE node_id = $1";
    txn.exec(qq, pqxx::params{node_id});
    auto res = txn.exec(qq, pqxx::params{node_id});
    return res;
  });
  return Node(result[0]);
}
References db_common::ExecuteTransaction().
IsConnected()
bool db_service::DbService::IsConnected () const
{
  return ::db_service::CheckConnection(conn_);
}
ListExperiments()
std::vector< Experiment > db_service::DbService::ListExperiments (IndexType user_id, IndexType page_num, IndexType page_size = 50)
Retrieves list of Experiments for user_id.
Note
pagination starts from 1
Parameters
user_id
page_num
page_size
Returns
Experiment List
{
  auto result=ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"Experiment\" WHERE user_id =$1";
    auto req=PaginateRequest(qq,
                             page_num, page_size);
    return txn.exec(req, pqxx::params{user_id});
  });
  return ParseArray<std::vector,Experiment>(result);
}
References ExecuteTransaction(), and db_common::PaginateRequest().
ListIterations()
std::vector< Iteration > db_service::DbService::ListIterations (IndexType experiment_id, IndexType page_num, IndexType page_size = 50)
Retrieves iteration list for experiment_id.
Note
pagination starts from 1
Parameters
experiment_id
page_num
page_size
Returns
list of Iteration
{
  auto result=ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"Iteration\" WHERE experiment_id =$1";
    auto req=PaginateRequest(qq,
                             page_num, page_size);
    return txn.exec(req,pqxx::params{experiment_id});
  });
  return ParseArray<std::vector,Iteration>(result);
}
References db_common::ExecuteTransaction(), and db_common::PaginateRequest().
ListLogs()
std::vector< db_common::Log > db_service::DbService::ListLogs (IndexType page_num, IndexType page_size = 50)
{
  auto result=ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"Log\"";
    auto req=PaginateRequest(qq,
                             page_num, page_size);
    return txn.exec(req);
  });
  return ParseArray<std::vector,db_common::Log>(result);
}
References db_common::ExecuteTransaction(), and db_common::PaginateRequest().
ListNodes()
std::vector< Node > db_service::DbService::ListNodes (IndexType page_num, IndexType page_size = 50)
Retrieves node list in paginated format.
Parameters
page_num
page_size
Returns
list of nodes
{
  auto result=ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"Node\"";
        auto req=PaginateRequest(qq,
                             page_num, page_size);
    return txn.exec(req);
  });
  return ParseArray<std::vector,Node>(result);
}
References db_common::ExecuteTransaction(), and db_common::PaginateRequest().
ListUsers()
std::vector< User > db_service::DbService::ListUsers (IndexType page_num, IndexType page_size = 50)
Retrieves user list in paginated form.
Note
pagination starts from 1
Parameters
page_num
page_size
Returns
userList
{
  auto result=ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "SELECT * FROM \"User\"";
    auto req=PaginateRequest(qq,
                             page_num, page_size);
    return txn.exec(req);
  });
  return ParseArray<std::vector,User>(result);
}
References ExecuteTransaction(), and db_common::PaginateRequest().
Log() [1/2]
IndexType db_service::DbService::Log (const db_common::Log & log)
{
  return Log(log.experiment_id, log.node_id,
             print_utils::kSevToStr[static_cast<unsigned long>(log.severity)],
             log.message);
}
References db_common::Log::experiment_id, db_common::Log::message, db_common::Log::node_id, and db_common::Log::severity.
Log() [2/2]
IndexType db_service::DbService::Log (std::optional< IndexType > experiment_id, std::optional< IndexType > node_id, std::string_view severity, std::string_view message)
Logs with specified message.
Parameters
experiment_id
node_id
severity
message
{
  auto res=ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "INSERT INTO \"Log\" (node_id,experiment_id, severity, message)"
                     " VALUES ($1,$2, $3::log_severity, $4)"
                     " RETURNING log_id";
    return txn.exec(qq, pqxx::params{node_id,experiment_id,severity,message});
  });
  return res[0][0].as<IndexType>();
}
References db_common::ExecuteTransaction().
RegisterNode() [1/2]
IndexType db_service::DbService::RegisterNode (const Node & node)
{
  return RegisterNode(node.ip_address,node.benchmark_score);
}
References db_common::Node::benchmark_score, and db_common::Node::ip_address.
RegisterNode() [2/2]
IndexType db_service::DbService::RegisterNode (std::string_view ip_address, const shared::BenchResVec & benchmark_score)
Create node record.
Parameters
ip_address
benchmark_score
Returns
{
  IndexType node_id;
  ExecuteTransaction([&](TransactionT &txn) {
    using namespace print_utils;
    std::string qq = "INSERT INTO \"Node\" (ip_address, benchmark_score, status, last_ping)"
                     " VALUES ($1, $2, 'active', NOW())"
                     "RETURNING node_id";
    auto bench_vec = OneDimToString(benchmark_score, false,
                                    EIGENF(EigenPrintFormats::VECTOR_DB_FORMAT));
    node_id =txn.exec(qq,
                      pqxx::params{ip_address,bench_vec}
                      ).one_row()[0].as<IndexType>();
    InnerLog(txn, std::nullopt,node_id, "info", fmt::format("Node registered with IP {}", ip_address));
    return ResType();
  });
  return node_id;
}
References EIGENF, and db_common::ExecuteTransaction().
SetConnStr()
void db_service::DbService::SetConnStr (const myConnString & conn_str)
{
  conn_str_ = conn_str;
}
UnregisterNode()
void db_service::DbService::UnregisterNode (IndexType node_id)
Deletes node.
Parameters
node_id
{
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "UPDATE \"Node\" SET status = 'inactive', last_ping = NOW() WHERE node_id = $1";
    txn.exec(qq, pqxx::params{node_id});
    InnerLog(txn,std::nullopt,node_id, "info", fmt::format("Node {} unregistered.", node_id));
    return ResType();
  });
}
References db_common::ExecuteTransaction().
UpdateExperimentStatus()
void db_service::DbService::UpdateExperimentStatus (IndexType experiment_id, std::string_view status)
{
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "UPDATE \"Experiment\" SET status = $1, start_time = CASE WHEN"
                     " $1 = 'running' THEN NOW() ELSE start_time END,"
                     " end_time = CASE WHEN $1 IN ('succeeded', 'error')"
                     " THEN NOW() ELSE end_time END WHERE experiment_id = $2";
    txn.exec(qq,pqxx::params{status, experiment_id});
    InnerLog(txn, std::nullopt,std::nullopt, "info", fmt::format("Experiment {}  status updated to {}", experiment_id, status));
    return ResType();
  });
}
References ExecuteTransaction().
UpdateIterationStatus()
void db_service::DbService::UpdateIterationStatus (IndexType iteration_id, std::string_view status, const Json::Value & output_data = Json::Value())
{
  ExecuteTransaction([&](TransactionT &txn) {
    if (output_data.isNull()) {
      std::string qq = "UPDATE \"Iteration\" SET status = $1::iteration_status, end_time = CASE WHEN $1 IN ('succeeded', 'error')"
                       " THEN NOW() ELSE end_time END "
                       " WHERE iteration_id = $2";
      txn.exec(qq, pqxx::params{status, iteration_id});
    } else {
      Json::StreamWriterBuilder builder;
      std::string output_str = Json::writeString(builder, output_data);
      std::string qq = "UPDATE \"Iteration\" SET status = $1::iteration_status, output_data = $2::jsonb, end_time ="
                       " CASE WHEN $1 IN ('succeeded', 'error') "
                       "THEN NOW() ELSE end_time END "
                       "WHERE iteration_id = $3";
      txn.exec(qq, pqxx::params{status, output_str, iteration_id});
    }
    //todo think
    InnerLog(txn,std::nullopt,std::nullopt, "info",
             fmt::format("Iteration {} status updated to {}",
                         iteration_id,
                         status)
                         );
    return ResType();
  });
}
References ExecuteTransaction().
UpdateNodeStatus()
void db_service::DbService::UpdateNodeStatus (IndexType node_id, std::string_view status)
Changes node status.
Parameters
node_id
status
{
  ExecuteTransaction([&](TransactionT &txn) {
    std::string qq = "UPDATE \"Node\" SET status = $1::node_status, last_ping = NOW() WHERE node_id = $2";
    txn.exec(qq, pqxx::params{status,node_id});
    InnerLog(txn,std::nullopt, node_id, "info", fmt::format("Node status updated to {}", node_id));
    return ResType();
  });
}
References db_common::ExecuteTransaction().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/DbService.h
computationalLib/lib/network_shared/DbService.cpp