Distributed math architecture: dipoles::Dipoles Class Reference
dipoles::Dipoles Class Reference
Provides interface to Solve system of dipoles.
Public Member Functions
Dipoles ()=default
template<typename Container >
requires HasSizeMethod<Container>
Dipoles (const Container &xi)
Basic constructor that acccepts dipole coordinates Container.
template<typename Container >
requires HasSizeMethod<Container>
void SetNewCoordinates (const Container &xi)
Function that allows to Reset dipole coordinates.
void LoadFromMatrix (const MatrixType &xi)
Loads system of equations matrix.
template<typename Container , typename Container2 >
requires HasSizeMethod<Container> && HasSizeMethod<Container2>
void GetFullFunction (const Container &xi, const Container2 &sol)
template<typename Container = common_types::ReturnToDataType<ReturnType::EIGEN_VECTOR>>
Container Solve ()
Computes solution vector for dipole parameters and returns it in available format.
const IntegrableFunction & GetIfunction () const
const DirectionGraph & GetI2Function () const
const EigenVec & GetRightPart ()
Returns reference to the right part for system of equations.
MatrixType GetMatrixx ()
Retrieves matrix computed for system of equations.
template<>
Arr2EigenVec Solve ()
template<>
EigenVec Solve ()
template<>
StdVec Solve ()
template<>
StdValarr Solve ()
Protected Member Functions
template<typename Container >
requires HasBracketOperator<Container>
FloatType GetDistance (size_t i1, size_t i2, Container &xi)
Computes euclidean distacne for dipole coordinates.
template<typename Container >
requires HasBracketOperator<Container>
Eigen::Vector< FloatType, 2 > TwoDVecDifference (size_t i1, size_t i2, Container &xi)
Computes vector difference for dipole coordinates.
void InitArrays ()
Intializes dimensions for system of equations matrices.
void GetMatrices (const Eigen::Vector< FloatType, 2 > &rim, FloatType r_mode, Eigen::Matrix< FloatType, 2, 2 > &k_1, Eigen::Matrix< FloatType, 2, 2 > &k_2) const
template<typename Container >
void SetMatrixes (const Container &xi)
Recalculates matrix values for dipole coordinates vector.
Protected Attributes
MatrixType m_1_
MatrixType m_2_
IntegrableFunction ifunction_
DirectionGraph i_2_function_
Eigen::Vector< FloatType, Eigen::Dynamic > f_
FloatType an_ = params::a
int n_
Detailed Description
Provides interface to Solve system of dipoles.
Allows to construct and Solve system of equations for the selected mathematical model.
Can accept various input formats for coordinates and solutions to crete system,
to Solve it, to Generate direction graph for magnetic field.
Constructor & Destructor Documentation
Dipoles() [1/2]
dipoles::Dipoles::Dipoles () default
Dipoles() [2/2]
template<typename Container > requires HasSizeMethod<Container> dipoles::Dipoles::Dipoles (const Container & xi)
Basic constructor that acccepts dipole coordinates Container.
Template Parameters
Container
Parameters
xi
{
  if constexpr (not HasBracketsNested<Container>) {
    this->n_ = xi.size() / 2;
  } else {
    this->n_ = xi[0].size();
  }
  InitArrays();
  SetMatrixes(xi);
}
References InitArrays(), n_, and SetMatrixes().
Member Function Documentation
GetDistance()
template<typename Container > requires HasBracketOperator<Container> FloatType dipoles::Dipoles::GetDistance (size_t i1, size_t i2, Container & xi) protected
Computes euclidean distacne for dipole coordinates.
Template Parameters
Container
Parameters
i1
i2
xi
{
  FloatType d1;
  FloatType d2;
  if constexpr (my_concepts::HasBracketsNested<Container>) {
    d1 = xi[0][i1] - xi[0][i2];
    d2 = xi[1][i1] - xi[1][i2];
  } else {
    d1 = xi[i1] - xi[i2];
    d2 = xi[i1 + n_] - xi[i2 + n_];
  }
  return std::sqrt(d1 * d1 + d2 * d2);
}
References n_.
Referenced by SetMatrixes().
GetFullFunction()
template<typename Container , typename Container2 > requires HasSizeMethod<Container> && HasSizeMethod<Container2> void dipoles::Dipoles::GetFullFunction (const Container & xi, const Container2 & sol)
Calculates directional graph and/or other it variants
Template Parameters
Container
Container2
Parameters
xi
sol
{
  this->ifunction_ = [&xi, &sol](FloatType theta, FloatType phi, FloatType t) {
    int n = xi.size() / 2;
    FloatType res = 0;
    FloatType s[2] = {cos(phi), sin(phi)};
    FloatType ress[3] = {0, 0, 0};
    for (int i = 0; i < n; ++i) {
      FloatType ri[2] = {GetElement(xi, 0, i, n),
                         GetElement(xi, 1, i, n)};
      FloatType ys = (ri[1] * cos(phi) - ri[0] * sin(phi)) * sin(theta);
      FloatType t0 = t - ys / params::c;
      FloatType aI[2] = {GetValue(sol, 2 * i), GetValue(sol, 2 * i + 1)};
      FloatType bi[2] = {GetValue(sol, 2 * i + 2 * n), GetValue(sol, 2 * i + 1 + 2 * n)};
      FloatType di[2] = {aI[0] * cos(params::omega * t0) + bi[0] * sin(params::omega * t0),
                         aI[1] * cos(params::omega * t0) + bi[1] * sin(params::omega * t0)};
      FloatType vi[2] = {params::omega * (bi[0] * cos(params::omega * t0)
          - aI[0] * sin(params::omega * t0)) / params::c,
                         params::omega * (bi[1] * cos(params::omega * t0)
                             - aI[1] * sin(params::omega)) / params::c};
      FloatType ai[2] = {-pow(params::omega, 2) * di[0], -pow(params::omega, 2) * di[1]};
      FloatType vsi = vi[0] * s[0] + vi[1] * s[1];
      FloatType asi = ai[0] * s[0] + ai[1] * s[1];
      for (int coord = 0; coord < 2; ++coord) {
        FloatType ttt = ai[coord] * (vsi * sin(theta) - 1) +
            s[coord] * asi * pow(sin(theta), 2) -
            vi[coord] * asi * sin(theta);
        ress[coord] += ttt;
      }
      FloatType t3 = asi * sin(theta) * cos(theta);
      ress[2] += t3;
    }
    for (FloatType elem : ress) {
      res += elem * elem;
    }
    return res;
  };
  this->i_2_function_ = [&xi, &sol](FloatType phi, FloatType theta) {
    int n = xi.size() / 2;
    FloatType omega0 = params::omega;
    FloatType t_0 = M_PI * 2 / omega0;
    FloatType res;
    Eigen::Vector<FloatType, 2> resxy = {0.0, 0.0};
    FloatType resz = 0.0;
    FloatType o3dco3dc = pow(omega0, 3) / params::c;//todo why is this here?
    FloatType o2 = pow(omega0, 2);
    FloatType sinth2 = pow(sin(theta), 2);
    Eigen::Vector<FloatType, 2> s = {cos(phi),
                                     sin(phi)};
    for (int i = 0; i < n; ++i) {
      FloatType ri[2] = {GetElement(xi, 0, i, n), GetElement(xi, 1, i, n)};
      FloatType ys = (ri[1] * cos(phi) - ri[0] * sin(phi)) * sin(theta);
      Eigen::Vector<FloatType, 2> Ai = {GetValue(sol, 2 * i), GetValue(sol, 2 * i + 1)};
      Eigen::Vector<FloatType, 2> bi = {GetValue(sol, 2 * i + 2 * n), GetValue(sol, 2 * i + 1 + 2 * n)};
      FloatType argument = omega0 * ys / params::c;
      FloatType ais = Ai.dot(s);
      FloatType bis = bi.dot(s);
      Eigen::Vector<FloatType, 2> a_bis = Ai * bis;
      Eigen::Vector<FloatType, 2> b_ais = bi * ais;
      Eigen::Vector<FloatType, 2> pc_1_i = ((s * ais * sinth2 - Ai) * cos(argument) -
          (s * bis * sinth2 - bi) * sin(argument));
      Eigen::Vector<FloatType, 2> ps_1_i = ((s * ais * sinth2 - Ai) * sin(argument) +
          (s * bis * sinth2 - bi) * cos(argument));
      Eigen::Vector<FloatType, 2> pcomi = -(omega0 / params::c) * (sin(theta)) * (a_bis - b_ais);
      FloatType pci = (ais * cos(argument) - bis * sin(argument));
      FloatType psi = (ais * sin(argument) + bis * cos(argument));
      Eigen::Vector<FloatType, 2> rj;
      FloatType ysj;
      Eigen::Vector<FloatType, 2> aj;
      Eigen::Vector<FloatType, 2> bj;
      FloatType argumentj;
      FloatType ajs;
      FloatType bjs;
      FloatType pcj;
      FloatType psj;
      Eigen::Vector<FloatType, 2> pc_1_j;
      Eigen::Vector<FloatType, 2> ps_1_j;
      Eigen::Vector<FloatType, 2> pcomj;
      Eigen::Vector<FloatType, 2> a_bjs;
      Eigen::Vector<FloatType, 2> b_ajs;
      for (int j = 0; j < i; ++j) {
        rj = {GetElement(xi, 0, j, n), GetElement(xi, 1, j, n)};
        ysj = (rj[1] * cos(phi) - rj[0] * sin(phi)) * sin(theta);
        aj = {GetValue(sol, 2 * j), GetValue(sol, 2 * j + 1)};
        bj = {GetValue(sol, 2 * j + 2 * n), GetValue(sol, j + 1 + 2 * n)};
        argumentj = omega0 * ysj / params::c;
        ajs = aj.dot(s);
        bjs = bj.dot(s);
        a_bjs = aj * bjs;
        b_ajs = bi * ajs;
        pcj = (ajs * cos(argumentj) - bjs * sin(argumentj));
        psj = (ajs * sin(argumentj) + bjs * cos(argumentj));
        pc_1_j = ((s * ajs * sinth2 - aj) * cos(argumentj) -
            (s * bjs * sinth2 - bj) * sin(argumentj));
        ps_1_j = ((s * ajs * sinth2 - aj) * sin(argumentj) +
            (s * bjs * sinth2 - bj) * cos(argumentj));
        pcomj = -(omega0 / params::c) * (sin(theta)) * (a_bjs - b_ajs);
        Eigen::Vector<FloatType, 2> rij_xy =
            pc_1_i.cwiseProduct(pc_1_j) + ps_1_i.cwiseProduct(ps_1_j)
                + 2 * pcomi.cwiseProduct(pcomj);
        FloatType rij_z = (pci * pcj + psi * psj);
        resz += rij_z;
        resxy += rij_xy;
      }
      Eigen::Vector<FloatType, 2> ri_xy =
          (pc_1_i.cwiseProduct(pc_1_i) + ps_1_i.cwiseProduct(ps_1_i)
              + 2 * pcomi.cwiseProduct(pcomi)) / 2.0;
      resxy += ri_xy;
      FloatType ri_xz = (pci * pci + psi * psi) / 2;
      resz += ri_xz;
    }
    resxy = resxy * t_0 * o2 * o2;
    resz = resz * t_0 * (o2 * o2 * pow(sin(theta) * cos(theta), 2));
    res = resxy.sum() + resz;
    return res;
  };
}
References shared::params::c, my_concepts::GetElement(), my_concepts::GetValue(), i_2_function_, ifunction_, and shared::params::omega.
GetI2Function()
const DirectionGraph & dipoles::Dipoles::GetI2Function () const inline
{
    return i_2_function_;
  }
References i_2_function_.
GetIfunction()
const IntegrableFunction & dipoles::Dipoles::GetIfunction () const inline
{
    return ifunction_;
  }
References ifunction_.
GetMatrices()
void dipoles::Dipoles::GetMatrices (const Eigen::Vector< FloatType, 2 > & rim, FloatType r_mode, Eigen::Matrix< FloatType, 2, 2 > & k_1, Eigen::Matrix< FloatType, 2, 2 > & k_2) const protected
{
  k_1 << 3 * rim(0) * rim(0) / pow(r_mode, 5) - 1 / pow(r_mode, 3), 3 * rim(0) * rim(1) / pow(r_mode, 5),
      3 * rim(0) * rim(1) / pow(r_mode, 5), 3 * rim(1) * rim(1) / pow(r_mode, 5) - 1 / pow(r_mode, 3);
  k_2 << params::omega / (params::c * pow(r_mode, 2)), 0,
      0, params::omega / (params::c * pow(r_mode, 2));
}
References shared::params::c, and shared::params::omega.
Referenced by SetMatrixes().
GetMatrixx()
MatrixType dipoles::Dipoles::GetMatrixx ()
Retrieves matrix computed for system of equations.
{
  MatrixType matrixx;
  matrixx.resize(4 * n_, 4 * n_);
  matrixx.topLeftCorner(2 * n_, 2 * n_).noalias() = m_1_;
  matrixx.topRightCorner(2 * n_, 2 * n_).noalias() = -m_2_;
  matrixx.bottomLeftCorner(2 * n_, 2 * n_).noalias() = m_2_;
  matrixx.bottomRightCorner(2 * n_, 2 * n_).noalias() = m_1_;
  return matrixx;
}
References m_1_, m_2_, and n_.
GetRightPart()
const EigenVec & dipoles::Dipoles::GetRightPart ()
Returns reference to the right part for system of equations.
{
  return f_;
}
References f_.
InitArrays()
void dipoles::Dipoles::InitArrays () protected
Intializes dimensions for system of equations matrices.
{
  an_ = params::a / n_;
  m_1_.resize(2 * n_, 2 * n_);
  m_2_.resize(2 * n_, 2 * n_);
  f_.resize(4 * n_);
  for (int i = 0; i < n_; ++i) {
    f_(2 * i) = an_ * params::eps;
    f_(2 * i + 1) = 0;
    f_(2 * i + 2 * n_) = 0;
    f_(2 * i + 1 + 2 * n_) = an_ * params::eps;
  }
}
References shared::params::a, an_, shared::params::eps, f_, m_1_, m_2_, and n_.
Referenced by Dipoles(), LoadFromMatrix(), and SetNewCoordinates().
LoadFromMatrix()
void dipoles::Dipoles::LoadFromMatrix (const MatrixType & xi)
Loads system of equations matrix.
Parameters
xi
{
  this->n_ = xi.rows() / 4;
  InitArrays();
  m_1_ = xi.topLeftCorner(2 * n_, 2 * n_);
  m_2_ = xi.bottomLeftCorner(2 * n_, 2 * n_);
}
References InitArrays(), m_1_, m_2_, and n_.
SetMatrixes()
template<typename Container > void dipoles::Dipoles::SetMatrixes (const Container & xi) protected
Recalculates matrix values for dipole coordinates vector.
Template Parameters
Container
Parameters
xi
{
  std::vector<std::pair<int, int>> sectors(4);
  sectors[0] = {0, 0};
  sectors[1] = {0, 2 * n_};
  sectors[2] = {2 * n_, 0};
  sectors[3] = {2 * n_, 2 * n_};
  for (int i = 0; i < n_; ++i) {//MAC
    for (int m = 0; m < n_; ++m) {
      if (i == m) {
        Eigen::Matrix<FloatType, 2, 2> id = Eigen::Matrix<FloatType, 2, 2>::Identity() *
            (params::omega0 * params::omega0 -
                params::omega * params::omega);
        m_1_.template block<2, 2>(2 * i, 2 * m) = id;
      } else {
        Eigen::Vector<FloatType, 2> rim = TwoDVecDifference(m, i, xi);
        auto r_mode = GetDistance(i, m, xi);
        Eigen::Matrix<FloatType, 2, 2> k1;
        Eigen::Matrix<FloatType, 2, 2> k2;
        GetMatrices(rim, r_mode, k1, k2);
        auto arg = params::omega * r_mode / params::c;
        Eigen::Matrix<FloatType, 2, 2> tmpmatr = -an_ * (k1 * cos(arg) - k2 * sin(arg));
        m_1_.template block<2, 2>(2 * i, 2 * m) = tmpmatr;
      }
    }
  }
  for (int i = 0; i < n_; ++i) {//MBC
    for (int m = 0; m < n_; ++m) {
      if (i == m) {
        Eigen::Matrix<FloatType, 2, 2> id =
            Eigen::Matrix<FloatType, 2, 2>::Identity() * (params::yo * params::omega);
        m_2_.template block<2, 2>(2 * i, 2 * m) = -id;
      } else {
        Eigen::Vector<FloatType, 2> rim = TwoDVecDifference(m, i, xi);
        auto r_mode = GetDistance(i, m, xi);
        Eigen::Matrix<FloatType, 2, 2> k1;
        Eigen::Matrix<FloatType, 2, 2> k2;
        GetMatrices(rim, r_mode, k1, k2);
        auto arg = params::omega * r_mode / params::c;
        Eigen::Matrix<FloatType, 2, 2> tmpmatr = -an_ * (k2 * cos(arg) + k1 * sin(arg));
        m_2_.template block<2, 2>(2 * i, 2 * m) = tmpmatr;
      }
    }
  }
}
References an_, shared::params::c, GetDistance(), GetMatrices(), m_1_, m_2_, n_, shared::params::omega, shared::params::omega0, TwoDVecDifference(), and shared::params::yo.
Referenced by Dipoles(), and SetNewCoordinates().
SetNewCoordinates()
template<typename Container > requires HasSizeMethod<Container> void dipoles::Dipoles::SetNewCoordinates (const Container & xi)
Function that allows to Reset dipole coordinates.
This function is used to avoid memory reallocation if dipole object already have been initialized.
Template Parameters
Container
Parameters
xi
{
  if (this->f_.size() != xi.size() * 2) {
    this->n_ = xi.size() / 2;
    InitArrays();
  }
  SetMatrixes(xi);
}
References f_, InitArrays(), n_, and SetMatrixes().
Solve() [1/5]
template<typename Container = common_types::ReturnToDataType<ReturnType::EIGEN_VECTOR>> Container dipoles::Dipoles::Solve ()
Computes solution vector for dipole parameters and returns it in available format.
Template Parameters
Container
Solve() [2/5]
template<> Arr2EigenVec dipoles::Dipoles::Solve ()
{
  Eigen::PartialPivLU tt = (m_1_ * m_1_ + m_2_ * m_2_).lu();
  Eigen::Vector<FloatType, Eigen::Dynamic> solution_1;
  Eigen::Vector<FloatType, Eigen::Dynamic> solution_2;
  solution_1.resize(2 * n_);
  solution_2.resize(2 * n_);
  solution_1 = tt.solve(m_1_ * f_.block(0, 0, 2 * n_, 1) + m_2_ * f_.block(2 * n_, 0, 2 * n_, 1));
  solution_2 = tt.solve(m_1_ * f_.block(2 * n_, 0, 2 * n_, 1) - m_2_ * f_.block(0, 0, 2 * n_, 1));
  return {solution_1, solution_2};
}
References f_, m_1_, m_2_, and n_.
Solve() [3/5]
template<> EigenVec dipoles::Dipoles::Solve ()
{
  Eigen::PartialPivLU tt = (m_1_ * m_1_ + m_2_ * m_2_).lu();
  Eigen::Vector<FloatType, Eigen::Dynamic> solution;
  solution.resize(4 * n_);
  solution.block(0, 0, 2 * n_, 1) = tt.solve(
      m_1_ * f_.block(0, 0, 2 * n_, 1) + m_2_ * f_.block(2 * n_, 0, 2 * n_, 1));
  solution.block(2 * n_, 0, 2 * n_, 1) = tt.solve(
      m_1_ * f_.block(2 * n_, 0, 2 * n_, 1) - m_2_ * f_.block(0, 0, 2 * n_, 1));
  return solution;
}
References f_, m_1_, m_2_, and n_.
Solve() [4/5]
template<> StdVec dipoles::Dipoles::Solve ()
                      {
  std::vector<FloatType> sol(4 * n_);
  Eigen::PartialPivLU<Eigen::Matrix<FloatType, Eigen::Dynamic, Eigen::Dynamic>> tt = (m_1_ * m_1_ + m_2_ * m_2_).lu();
  Eigen::Map<Eigen::Vector<FloatType, Eigen::Dynamic>> solution(sol.data(), sol.size());
  solution.resize(4 * n_);
  solution.block(0, 0, 2 * n_, 1) = tt.solve(
      m_1_ * f_.block(0, 0, 2 * n_, 1) + m_2_ * f_.block(2 * n_, 0, 2 * n_, 1));
  solution.block(2 * n_, 0, 2 * n_, 1) = tt.solve(
      m_1_ * f_.block(2 * n_, 0, 2 * n_, 1) - m_2_ * f_.block(0, 0, 2 * n_, 1));
  return sol;
}
References f_, m_1_, m_2_, and n_.
Solve() [5/5]
template<> StdValarr dipoles::Dipoles::Solve ()
{
  StdValarr sol(4 * n_);
  Eigen::PartialPivLU<Eigen::Matrix<FloatType, Eigen::Dynamic, Eigen::Dynamic>> tt = (m_1_ * m_1_ + m_2_ * m_2_).lu();
  Eigen::Map<Eigen::Vector<FloatType, Eigen::Dynamic>> solution(&(sol[0]), sol.size());
  solution.resize(4 * n_);
  solution.block(0, 0, 2 * n_, 1) = tt.solve(
      m_1_ * f_.block(0, 0, 2 * n_, 1) + m_2_ * f_.block(2 * n_, 0, 2 * n_, 1));
  solution.block(2 * n_, 0, 2 * n_, 1) = tt.solve(
      m_1_ * f_.block(2 * n_, 0, 2 * n_, 1) - m_2_ * f_.block(0, 0, 2 * n_, 1));
  return sol;
}
References f_, m_1_, m_2_, and n_.
TwoDVecDifference()
template<typename Container > requires HasBracketOperator<Container> Eigen::Vector< FloatType, 2 > dipoles::Dipoles::TwoDVecDifference (size_t i1, size_t i2, Container & xi) protected
Computes vector difference for dipole coordinates.
older name getRIM
Template Parameters
Container
Parameters
i1
i2
xi
{
  FloatType d1;
  FloatType d2;
  if constexpr (my_concepts::HasBracketsNested<Container>) {
    d1 = xi[0][i1] - xi[0][i2];
    d2 = xi[1][i1] - xi[1][i2];
  } else {
    d1 = xi[i1] - xi[i2];
    d2 = xi[i1 + n_] - xi[i2 + n_];
  }
  return {d1, d2};
}
References n_.
Referenced by SetMatrixes().
Member Data Documentation
an_
FloatType dipoles::Dipoles::an_ = params::a protected
Referenced by InitArrays(), and SetMatrixes().
f_
Eigen::Vector<FloatType, Eigen::Dynamic> dipoles::Dipoles::f_ protected
Referenced by GetRightPart(), InitArrays(), SetNewCoordinates(), and Solve().
i_2_function_
DirectionGraph dipoles::Dipoles::i_2_function_ protected
Referenced by GetFullFunction(), and GetI2Function().
ifunction_
IntegrableFunction dipoles::Dipoles::ifunction_ protected
Referenced by GetFullFunction(), and GetIfunction().
m_1_
MatrixType dipoles::Dipoles::m_1_ protected
Referenced by GetMatrixx(), InitArrays(), LoadFromMatrix(), SetMatrixes(), and Solve().
m_2_
MatrixType dipoles::Dipoles::m_2_ protected
Referenced by GetMatrixx(), InitArrays(), LoadFromMatrix(), SetMatrixes(), and Solve().
n_
int dipoles::Dipoles::n_ protected
Referenced by Dipoles(), GetDistance(), GetMatrixx(), InitArrays(), LoadFromMatrix(), SetMatrixes(), SetNewCoordinates(), Solve(), and TwoDVecDifference().
The documentation for this class was generated from the following files:
computationalLib/include/math_core/Dipoles.h
computationalLib/lib/math_core/Dipoles.cpp