Distributed math architecture: mesh_storage::MeshCreator Class Reference
mesh_storage::MeshCreator Class Reference
Class that handles 3d mesh creation and parameters management.
#include <MeshCreator.h>
Public Member Functions
MeshCreator (bool construct=true)
Default MeshCreator constructor.
void ConstructMeshes (const DimType &dims, const LimType &lims)
Computes 2d meshgrid using dims,lims.
void ConstructMeshes (std::optional< DimType > dim_opt=std::nullopt, std::optional< LimType > lim_opt=std::nullopt)
Will substitute any null-opt with default values.
void ApplyFunction (const co::DirectionGraph &func)
Computes data[2] using provided Func function.
void ApplyIntegrate (const co::IntegrableFunction &func, FloatType a=0, FloatType b=kRr)
Uses numerical integration with range [a,b] compute data[2].
void PlotAndSave (const std::string &filename, const std::function< void(const std::string &filename, const MeshCreator &)> &plot_callback)
Calls provided callback to Plot this mesh.
Public Attributes
DimType dimensions_
LimType limits_
MeshArr< 3 > data_
Friends
MeshArr< 3 > SphericalTransformation (const MeshCreator &oth)
Cartesian to spherical coordinate transformation.
Detailed Description
Class that handles 3d mesh creation and parameters management.
Constructor & Destructor Documentation
MeshCreator()
mesh_storage::MeshCreator::MeshCreator (bool construct = true)
Default MeshCreator constructor.
Parameters
construct - will allocate memory for data arrays if is true
References data_, and dimensions_.
Member Function Documentation
ApplyFunction()
void mesh_storage::MeshCreator::ApplyFunction (const co::DirectionGraph & func)
Computes data[2] using provided Func function.
Parameters
func
References mesh_storage::ComputeFunction(), and data_.
Referenced by ApplyIntegrate().
ApplyIntegrate()
void mesh_storage::MeshCreator::ApplyIntegrate (const co::IntegrableFunction & func, FloatType a = 0, FloatType b = kRr)
Uses numerical integration with range [a,b] compute data[2].
Parameters
func
a
b
References ApplyFunction().
ConstructMeshes() [1/2]
void mesh_storage::MeshCreator::ConstructMeshes (const DimType & dims, const LimType & lims)
Computes 2d meshgrid using dims,lims.
Parameters
dims
lims
References data_, dimensions_, limits_, and mesh_storage::MyMeshGrid().
Referenced by ConstructMeshes(), print_utils::FromJson(), and print_utils::ParseMeshFrom().
ConstructMeshes() [2/2]
void mesh_storage::MeshCreator::ConstructMeshes (std::optional< DimType > dim_opt = std::nullopt, std::optional< LimType > lim_opt = std::nullopt)
Will substitute any null-opt with default values.
Parameters
dim_opt
lim_opt
References ConstructMeshes().
PlotAndSave()
void mesh_storage::MeshCreator::PlotAndSave (const std::string & filename, const std::function< void(const std::string &filename, const MeshCreator &)> & plot_callback) inline
Calls provided callback to Plot this mesh.
Parameters
filename
plot_callback
Todo:
remove deprecated callback
Friends And Related Function Documentation
SphericalTransformation
MeshArr<3> SphericalTransformation (const MeshCreator & oth) friend
Cartesian to spherical coordinate transformation.
Parameters
oth
Returns
Member Data Documentation
data_
MeshArr<3> mesh_storage::MeshCreator::data_
Referenced by ApplyFunction(), ConstructMeshes(), print_utils::FromJson(), MeshCreator(), print_utils::ParseMeshFrom(), mesh_storage::PrintDec(), print_utils::PrintMesh(), and print_utils::ToJson().
dimensions_
DimType mesh_storage::MeshCreator::dimensions_
Referenced by ConstructMeshes(), MeshCreator(), mesh_storage::PrintDec(), print_utils::PrintMesh(), and print_utils::ToJson().
limits_
LimType mesh_storage::MeshCreator::limits_
Referenced by ConstructMeshes(), print_utils::PrintMesh(), and print_utils::ToJson().
The documentation for this class was generated from the following files:
utilLib/include/common/MeshCreator.h
utilLib/lib/common/MeshCreator.cpp