Distributed math architecture: comp_services::BenchmarkRunner Class Reference
comp_services::BenchmarkRunner Class Reference
A class to run performance benchmarks for dipole and mesh computations.
#include <BenchmarkRunnerService.h>
Public Member Functions
BenchmarkRunner (const shared::BenchResVec &nss, const shared::BenchResVec &iter_counts)
Constructs a BenchmarkRunner with benchmark parameters.
std::pair< shared::BenchResVec, shared::BenchResVec > Run (bool use_omp_outer=true, int eigen_threads=0)
Runs the benchmark for all parameter pairs and returns the results.
Private Member Functions
shared::BenchResultType RunSingleBenchmark (size_t N, size_t conf_num, bool use_omp_outer, int eigen_threads)
Runs the benchmark for a single pair of N and conf_num.
Private Attributes
shared::BenchResVec ns_
shared::BenchResVec iter_counts_
chrono_clock::ChronoClockTemplate< std::milli > clk
Static Private Attributes
static constexpr double k_arange_ = 1e-6
static constexpr size_t iter_num_ = 10000
static thread_local auto ff_ = generators::get_normal_generator(0.0, k_arange_ * std::sqrt(2.0))
Detailed Description
A class to run performance benchmarks for dipole and mesh computations.
Constructor & Destructor Documentation
BenchmarkRunner()
comp_services::BenchmarkRunner::BenchmarkRunner (const shared::BenchResVec & nss, const shared::BenchResVec & iter_counts)
Constructs a BenchmarkRunner with benchmark parameters.
Parameters
nss
iter_counts
Exceptions
std::invalid_argument
References iter_counts_, and ns_.
Member Function Documentation
Run()
std::pair< shared::BenchResVec, shared::BenchResVec > comp_services::BenchmarkRunner::Run (bool use_omp_outer = true, int eigen_threads = 0)
Runs the benchmark for all parameter pairs and returns the results.
Parameters
use_omp_outer - uses openmp during runs
eigen_threads - sets num of eigen threads(0 for default num)
References clk, iter_counts_, shared::ns, ns_, and RunSingleBenchmark().
Referenced by comp_services::ComputationNodeService::RunBench().
RunSingleBenchmark()
shared::BenchResultType comp_services::BenchmarkRunner::RunSingleBenchmark (size_t N, size_t conf_num, bool use_omp_outer, int eigen_threads) private
Runs the benchmark for a single pair of N and conf_num.
Parameters
N
conf_num
References clk, ff_, dipoles::Dipoles::GetFullFunction(), dipoles::Dipoles::GetI2Function(), iter_num_, dipoles::Dipoles::SetNewCoordinates(), and dipoles::Dipoles::Solve().
Referenced by Run().
Member Data Documentation
clk
chrono_clock::ChronoClockTemplate<std::milli> comp_services::BenchmarkRunner::clk private
Referenced by Run(), and RunSingleBenchmark().
ff_
thread_local auto comp_services::BenchmarkRunner::ff_ = generators::get_normal_generator(0.0, k_arange_ * std::sqrt(2.0)) inline static private
Referenced by RunSingleBenchmark().
iter_counts_
shared::BenchResVec comp_services::BenchmarkRunner::iter_counts_ private
Referenced by BenchmarkRunner(), and Run().
iter_num_
constexpr size_t comp_services::BenchmarkRunner::iter_num_ = 10000 static constexpr private
Referenced by RunSingleBenchmark().
k_arange_
constexpr double comp_services::BenchmarkRunner::k_arange_ = 1e-6 static constexpr private
ns_
shared::BenchResVec comp_services::BenchmarkRunner::ns_ private
Referenced by BenchmarkRunner(), and Run().
The documentation for this class was generated from the following files:
computationalNode/include/service/BenchmarkRunnerService.h
computationalNode/src/service/BenchmarkRunnerService.cpp