Distributed math architecture: rest::v1::CompNode Class Reference
rest::v1::CompNode Class Reference
Public Types
using Cont = CompNode
Public Member Functions
CompNode ()
METHOD_LIST_BEGIN ADD_METHOD_TO (Cont::GetStatus, "v1/status", Get)
ADD_METHOD_TO (Cont::ConnectHandler, "v1/Connect", Post)
ADD_METHOD_TO (Cont::DisconnectHandler, "v1/Disconnect", Post)
METHOD_LIST_END void GetStatus (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
void ConnectHandler (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
void DisconnectHandler (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
Private Attributes
ComputationNodeService * handler_
Member Typedef Documentation
Cont
using rest::v1::CompNode::Cont = CompNode
Constructor & Destructor Documentation
CompNode()
rest::v1::CompNode::CompNode () inline
References handler_.
Member Function Documentation
ADD_METHOD_TO() [1/3]
rest::v1::CompNode::ADD_METHOD_TO (Cont::ConnectHandler , "v1/Connect" , Post)
ADD_METHOD_TO() [2/3]
rest::v1::CompNode::ADD_METHOD_TO (Cont::DisconnectHandler , "v1/Disconnect" , Post)
ADD_METHOD_TO() [3/3]
METHOD_LIST_BEGIN rest::v1::CompNode::ADD_METHOD_TO (Cont::GetStatus , "v1/status" , Get)
ConnectHandler()
void rest::v1::CompNode::ConnectHandler (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
References comp_services::ComputationNodeService::Connect(), and handler_.
DisconnectHandler()
void rest::v1::CompNode::DisconnectHandler (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
References comp_services::ComputationNodeService::Disconnect(), and handler_.
GetStatus()
void rest::v1::CompNode::GetStatus (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
References comp_services::ComputationNodeService::GetStatus(), and handler_.
Member Data Documentation
handler_
ComputationNodeService* rest::v1::CompNode::handler_ private
Referenced by CompNode(), ConnectHandler(), DisconnectHandler(), and GetStatus().
The documentation for this class was generated from the following files:
computationalNode/include/controller/CompNode.h
computationalNode/src/controller/CompNode.cpp