Distributed math architecture: network_types::PostgreSQLCStr Class Reference
network_types::PostgreSQLCStr Class Reference
Structure to store and format PostgreSQL connection string.
#include <connectionString.h>
Public Member Functions
PostgreSQLCStr ()
void FromString (std::string_view s) override
Parses fields from std::string_view.
PostgreSQLCStr (std::string_view user, std::string_view password, std::string_view host, std::string_view dbname, unsigned port)
void SetUser (std::string_view new_user)
void SetPassword (std::string_view new_password)
void SetHost (std::string_view new_host)
void SetPort (unsigned new_port)
void SetDbname (std::string_view new_dbname)
std::string_view GetUser () const
std::string_view GetPassword () const
std::string_view GetHost () const
std::string_view GetDbname () const
unsigned int GetPort () const
std::string GetVerboseName () const override
Retrieves cString contents for verbose logging.
Public Member Functions inherited from network_types::AbstractConnectionString
AbstractConnectionString ()=default
std::string to_string () const
explicit std::string type cast
operator std::string_view ()
implicit std::string_view cast
const char * CStr () const
Retrieves const char * representation.
bool operator== (const AbstractConnectionString &rhs) const
Protected Member Functions
void UpdateFormat () override
Protected Attributes
std::string user_
std::string password_
std::string host_
std::string dbname_
unsigned port_
Protected Attributes inherited from network_types::AbstractConnectionString
std::string formatted_string_
formatted string for c string
Detailed Description
Structure to store and format PostgreSQL connection string.
Constructor & Destructor Documentation
PostgreSQLCStr() [1/2]
network_types::PostgreSQLCStr::PostgreSQLCStr ()
PostgreSQLCStr() [2/2]
network_types::PostgreSQLCStr::PostgreSQLCStr (std::string_view user, std::string_view password, std::string_view host, std::string_view dbname, unsigned port)
Member Function Documentation
FromString()
void network_types::PostgreSQLCStr::FromString (std::string_view s) override virtual
Parses fields from std::string_view.
Parameters
s
Implements network_types::AbstractConnectionString.
References dbname_, host_, password_, port_, UpdateFormat(), network_types::UrlDecode(), and user_.
GetDbname()
std::string_view network_types::PostgreSQLCStr::GetDbname () const
References dbname_.
Referenced by db_common::CreateDatabase(), and db_common::DropDatabase().
GetHost()
std::string_view network_types::PostgreSQLCStr::GetHost () const
References host_.
GetPassword()
std::string_view network_types::PostgreSQLCStr::GetPassword () const
References password_.
GetPort()
unsigned int network_types::PostgreSQLCStr::GetPort () const
References port_.
GetUser()
std::string_view network_types::PostgreSQLCStr::GetUser () const
References user_.
Referenced by db_common::CreateDatabase().
GetVerboseName()
std::string network_types::PostgreSQLCStr::GetVerboseName () const override virtual
Retrieves cString contents for verbose logging.
Reimplemented from network_types::AbstractConnectionString.
References dbname_, host_, and port_.
Referenced by db_common::ExecuteTransaction(), and db_common::TryConnect().
SetDbname()
void network_types::PostgreSQLCStr::SetDbname (std::string_view new_dbname)
References dbname_, and UpdateFormat().
Referenced by db_common::CreateDatabase(), and db_common::DropDatabase().
SetHost()
void network_types::PostgreSQLCStr::SetHost (std::string_view new_host)
References host_, and UpdateFormat().
SetPassword()
void network_types::PostgreSQLCStr::SetPassword (std::string_view new_password)
References password_, and UpdateFormat().
SetPort()
void network_types::PostgreSQLCStr::SetPort (unsigned new_port)
References port_, and UpdateFormat().
SetUser()
void network_types::PostgreSQLCStr::SetUser (std::string_view new_user)
References UpdateFormat(), and user_.
UpdateFormat()
void network_types::PostgreSQLCStr::UpdateFormat () override protected virtual
Implements network_types::AbstractConnectionString.
References dbname_, network_types::AbstractConnectionString::formatted_string_, host_, password_, port_, and user_.
Referenced by FromString(), SetDbname(), SetHost(), SetPassword(), SetPort(), and SetUser().
Member Data Documentation
dbname_
std::string network_types::PostgreSQLCStr::dbname_ protected
Referenced by FromString(), GetDbname(), GetVerboseName(), SetDbname(), and UpdateFormat().
host_
std::string network_types::PostgreSQLCStr::host_ protected
Referenced by FromString(), GetHost(), GetVerboseName(), SetHost(), and UpdateFormat().
password_
std::string network_types::PostgreSQLCStr::password_ protected
Referenced by FromString(), GetPassword(), SetPassword(), and UpdateFormat().
port_
unsigned network_types::PostgreSQLCStr::port_ protected
Referenced by FromString(), GetPort(), GetVerboseName(), SetPort(), and UpdateFormat().
user_
std::string network_types::PostgreSQLCStr::user_ protected
Referenced by FromString(), GetUser(), SetUser(), and UpdateFormat().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/connectionString.h
computationalLib/lib/network_shared/connectionString.cpp