Distributed math architecture: amqp_common::AMQPService Class Reference
amqp_common::AMQPService Class Reference abstract
This class connection/disconnection semantics.
#include <amqpCommon.h>
Public Member Functions
AMQPService ()
AMQPService (const AMQPSQLCStr &connection_string)
void SetParameters (const AMQPSQLCStr &connection_string)
Sets most connection parameter.
bool IsConnected () const
const AMQPSQLCStr & GetCString () const
void Connect ()
Starts event Loop for service.
void Disconnect ()
Ends connection and channel to rabbitMQ This is the variant of soft disconnect.
~AMQPService ()
Calls Disconnect and frees used memory with smart pointers.
Protected Types
using GuardType = std::scoped_lock< std::mutex >
Protected Member Functions
virtual void Reconnect ()=0
virtual std::string ServiceName ()=0
Protected Attributes
boost::asio::io_service service_
service used for async event loop
boost::asio::io_service::work * work_
work object to handle loop work
MyHandler * handler_
custom connection handler
AMQP::TcpConnection * connection_
AMQP::TcpConnection pointer.
AMQP::TcpChannel * channel_
AMQP::TcpChannel pointer.
AMQPSQLCStr c_string_
connection string
std::thread service_thread_
thread to run boost service
std::promise< std::string > connection_promise_
bool promise_set_
Static Protected Attributes
static std::mutex s_mutex_
Detailed Description
This class connection/disconnection semantics.
This class allow to synchronously Connect
and soft disconnect.
Member Typedef Documentation
GuardType
using amqp_common::AMQPService::GuardType = std::scoped_lock<std::mutex> protected
Constructor & Destructor Documentation
AMQPService() [1/2]
amqp_common::AMQPService::AMQPService ()
AMQPService() [2/2]
amqp_common::AMQPService::AMQPService (const AMQPSQLCStr & connection_string)
~AMQPService()
amqp_common::AMQPService::~AMQPService ()
Calls Disconnect and frees used memory with smart pointers.
See also
AMQPPublisherService Disconnect
References Disconnect().
Member Function Documentation
Connect()
void amqp_common::AMQPService::Connect ()
Starts event Loop for service.
References c_string_, connection_promise_, Disconnect(), IsConnected(), promise_set_, Reconnect(), service_, service_thread_, ServiceName(), network_types::AbstractConnectionString::to_string(), and work_.
Referenced by comp_services::ComputationNodeService::Connect(), and main_services::MainNodeService::Connect().
Disconnect()
void amqp_common::AMQPService::Disconnect ()
Ends connection and channel to rabbitMQ This is the variant of soft disconnect.
References channel_, connection_, service_, service_thread_, and work_.
Referenced by Connect(), comp_services::ComputationNodeService::Disconnect(), main_services::MainNodeService::Disconnect(), amqp_common::AMQPPublisherService::~AMQPPublisherService(), and ~AMQPService().
GetCString()
const AMQPSQLCStr & amqp_common::AMQPService::GetCString () const
Returns
connection string
References c_string_.
Referenced by comp_services::ComputationNodeService::Connect(), main_services::MainNodeService::Connect(), and main_services::MainNodeService::Status().
IsConnected()
bool amqp_common::AMQPService::IsConnected () const
Returns
connection status
References handler_, and amqp_common::MyHandler::IsConnected().
Referenced by comp_services::ComputationNodeService::CheckConnection(), Connect(), comp_services::ComputationNodeService::Connect(), main_services::MainNodeService::Connect(), main_services::MainNodeService::ConnectNode(), comp_services::ComputationNodeService::Disconnect(), main_services::MainNodeService::Disconnect(), main_services::MainNodeService::DisconnectNode(), comp_services::ComputationNodeService::GetStatus(), main_services::MainNodeService::PublishMessage(), amqp_common::AMQPConsumerService::Reconnect(), amqp_common::AMQPPublisherService::Reconnect(), and main_services::MainNodeService::Status().
Reconnect()
virtual void amqp_common::AMQPService::Reconnect () protected pure virtual
Implemented in amqp_common::AMQPPublisherService, and amqp_common::AMQPConsumerService.
Referenced by Connect().
ServiceName()
virtual std::string amqp_common::AMQPService::ServiceName () protected pure virtual
Implemented in amqp_common::AMQPPublisherService, and amqp_common::AMQPConsumerService.
Referenced by Connect().
SetParameters()
void amqp_common::AMQPService::SetParameters (const AMQPSQLCStr & connection_string)
Sets most connection parameter.
Parameters
connection_string
References c_string_.
Member Data Documentation
c_string_
AMQPSQLCStr amqp_common::AMQPService::c_string_ protected
connection string
Referenced by Connect(), GetCString(), amqp_common::AMQPConsumerService::Reconnect(), amqp_common::AMQPPublisherService::Reconnect(), SetParameters(), amqp_common::AMQPPublisherService::SetParameters(), and amqp_common::AMQPConsumerService::SetParameters().
channel_
AMQP::TcpChannel* amqp_common::AMQPService::channel_ protected
AMQP::TcpChannel pointer.
Referenced by amqp_common::AMQPPublisherService::AddQueue(), Disconnect(), amqp_common::AMQPPublisherService::Publish(), amqp_common::AMQPConsumerService::Reconnect(), and amqp_common::AMQPPublisherService::Reconnect().
connection_
AMQP::TcpConnection* amqp_common::AMQPService::connection_ protected
AMQP::TcpConnection pointer.
Referenced by Disconnect(), amqp_common::AMQPConsumerService::Reconnect(), and amqp_common::AMQPPublisherService::Reconnect().
connection_promise_
std::promise<std::string> amqp_common::AMQPService::connection_promise_ protected
Referenced by Connect(), amqp_common::AMQPConsumerService::Reconnect(), and amqp_common::AMQPPublisherService::Reconnect().
handler_
MyHandler* amqp_common::AMQPService::handler_ protected
custom connection handler
Referenced by IsConnected(), amqp_common::AMQPConsumerService::Reconnect(), and amqp_common::AMQPPublisherService::Reconnect().
promise_set_
bool amqp_common::AMQPService::promise_set_ protected
Referenced by Connect(), amqp_common::AMQPConsumerService::Reconnect(), and amqp_common::AMQPPublisherService::Reconnect().
s_mutex_
std::mutex amqp_common::AMQPService::s_mutex_ inline static protected
Referenced by amqp_common::AMQPConsumerService::Reconnect(), and amqp_common::AMQPPublisherService::Reconnect().
service_
boost::asio::io_service amqp_common::AMQPService::service_ protected
service used for async event loop
Referenced by Connect(), and Disconnect().
service_thread_
std::thread amqp_common::AMQPService::service_thread_ protected
thread to run boost service
Referenced by Connect(), and Disconnect().
work_
boost::asio::io_service::work* amqp_common::AMQPService::work_ protected
work object to handle loop work
Referenced by Connect(), and Disconnect().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/amqpCommon.h
computationalLib/lib/network_shared/amqpCommon.cpp