Distributed math architecture: amqp_common::AMQPConsumerService Class Reference
amqp_common::AMQPConsumerService Class Reference
Service that allow to start and end reading event Loop from specified queue.
#include <AMQPConsumerService.h>
Public Member Functions
AMQPConsumerService ()
AMQPConsumerService (const AMQPSQLCStr &connection_string, const std::string &queue_name)
void SetParameters (const AMQPSQLCStr &connection_string, const std::string &queue_name)
void SetMessageCallback (MessageCallback callback)
Sets message processing callback.
Public Member Functions inherited from amqp_common::AMQPService
AMQPService ()
AMQPService (const AMQPSQLCStr &connection_string)
void SetParameters (const AMQPSQLCStr &connection_string)
Sets most connection parameter.
bool IsConnected () const
const AMQPSQLCStr & GetCString () const
void Connect ()
Starts event Loop for service.
void Disconnect ()
Ends connection and channel to rabbitMQ This is the variant of soft disconnect.
~AMQPService ()
Calls Disconnect and frees used memory with smart pointers.
Private Member Functions
void Reconnect () override
Reconnects to specified queue Restarts amqp connection and channel objects. Specifies message management callbacks.
std::string ServiceName () override
Private Attributes
std::string queue_
queue to which the srvice will listen
MessageCallback message_callback_
callback that processes incoming messages
Additional Inherited Members
Protected Types inherited from amqp_common::AMQPService
using GuardType = std::scoped_lock< std::mutex >
Protected Attributes inherited from amqp_common::AMQPService
boost::asio::io_service service_
service used for async event loop
boost::asio::io_service::work * work_
work object to handle loop work
MyHandler * handler_
custom connection handler
AMQP::TcpConnection * connection_
AMQP::TcpConnection pointer.
AMQP::TcpChannel * channel_
AMQP::TcpChannel pointer.
AMQPSQLCStr c_string_
connection string
std::thread service_thread_
thread to run boost service
std::promise< std::string > connection_promise_
bool promise_set_
Static Protected Attributes inherited from amqp_common::AMQPService
static std::mutex s_mutex_
Detailed Description
Service that allow to start and end reading event Loop from specified queue.
Constructor & Destructor Documentation
AMQPConsumerService() [1/2]
amqp_common::AMQPConsumerService::AMQPConsumerService ()
AMQPConsumerService() [2/2]
amqp_common::AMQPConsumerService::AMQPConsumerService (const AMQPSQLCStr & connection_string, const std::string & queue_name)
Parameters
connection_string
queue_name
Member Function Documentation
Reconnect()
void amqp_common::AMQPConsumerService::Reconnect () override private virtual
Reconnects to specified queue Restarts amqp connection and channel objects. Specifies message management callbacks.
Implements amqp_common::AMQPService.
References amqp_common::AMQPService::c_string_, amqp_common::AMQPService::channel_, amqp_common::AMQPService::connection_, amqp_common::AMQPService::connection_promise_, amqp_common::DefaultMessageCallback(), amqp_common::AMQPService::handler_, amqp_common::AMQPService::IsConnected(), message_callback_, amqp_common::AMQPService::promise_set_, queue_, amqp_common::AMQPService::s_mutex_, network_types::AbstractConnectionString::to_string(), and VARIABLE_NAME.
ServiceName()
std::string amqp_common::AMQPConsumerService::ServiceName () override private virtual
Implements amqp_common::AMQPService.
SetMessageCallback()
void amqp_common::AMQPConsumerService::SetMessageCallback (MessageCallback callback)
Sets message processing callback.
Parameters
callback
References message_callback_.
Referenced by comp_services::ComputationNodeService::Connect().
SetParameters()
void amqp_common::AMQPConsumerService::SetParameters (const AMQPSQLCStr & connection_string, const std::string & queue_name)
Parameters
connection_string
queue_name
References amqp_common::AMQPService::c_string_, and queue_.
Referenced by comp_services::ComputationNodeService::Connect().
Member Data Documentation
message_callback_
MessageCallback amqp_common::AMQPConsumerService::message_callback_ private
callback that processes incoming messages
Referenced by Reconnect(), and SetMessageCallback().
queue_
std::string amqp_common::AMQPConsumerService::queue_ private
queue to which the srvice will listen
Referenced by Reconnect(), and SetParameters().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/AMQPConsumerService.h
computationalLib/lib/network_shared/AMQPConsumerService.cpp