Distributed math architecture: network_types::AbstractConnectionString Class Reference
network_types::AbstractConnectionString Class Reference abstract
us it for verbose names
#include <connectionString.h>
Public Member Functions
AbstractConnectionString ()=default
virtual void FromString (std::string_view s)=0
Parses fields from std::string_view.
std::string to_string () const
explicit std::string type cast
operator std::string_view ()
implicit std::string_view cast
virtual std::string GetVerboseName () const
Retrieves cString contents for verbose logging.
const char * CStr () const
Retrieves const char * representation.
bool operator== (const AbstractConnectionString &rhs) const
Protected Member Functions
virtual void UpdateFormat ()=0
Protected Attributes
std::string formatted_string_
formatted string for c string
Detailed Description
us it for verbose names
Default interfacer for the connection strings
Constructor & Destructor Documentation
AbstractConnectionString()
network_types::AbstractConnectionString::AbstractConnectionString () default
Member Function Documentation
CStr()
const char * network_types::AbstractConnectionString::CStr () const
Retrieves const char * representation.
References formatted_string_.
Referenced by db_common::TryConnect().
FromString()
virtual void network_types::AbstractConnectionString::FromString (std::string_view s) pure virtual
Parses fields from std::string_view.
Parameters
s
Implemented in network_types::AMQPSQLCStr, and network_types::PostgreSQLCStr.
GetVerboseName()
std::string network_types::AbstractConnectionString::GetVerboseName () const virtual
Retrieves cString contents for verbose logging.
Reimplemented in network_types::AMQPSQLCStr, and network_types::PostgreSQLCStr.
operator std::string_view()
network_types::AbstractConnectionString::operator std::string_view ()
implicit std::string_view cast
operator==()
bool network_types::AbstractConnectionString::operator== (const AbstractConnectionString & rhs) const
References formatted_string_.
to_string()
std::string network_types::AbstractConnectionString::to_string () const
explicit std::string type cast
Cast to std::string
References formatted_string_.
Referenced by amqp_common::AMQPService::Connect(), main_services::MainNodeService::Connect(), amqp_common::ConstructCString(), amqp_common::AMQPConsumerService::Reconnect(), amqp_common::AMQPPublisherService::Reconnect(), and main_services::MainNodeService::Status().
UpdateFormat()
virtual void network_types::AbstractConnectionString::UpdateFormat () protected pure virtual
Implemented in network_types::AMQPSQLCStr, and network_types::PostgreSQLCStr.
Member Data Documentation
formatted_string_
std::string network_types::AbstractConnectionString::formatted_string_ protected
formatted string for c string
Referenced by CStr(), operator==(), to_string(), network_types::PostgreSQLCStr::UpdateFormat(), and network_types::AMQPSQLCStr::UpdateFormat().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/connectionString.h
computationalLib/lib/network_shared/connectionString.cpp