Distributed math architecture: rest::v1::ClusterConfigController Class Reference
rest::v1::ClusterConfigController Class Reference
Drogon service for main node.
Public Types
using Cont = ClusterConfigController
Public Member Functions
ClusterConfigController ()
Initializes MainNodeService with preconfigured credentials provider.
METHOD_LIST_BEGIN ADD_METHOD_TO (Cont::GetStatus, "v1/status", Get)
ADD_METHOD_TO (Cont::ConnectNodeHandler, "v1/connect_node?ip={ip}", Post)
ADD_METHOD_TO (Cont::DisconnectNodeHandler, "v1/disconnect_node?ip={ip}", Post)
ADD_METHOD_TO (Cont::ConnectQ, "v1/connect_publisher", Post)
ADD_METHOD_TO (Cont::DisconnectQ, "v1/disconnect_publisher", Post)
ADD_METHOD_TO (Cont::SentToExecution, "v1/send_task", Put)
METHOD_LIST_END void GetStatus (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
Retrieves the status of whole cluster.
void ConnectNodeHandler (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback, const std::string &host_port)
Connects node to computational cluster.
void DisconnectNodeHandler (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback, const std::string &host_port)
Disconnects node to computational cluster.
void SentToExecution (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
Sends task to be sharded and published into queues for workers.
void ConnectQ (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
Connects main node to RabbitMQ.
void DisconnectQ (const HttpRequestPtr &req, std::function< void(const HttpResponsePtr &)> &&callback)
Disconnects main node from RabbitMQ.
Private Attributes
MainNodeService * main_node_service_
Detailed Description
Drogon service for main node.
Member Typedef Documentation
Cont
using rest::v1::ClusterConfigController::Cont = ClusterConfigController
Todo:
/rebalance
Todo:
ping(measures latencies)?
Constructor & Destructor Documentation
ClusterConfigController()
rest::v1::ClusterConfigController::ClusterConfigController () inline
Initializes MainNodeService with preconfigured credentials provider.
References main_node_service_.
Member Function Documentation
ADD_METHOD_TO() [1/6]
rest::v1::ClusterConfigController::ADD_METHOD_TO (Cont::ConnectNodeHandler)
ADD_METHOD_TO() [2/6]
rest::v1::ClusterConfigController::ADD_METHOD_TO (Cont::ConnectQ , "v1/connect_publisher" , Post)
ADD_METHOD_TO() [3/6]
rest::v1::ClusterConfigController::ADD_METHOD_TO (Cont::DisconnectNodeHandler)
ADD_METHOD_TO() [4/6]
rest::v1::ClusterConfigController::ADD_METHOD_TO (Cont::DisconnectQ , "v1/disconnect_publisher" , Post)
ADD_METHOD_TO() [5/6]
METHOD_LIST_BEGIN rest::v1::ClusterConfigController::ADD_METHOD_TO (Cont::GetStatus , "v1/status" , Get)
ADD_METHOD_TO() [6/6]
rest::v1::ClusterConfigController::ADD_METHOD_TO (Cont::SentToExecution , "v1/send_task" , Put)
ConnectNodeHandler()
void rest::v1::ClusterConfigController::ConnectNodeHandler (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback, const std::string & host_port)
Connects node to computational cluster.
Parameters
req
callback
host_port Requires main node to be connected to RabbitMQ
See also
ClusterConfigController::ConnectQ
References main_services::MainNodeService::ConnectNode(), and main_node_service_.
ConnectQ()
void rest::v1::ClusterConfigController::ConnectQ (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
Connects main node to RabbitMQ.
Parameters
req
callback Main node connects to RabbitMQ in the following manner:
It initializes event loop of AMQPPublisherService
It creates all the objects(if not exists) specified in members
See also
amqp_common::AMQPPublisherService
References main_services::MainNodeService::Connect(), and main_node_service_.
DisconnectNodeHandler()
void rest::v1::ClusterConfigController::DisconnectNodeHandler (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback, const std::string & host_port)
Disconnects node to computational cluster.
Parameters
req
callback
host_port Requires main node to be connected to RabbitMQ
See also
ClusterConfigController::ConnectQ
References main_services::MainNodeService::DisconnectNode(), and main_node_service_.
DisconnectQ()
void rest::v1::ClusterConfigController::DisconnectQ (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
Disconnects main node from RabbitMQ.
Parameters
req
callback
See also
ClusterConfigController::ConnectQ
References main_services::MainNodeService::Disconnect(), and main_node_service_.
GetStatus()
void rest::v1::ClusterConfigController::GetStatus (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
Retrieves the status of whole cluster.
Parameters
req
callback
References main_node_service_, and main_services::MainNodeService::Status().
SentToExecution()
void rest::v1::ClusterConfigController::SentToExecution (const HttpRequestPtr & req, std::function< void(const HttpResponsePtr &)> && callback)
Sends task to be sharded and published into queues for workers.
Parameters
req
callback Requires main node to be connected to RabbitMQ
See also
ClusterConfigController::ConnectQ
References main_node_service_, and main_services::MainNodeService::SendToExecution().
Member Data Documentation
main_node_service_
MainNodeService* rest::v1::ClusterConfigController::main_node_service_ private
Referenced by ClusterConfigController(), ConnectNodeHandler(), ConnectQ(), DisconnectNodeHandler(), DisconnectQ(), GetStatus(), and SentToExecution().
The documentation for this class was generated from the following files:
mainNode/include/controller/ClusterConfigController.h
mainNode/src/controller/ClusterConfigController.cpp