Distributed math architecture: amqp_common::MyHandler Class Reference
amqp_common::MyHandler Class Reference
Custom handler for connection events logging.
Public Member Functions
MyHandler (boost::asio::io_service &service, boost::asio::io_service::work *&work_ref)
void onClosed (AMQP::TcpConnection *connection) override
Method that is called on connection close.
void onError (AMQP::TcpConnection *connection, const char *message) override
Method that is called on connection error.
void onConnected (AMQP::TcpConnection *connection) override
Method that is called when connection is established.
bool IsConnected () const
Gets handler connection status.
Private Member Functions
void ResetLoop ()
Resets work to stop event loop.
Private Attributes
WorkPtr & m_work_
bool connected_
< work pointer to handle event loop
Detailed Description
Custom handler for connection events logging.
Constructor & Destructor Documentation
MyHandler()
amqp_common::MyHandler::MyHandler (boost::asio::io_service & service, boost::asio::io_service::work *& work_ref)
Member Function Documentation
IsConnected()
bool amqp_common::MyHandler::IsConnected () const
Gets handler connection status.
References connected_.
Referenced by amqp_common::AMQPService::IsConnected().
onClosed()
void amqp_common::MyHandler::onClosed (AMQP::TcpConnection * connection) inline override
Method that is called on connection close.
Parameters
connection
References ResetLoop().
onConnected()
void amqp_common::MyHandler::onConnected (AMQP::TcpConnection * connection) inline override
Method that is called when connection is established.
Parameters
connection
References connected_.
onError()
void amqp_common::MyHandler::onError (AMQP::TcpConnection * connection, const char * message) inline override
Method that is called on connection error.
Parameters
connection
message
References ResetLoop().
ResetLoop()
void amqp_common::MyHandler::ResetLoop () inline private
Resets work to stop event loop.
References connected_, and m_work_.
Referenced by onClosed(), and onError().
Member Data Documentation
connected_
bool amqp_common::MyHandler::connected_ private
< work pointer to handle event loop
Referenced by IsConnected(), onConnected(), and ResetLoop().
m_work_
WorkPtr& amqp_common::MyHandler::m_work_ private
Referenced by ResetLoop().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/amqpCommon.h
computationalLib/lib/network_shared/amqpCommon.cpp