Distributed math architecture: main_services::WorkerManagementService Class Reference
main_services::WorkerManagementService Class Reference
Class for worker node enumeration and management.
Public Member Functions
Json::Value GetStatus ()
returns list of lists with all nodes meta information
WorkerManagementService ()
Json::Value AddNewNode (const std::string &host_port)
Upsets new node into node list This method doesn't perform connection operation, but is used to update node information.
Json::Value ConnectNode (const std::string &host_port, drogon::HttpRequestPtr req1)
Connects node to computational cluster This method performs http request to connect worker and retrieve benchmark results. Successful request will result in node bench reassignment.
Json::Value DisconnectNode (const std::string &host_port)
Disconnects worker node from cluster This method calls disconnect http request.
auto begin ()
auto end ()
const BenchResVec GetSum () const
Private Types
using NodeStorageType = std::unordered_map< NodeStatus, std::unordered_map< std::string, ComputationalNode > >
Private Member Functions
void MoveNode (const std::string &host_port, const NodeStatus &from, const NodeStatus &to)
Private Attributes
NodeStorageType worker_nodes_
map of maps to manage worker nodes
std::string q_host_
queue host_
std::valarray< uint64_t > normalized_
Detailed Description
Class for worker node enumeration and management.
This class is dedicated to store and manage worker nodes information. Currently only Active(connected and running) nodes are used for message processing.
Member Typedef Documentation
NodeStorageType
using main_services::WorkerManagementService::NodeStorageType = std::unordered_map<NodeStatus, std::unordered_map<std::string, ComputationalNode> > private
Constructor & Destructor Documentation
WorkerManagementService()
main_services::WorkerManagementService::WorkerManagementService () inline
References shared::DefaultBench(), and normalized_.
Member Function Documentation
AddNewNode()
Json::Value main_services::WorkerManagementService::AddNewNode (const std::string & host_port)
Upsets new node into node list This method doesn't perform connection operation, but is used to update node information.
Parameters
host_port
Returns
empty Json::Value
Json:: Value with "status"=409 - if node exists and is Active
References main_services::ACTIVE, main_services::ComputationalNode::http_client_, main_services::INACTIVE, main_services::ComputationalNode::st_, and worker_nodes_.
Referenced by main_services::MainNodeService::ConnectNode().
begin()
auto main_services::WorkerManagementService::begin () inline
Returns
begin iterator to map of Active nodes
See also
NodeStatus::ACTIVE
References main_services::ACTIVE, and worker_nodes_.
Referenced by main_services::MainNodeService::SendToExecution().
ConnectNode()
Json::Value main_services::WorkerManagementService::ConnectNode (const std::string & host_port, drogon::HttpRequestPtr req1)
Connects node to computational cluster This method performs http request to connect worker and retrieve benchmark results. Successful request will result in node bench reassignment.
Parameters
host_port
req1
Returns
Json::Value with "node_output" that contains results
Json:: Value with "status"=504 - if worker cannot be accessed for specified host_port
Json:: Value with "status">=400 - if any abnormal http code is received
References main_services::ACTIVE, main_services::INACTIVE, MoveNode(), normalized_, and worker_nodes_.
Referenced by main_services::MainNodeService::ConnectNode().
DisconnectNode()
Json::Value main_services::WorkerManagementService::DisconnectNode (const std::string & host_port)
Disconnects worker node from cluster This method calls disconnect http request.
Parameters
host_port
Returns
Json::Value with node Output
Json:: Value with "status"=409 - if there is no Active node with specified host and port
Json:: Value with "status"=504 - if worker cannot be accessed for specified host_port
Json:: Value with "status">=400 - if any abnormal http code is received
References main_services::ACTIVE, main_services::INACTIVE, MoveNode(), normalized_, and worker_nodes_.
Referenced by main_services::MainNodeService::DisconnectNode().
end()
auto main_services::WorkerManagementService::end () inline
Returns
end iterator to map of Active nodes
See also
NodeStatus::ACTIVE
References main_services::ACTIVE, and worker_nodes_.
Referenced by main_services::MainNodeService::SendToExecution().
GetStatus()
Json::Value main_services::WorkerManagementService::GetStatus ()
returns list of lists with all nodes meta information
Returns
Json::Value
References print_utils::ContinuousToJson(), main_services::kNodeStatusToStr, and worker_nodes_.
Referenced by main_services::MainNodeService::Status().
GetSum()
const BenchResVec main_services::WorkerManagementService::GetSum () const
Returns
normalization coefficients for becnmark speed results
References normalized_.
Referenced by main_services::MainNodeService::SendToExecution().
MoveNode()
void main_services::WorkerManagementService::MoveNode (const std::string & host_port, const NodeStatus & from, const NodeStatus & to) private
Moves node between map entries
Parameters
host_port
from
to
References worker_nodes_.
Referenced by ConnectNode(), and DisconnectNode().
Member Data Documentation
normalized_
std::valarray<uint64_t> main_services::WorkerManagementService::normalized_ private
Referenced by ConnectNode(), DisconnectNode(), GetSum(), and WorkerManagementService().
q_host_
std::string main_services::WorkerManagementService::q_host_ private
queue host_
worker_nodes_
NodeStorageType main_services::WorkerManagementService::worker_nodes_ private
map of maps to manage worker nodes
Referenced by AddNewNode(), begin(), ConnectNode(), DisconnectNode(), end(), GetStatus(), and MoveNode().
The documentation for this class was generated from the following files:
mainNode/include/service/WorkerManagementService.h
mainNode/src/service/WorkerManagementService.cpp