Distributed math architecture: bench_utils::BenchmarkHandler< range > Class Template Reference
bench_utils::BenchmarkHandler< range > Class Template Reference
Class that handles benchmark file creation time measurements and other functionality.
#include <BenchmarkHandler.h>
Public Types
using Clk1 = ClockType< range >
Public Member Functions
BenchmarkHandler (std::string_view name, std::optional< std::string > path=std::nullopt)
template<typename... ARRAYS>
constexpr void RunBenchmark (const std::function< std::string(typename ARRAYS::value_type ...)> &bench_name_generator, const std::function< void(Clk1 &, fu::FileHandler &, size_t &, typename ARRAYS::value_type ...)> &bench_function, ARRAYS...arrays)
void SnapshotTimers (Clk1 &clk, const std::string &preprint, const std::string &delim="\n", size_t multiplier=1)
Prints each entry in clk to a designated file.
void PrintClocks ()
Prints global clock results into designated file.
~BenchmarkHandler ()
Static Public Attributes
static std::filesystem::path ddpath_ = "timers"
Private Attributes
fu::FileHandler fh_
std::string benchmark_name_
Clk1 clk_arr_
size_t mul_
Detailed Description
template<typename range = std::micro>
class bench_utils::BenchmarkHandler< range >
Class that handles benchmark file creation time measurements and other functionality.
Member Typedef Documentation
Clk1
template<typename range = std::micro> using bench_utils::BenchmarkHandler< range >::Clk1 = ClockType<range>
Constructor & Destructor Documentation
BenchmarkHandler()
template<typename range > bench_utils::BenchmarkHandler< range >::BenchmarkHandler (std::string_view name, std::optional< std::string > path = std::nullopt) explicit
Parameters
name -benchmark name
path - may be optional -> current directory will be used
~BenchmarkHandler()
template<typename range = std::micro> bench_utils::BenchmarkHandler< range >::~BenchmarkHandler () inline
References file_utils::FileHandler::CloseFiles(), bench_utils::BenchmarkHandler< range >::fh_, and bench_utils::BenchmarkHandler< range >::PrintClocks().
Member Function Documentation
PrintClocks()
template<typename range = std::micro> void bench_utils::BenchmarkHandler< range >::PrintClocks () inline
Prints global clock results into designated file.
References bench_utils::BenchmarkHandler< range >::clk_arr_, bench_utils::BenchmarkHandler< range >::fh_, file_utils::FileHandler::Output(), and file_utils::FileHandler::Upsert().
Referenced by bench_utils::BenchmarkHandler< range >::~BenchmarkHandler().
RunBenchmark()
template<typename range > template<typename... ARRAYS> constexpr void bench_utils::BenchmarkHandler< range >::RunBenchmark (const std::function< std::string(typename ARRAYS::value_type ...)> & bench_name_generator, const std::function< void(Clk1 &, fu::FileHandler &, size_t &, typename ARRAYS::value_type ...)> & bench_function, ARRAYS... arrays) constexpr
References timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::advance(), bench_utils::CartesianProduct(), file_utils::CreateDirIfNotPresent(), and print_utils::TupleToString().
SnapshotTimers()
template<typename range > void bench_utils::BenchmarkHandler< range >::SnapshotTimers (Clk1 & clk, const std::string & preprint, const std::string & delim = "\n", size_t multiplier = 1)
Prints each entry in clk to a designated file.
Parameters
clk
preprint - is printed before each entry
delim - delimeter that is printed after each timer record
multiplier - timer time is multiplied by given multiplier(defaults to 1)
Member Data Documentation
benchmark_name_
template<typename range = std::micro> std::string bench_utils::BenchmarkHandler< range >::benchmark_name_ private
clk_arr_
template<typename range = std::micro> Clk1 bench_utils::BenchmarkHandler< range >::clk_arr_ private
Referenced by bench_utils::BenchmarkHandler< range >::PrintClocks().
ddpath_
template<typename range = std::micro> std::filesystem::path bench_utils::BenchmarkHandler< range >::ddpath_ = "timers" inline static
Template Parameters
ARRAYS - input arrays types for cartessian product
Parameters
benchNameGenerator - function that generates iteration name
benchFunction - function that performs benchmark iteration
arrays - arrays for cartessian product
fh_
template<typename range = std::micro> fu::FileHandler bench_utils::BenchmarkHandler< range >::fh_ private
Referenced by bench_utils::BenchmarkHandler< range >::PrintClocks(), and bench_utils::BenchmarkHandler< range >::~BenchmarkHandler().
mul_
template<typename range = std::micro> size_t bench_utils::BenchmarkHandler< range >::mul_ private
The documentation for this class was generated from the following file:
computationalLib/test/BenchmarkHandler.h