Distributed math architecture: file_utils::FileHandler Class Reference
file_utils::FileHandler Class Reference
Sample class that handles dynamic file opening and Output.
#include <FileHandler.h>
Public Member Functions
FileHandler (const std::string &parent_path)
void Open (const std::string &filename, std::ios_base::openmode mode=std::ios_base::out)
Opens file with given permissions.
void Close (const std::string &filename)
Closes filename with given name.
bool Upsert (const std::string &filename, std::ios_base::openmode mode=std::ios_base::out)
Adds and opens filename to write with given permissions.
bool Contains (const std::string &filename)
Contains wrapper.
void CloseFiles ()
Closes all files from this instance of fileHandler.
~FileHandler ()
template<typename T >
void Print (OstreamPtr &out_ptr, const T &pr)
Print pr to selected outPtr.
template<bool checks = true, typename T >
void Output (const std::string &filename, const T &printed_val)
Wrapper for fileHandler::Print to printImpl data to designated file.
const fs::path & GetParentPath () const
Private Attributes
fs::path parent_path_
std::unordered_map< std::string, OstreamPtr > file_map_
Detailed Description
Sample class that handles dynamic file opening and Output.
Constructor & Destructor Documentation
FileHandler()
file_utils::FileHandler::FileHandler (const std::string & parent_path) explicit
Creates parent_path if it doesn't exist;
filenames in this class are stored in format parent_path/filename
Parameters
parent_path
References file_utils::CreateDirIfNotPresent(), and parent_path_.
~FileHandler()
file_utils::FileHandler::~FileHandler () inline
References CloseFiles().
Member Function Documentation
Close()
void file_utils::FileHandler::Close (const std::string & filename)
Closes filename with given name.
Parameters
filename
References file_map_, and parent_path_.
CloseFiles()
void file_utils::FileHandler::CloseFiles ()
Closes all files from this instance of fileHandler.
References file_map_.
Referenced by bench_utils::BenchmarkHandler< range >::~BenchmarkHandler(), and ~FileHandler().
Contains()
bool file_utils::FileHandler::Contains (const std::string & filename)
Contains wrapper.
Parameters
filename
References file_map_, and parent_path_.
GetParentPath()
const fs::path & file_utils::FileHandler::GetParentPath () const
References parent_path_.
Open()
void file_utils::FileHandler::Open (const std::string & filename, std::ios_base::openmode mode = std::ios_base::out)
Opens file with given permissions.
filename must be present in class
Parameters
filename
References file_map_, and parent_path_.
Output()
template<bool checks, typename T > void file_utils::FileHandler::Output (const std::string & filename, const T & printed_val)
Wrapper for fileHandler::Print to printImpl data to designated file.
Template Parameters
checks
T
Parameters
filename
printed_val
See also
fileHandler::printImpl
References file_map_, parent_path_, Print(), and Upsert().
Referenced by bench_utils::BenchmarkHandler< range >::PrintClocks().
Print()
template<typename T > void file_utils::FileHandler::Print (OstreamPtr & out_ptr, const T & pr)
Print pr to selected outPtr.
user mus implement std::ostream& operator<< for it
Template Parameters
T
Parameters
out_ptr
pr
Referenced by Output().
Upsert()
bool file_utils::FileHandler::Upsert (const std::string & filename, std::ios_base::openmode mode = std::ios_base::out)
Adds and opens filename to write with given permissions.
If file is already present in fileHandler it'l be opened in case it's closed
Parameters
filename
mode
Returns
file->is_open()
References file_map_, and parent_path_.
Referenced by Output(), and bench_utils::BenchmarkHandler< range >::PrintClocks().
Member Data Documentation
file_map_
std::unordered_map<std::string, OstreamPtr> file_utils::FileHandler::file_map_ private
Referenced by Close(), CloseFiles(), Contains(), Open(), Output(), and Upsert().
parent_path_
fs::path file_utils::FileHandler::parent_path_ private
Referenced by Close(), Contains(), FileHandler(), GetParentPath(), Open(), Output(), and Upsert().
The documentation for this class was generated from the following files:
utilLib/include/testingUtils/FileHandler.h
utilLib/lib/testingUtils/FileHandler.cpp