Distributed math architecture: timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter > Class Template Reference
timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter > Class Template Reference
Clock array template class.
Classes
struct timeStore
Public Member Functions
void Reset ()
void ResetTimer (const LocationType &location)
resets timer value for one timer
void Tik (const std::source_location &location=std::source_location::current())
void Tak (const std::source_location &location=std::source_location::current())
LocationType TikLoc (const std::source_location &location=std::source_location::current())
std::pair< std::source_location, LocationType > TikPair (const std::source_location &location=std::source_location::current())
decltype(auto) begin () const
decltype(auto) end () const
auto cbegin () const
auto cend () const
auto & operator[] (const LocationType &loc)
bool contains (const LocationType &loc) const
void advance (ClockArray &other)
adds up all timers from other timer current timer
Private Types
using GuardType = std::scoped_lock< std::mutex >
Private Attributes
std::map< LocationType, timeStore, LocationComparator > timers_
std::map< LocationType, inType, LocationComparator > start_ing_timers_
std::stack< LocationType > to_tak_
Static Private Attributes
static std::mutex s_mutex_
Friends
std::ostream & operator<< (std::ostream &out, const ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter > &ts)
Detailed Description
template<typename OutType, typename inType, inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter>
requires std::is_floating_point_v<OutType>
class timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >
Clock array template class.
Template Parameters
OutType double type tha will be printed
inType Type that timeGetter return
timeGetter function that return current time
sourceTypeConverter function that converts source location to inner representation of it
timeConverter a function that casts time difference to type
Member Typedef Documentation
GuardType
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> using timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::GuardType = std::scoped_lock<std::mutex> private
Member Function Documentation
advance()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location) sourceTypeConverter, OutType(*)(inType, inType) timeConverter> requires std::is_floating_point_v<OutType> or std::is_integral_v< OutType > void timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::advance (ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter > & other)
adds up all timers from other timer current timer
Parameters
other
Referenced by bench_utils::BenchmarkHandler< range >::RunBenchmark().
begin()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> decltype(auto) timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::begin () const inline
cbegin()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> auto timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::cbegin () const inline
cend()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> auto timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::cend () const inline
contains()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location) sourceTypeConverter, OutType(*)(inType, inType) timeConverter> requires std::is_floating_point_v<OutType> or std::is_integral_v< OutType > bool timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::contains (const LocationType & loc) const
References timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::contains().
Referenced by timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::contains().
end()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> decltype(auto) timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::end () const inline
operator[]()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> auto & timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::operator[] (const LocationType & loc) inline
Reset()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location) sourceTypeConverter, OutType(*)(inType, inType) timeConverter> requires std::is_floating_point_v<OutType> or std::is_integral_v< OutType > void timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::Reset ()
Resets timers and converted double values
ResetTimer()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location) sourceTypeConverter, OutType(*)(inType, inType) timeConverter> requires std::is_floating_point_v<OutType> or std::is_integral_v< OutType > void timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::ResetTimer (const LocationType & location)
resets timer value for one timer
Tak()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location) sourceTypeConverter, OutType(*)(inType, inType) timeConverter> requires std::is_floating_point_v<OutType> or std::is_integral_v< OutType > void timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::Tak (const std::source_location & location = std::source_location::current())
Finishes timing for specified section and calculation double value for time
Parameters
location
Tik()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location) sourceTypeConverter, OutType(*)(inType, inType) timeConverter> requires std::is_floating_point_v<OutType> or std::is_integral_v< OutType > void timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::Tik (const std::source_location & location = std::source_location::current())
This function starts new calculation section
Parameters
location source location of call
Attention
You must mirror every Tik like call with Tak
TikLoc()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> LocationType timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::TikLoc (const std::source_location & location = std::source_location::current()) inline
This function returns it's source location to chain several compute sections into one. Code example:
auto source =clk.TikLoc() //get recorded location
some_func();
clk.Tak();        //record function time
someOtherFunc();  //won't record
clk.Tik(source);   //continue recording for second function
some_func2();
clk.Tak();    //record function time
Parameters
location
Returns
source location
TikPair()
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> std::pair< std::source_location, LocationType > timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::TikPair (const std::source_location & location = std::source_location::current()) inline
Parameters
location
Returns
pair of std::source_location, location_type
Friends And Related Symbol Documentation
operator<<
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> std::ostream & operator<< (std::ostream & out, const ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter > & ts) friend
Member Data Documentation
s_mutex_
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> std::mutex timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::s_mutex_ inline static private
start_ing_timers_
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> std::map<LocationType, inType, LocationComparator> timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::start_ing_timers_ private
timers_
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> std::map<LocationType, timeStore, LocationComparator> timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::timers_ private
to_tak_
template<typename OutType , typename inType , inType(*)() timeGetter, LocationType(*)(std::source_location location) sourceTypeConverter, OutType(*)(inType curr, inType prev) timeConverter> std::stack<LocationType> timing::ClockArray< OutType, inType, timeGetter, sourceTypeConverter, timeConverter >::to_tak_ private
The documentation for this class was generated from the following file:
utilLib/include/parallelUtils/ClockArray.h