Distributed math architecture: DatabaseTestEnvironment Class Reference
DatabaseTestEnvironment Class Reference
Public Member Functions
void SetUp () override
void TearDown () override
Private Attributes
ConnPtr conn_ptr_
myConnString conn_string_
Member Function Documentation
SetUp()
void DatabaseTestEnvironment::SetUp () inline override
References conn_string_, db_common::CreateDatabase(), db_common::FillDatabase(), and g_serviceParams.
TearDown()
void DatabaseTestEnvironment::TearDown () inline override
References conn_string_, and db_common::DropDatabase().
Member Data Documentation
conn_ptr_
ConnPtr DatabaseTestEnvironment::conn_ptr_ private
conn_string_
myConnString DatabaseTestEnvironment::conn_string_ private
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
computationalLib/test/interegated/DbServiceTest.cpp