Distributed math architecture: amqp_common::RabbitMQRestService Class Reference
amqp_common::RabbitMQRestService Class Reference
This service is used to perform http requests to a RabbiMQ management interface.
Public Member Functions
RabbitMQRestService ()
void SetBaseUrl (const std::string &base_url)
Sets url's for reuqests.
void SetParams (const std::string &base_url, AuthHandler *auth_handler)
Set's url and auth provider.
RabbitMQRestService (const std::string &base_url, AuthHandler *auth_handler)
Same as the default constructor but set's the provided parameters.
RabbitMQRestService (const RabbitMQRestService &other)=delete
RabbitMQRestService & operator= (const RabbitMQRestService &other)=delete
~RabbitMQRestService ()
Clean up curl.
Json::Value Whoami ()
Requests user information from a RabbitMQ.
bool CreateQueue (const std::string &vhost, const network_types::queue &queue, const Json::Value &arguments)
Creates queue with specified params.
bool DeleteQueue (const std::string &vhost, const std::string &queue_name)
Remove queue.
bool CreateExchange (const std::string &vhost, const exchange &exchange, const Json::Value &arguments)
Creates exchange with specified params.
bool DeleteExchange (const std::string &vhost, const std::string &exchange_name)
Remove exchange.
Json::Value GetQueueStats (const std::string &vhost, const std::string &queue_name)
Retrieves Json::Value from queue/stats.
bool PublishMessage (const std::string &vhost, const std::string &exhange_name, const message &message)
Publishes message to the specified exchange and routing key.
size_t GetMessageCount (const std::string &vhost, const std::string &queue_name)
Retrieves number of messages for the selected queue.
bool GlobalParam (const global_param &param, const HttpMethod &type)
Uses global-parameters api to interact with them.
std::vector< global_param > ListGlobalParams ()
Lists all global params from RabbimMQ.
std::vector< std::string > ListQueues (const std::string &vhost)
Lists all queues.
std::vector< connection > ListConnections ()
retrieve all connection
std::vector< channel > ListChannels ()
retrieve all channels
bool BindQueueToExchange (const std::string &vhost, const std::string &queue_name, const std::string &exchange_name, const std::string &routing_key)
Binds queue to exchange.
bool UnbindQueueFromExchange (const std::string &vhost, const std::string &queue_name, const std::string &exchange_name, const std::string &routing_key)
bool CreateUser (const std::string &user, const std::string &pass)
Creates new auth user data.
bool DeleteUser (const std::string &user)
Deletes user data.
std::vector< rabbitMQUser > ListUsers (const std::string &vhost)
List all users with their roles and tags.
std::vector< queueBinding > GetQueueBindings (const std::string &vhost, const std::string &queue)
Lists all queue bindings for the specified queue.
std::vector< exchange > GetExchanges (const std::string &vhost)
Retrieves list of exhnages.
Private Member Functions
HttpResult PerformRequest (const std::string &path, const std::string &method, const std::string &data="")
Wrapper to perform curl request.
HttpResult PerformRequest (const std::string &path, const HttpMethod &method, const std::string &data="")
Static Private Member Functions
static Json::Value ParseJson (const std::string &json_str)
Private Attributes
std::string base_url_
url to perform request
AuthHandler * auth_ptr_
Detailed Description
This service is used to perform http requests to a RabbiMQ management interface.
Since this class initializes curl only one may exist per programm. This class uses libcurl to perform requests. Most of the methods use RabbitMQRestService::PerformRequest() to get the results
Constructor & Destructor Documentation
RabbitMQRestService() [1/3]
amqp_common::RabbitMQRestService::RabbitMQRestService ()
RabbitMQRestService() [2/3]
amqp_common::RabbitMQRestService::RabbitMQRestService (const std::string & base_url, AuthHandler * auth_handler)
Same as the default constructor but set's the provided parameters.
Parameters
base_url
auth_handler
See also
RabbitMQRestService::RabbitMQRestService()
RabbitMQRestService() [3/3]
amqp_common::RabbitMQRestService::RabbitMQRestService (const RabbitMQRestService & other) delete
~RabbitMQRestService()
amqp_common::RabbitMQRestService::~RabbitMQRestService ()
Clean up curl.
Member Function Documentation
BindQueueToExchange()
bool amqp_common::RabbitMQRestService::BindQueueToExchange (const std::string & vhost, const std::string & queue_name, const std::string & exchange_name, const std::string & routing_key)
Binds queue to exchange.
Parameters
vhost
queue_name
exchange_name
routing_key
Returns
true - if succeeds
References PerformRequest().
Referenced by main_services::MainNodeService::ConnectNode().
CreateExchange()
bool amqp_common::RabbitMQRestService::CreateExchange (const std::string & vhost, const exchange & exchange, const Json::Value & arguments)
Creates exchange with specified params.
Parameters
vhost
exchange
arguments - additional arguments to be added in body["arguments"]
Returns
true - if succeeds
References network_types::exchange::name, PerformRequest(), and network_types::exchange::ToJson().
Referenced by main_services::MainNodeService::Connect().
CreateQueue()
bool amqp_common::RabbitMQRestService::CreateQueue (const std::string & vhost, const network_types::queue & queue, const Json::Value & arguments)
Creates queue with specified params.
Parameters
vhost
queue
arguments - additional arguments to be added in body["arguments"]
Returns
true - if succeeds
References network_types::queue::name, PerformRequest(), and network_types::queue::ToJson().
Referenced by main_services::MainNodeService::ConnectNode().
CreateUser()
bool amqp_common::RabbitMQRestService::CreateUser (const std::string & user, const std::string & pass)
Creates new auth user data.
Parameters
user
pass
Returns
true - if succeeds
References PerformRequest().
DeleteExchange()
bool amqp_common::RabbitMQRestService::DeleteExchange (const std::string & vhost, const std::string & exchange_name)
Remove exchange.
Parameters
vhost
exchange_name
Returns
true - if succeeds
References PerformRequest().
DeleteQueue()
bool amqp_common::RabbitMQRestService::DeleteQueue (const std::string & vhost, const std::string & queue_name)
Remove queue.
Parameters
vhost
queue_name
Returns
true - if succeeds
References PerformRequest().
DeleteUser()
bool amqp_common::RabbitMQRestService::DeleteUser (const std::string & user)
Deletes user data.
Parameters
user
Returns
true - if succeeds
References PerformRequest().
GetExchanges()
std::vector< exchange > amqp_common::RabbitMQRestService::GetExchanges (const std::string & vhost)
Retrieves list of exhnages.
Parameters
vhost
Returns
std::vector<exchange>
References ParseJson(), and PerformRequest().
Referenced by main_services::MainNodeService::Connect().
GetMessageCount()
size_t amqp_common::RabbitMQRestService::GetMessageCount (const std::string & vhost, const std::string & queue_name)
Retrieves number of messages for the selected queue.
Parameters
vhost
queue_name
Returns
number of messages
References ParseJson(), and PerformRequest().
GetQueueBindings()
std::vector< queueBinding > amqp_common::RabbitMQRestService::GetQueueBindings (const std::string & vhost, const std::string & queue)
Lists all queue bindings for the specified queue.
Parameters
vhost
queue
Returns
std::vector<queueBinding>
References ParseJson(), and PerformRequest().
GetQueueStats()
Json::Value amqp_common::RabbitMQRestService::GetQueueStats (const std::string & vhost, const std::string & queue_name)
Retrieves Json::Value from queue/stats.
Parameters
vhost
queue_name
References ParseJson(), and PerformRequest().
GlobalParam()
bool amqp_common::RabbitMQRestService::GlobalParam (const global_param & param, const HttpMethod & type)
Uses global-parameters api to interact with them.
Parameters
param
type
Returns
status
References network_types::global_param::name, PerformRequest(), and network_types::global_param::ToJson().
ListChannels()
std::vector< channel > amqp_common::RabbitMQRestService::ListChannels ()
retrieve all channels
Returns
std::vector of channel
References ParseJson(), and PerformRequest().
ListConnections()
std::vector< connection > amqp_common::RabbitMQRestService::ListConnections ()
retrieve all connection
Returns
std::vector of connection
References ParseJson(), and PerformRequest().
ListGlobalParams()
std::vector< global_param > amqp_common::RabbitMQRestService::ListGlobalParams ()
Lists all global params from RabbimMQ.
Returns
std::vector of global parameters
References ParseJson(), and PerformRequest().
ListQueues()
std::vector< std::string > amqp_common::RabbitMQRestService::ListQueues (const std::string & vhost)
Lists all queues.
Parameters
vhost
Returns
std::vector of queue names
References ParseJson(), and PerformRequest().
Referenced by main_services::MainNodeService::ConnectNode().
ListUsers()
std::vector< rabbitMQUser > amqp_common::RabbitMQRestService::ListUsers (const std::string & vhost)
List all users with their roles and tags.
Parameters
vhost
Returns
std::vector<rabbitMQUser>
References ParseJson(), and PerformRequest().
operator=()
RabbitMQRestService & amqp_common::RabbitMQRestService::operator= (const RabbitMQRestService & other) delete
ParseJson()
Json::Value amqp_common::RabbitMQRestService::ParseJson (const std::string & json_str) static private
Referenced by GetExchanges(), GetMessageCount(), GetQueueBindings(), GetQueueStats(), ListChannels(), ListConnections(), ListGlobalParams(), ListQueues(), ListUsers(), PublishMessage(), and Whoami().
PerformRequest() [1/2]
HttpResult amqp_common::RabbitMQRestService::PerformRequest (const std::string & path, const HttpMethod & method, const std::string & data = "") private
References PerformRequest(), and network_types::ToString().
PerformRequest() [2/2]
HttpResult amqp_common::RabbitMQRestService::PerformRequest (const std::string & path, const std::string & method, const std::string & data = "") private
Wrapper to perform curl request.
Wraps around rest_utils::PerformCurlRequest() Thrown anything this function throws.
Parameters
path
method
data
Returns
HttpResult
References auth_ptr_, base_url_, and rest_utils::PerformCurlRequest().
Referenced by BindQueueToExchange(), CreateExchange(), CreateQueue(), CreateUser(), DeleteExchange(), DeleteQueue(), DeleteUser(), GetExchanges(), GetMessageCount(), GetQueueBindings(), GetQueueStats(), GlobalParam(), ListChannels(), ListConnections(), ListGlobalParams(), ListQueues(), ListUsers(), PerformRequest(), PublishMessage(), UnbindQueueFromExchange(), and Whoami().
PublishMessage()
bool amqp_common::RabbitMQRestService::PublishMessage (const std::string & vhost, const std::string & exhange_name, const message & message)
Publishes message to the specified exchange and routing key.
Parameters
vhost
exhange_name
message
Returns
is_routed
References ParseJson(), PerformRequest(), and network_types::message::ToJson().
SetBaseUrl()
void amqp_common::RabbitMQRestService::SetBaseUrl (const std::string & base_url)
Sets url's for reuqests.
Parameters
base_url
References base_url_.
SetParams()
void amqp_common::RabbitMQRestService::SetParams (const std::string & base_url, AuthHandler * auth_handler)
Set's url and auth provider.
Parameters
base_url
auth_handler
References auth_ptr_, and base_url_.
Referenced by main_services::MainNodeService::Connect().
UnbindQueueFromExchange()
bool amqp_common::RabbitMQRestService::UnbindQueueFromExchange (const std::string & vhost, const std::string & queue_name, const std::string & exchange_name, const std::string & routing_key)
Unbinds queue from exchange
Parameters
vhost
queue_name
exchange_name
routing_key
Returns
true - if succeeds
References PerformRequest().
Whoami()
Json::Value amqp_common::RabbitMQRestService::Whoami ()
Requests user information from a RabbitMQ.
Returns
Json::Value from RabbitMQRestService::PerformRequest
References ParseJson(), and PerformRequest().
Member Data Documentation
auth_ptr_
AuthHandler* amqp_common::RabbitMQRestService::auth_ptr_ private
Referenced by PerformRequest(), and SetParams().
base_url_
std::string amqp_common::RabbitMQRestService::base_url_ private
url to perform request
Referenced by PerformRequest(), SetBaseUrl(), and SetParams().
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/amqpRestService.h
computationalLib/lib/network_shared/amqpRestService.cpp