Distributed math architecture: amqp_common::AMQPPublisherService Class Reference
amqp_common::AMQPPublisherService Class Reference
Service that allow to Publish messages to multiple queues.
Public Member Functions
AMQPPublisherService ()
void SetParameters (const std::string &connection_string, const std::vector< std::string > &queues, const std::string &exchange="testexch")
AMQPPublisherService (const std::string &connection_string, const std::vector< std::string > &queues={}, const std::string &exchange="testexch")
const std::string & GetDefaultExchange () const
void RemoveQueue (size_t i)
delted i's queue
void AddQueue (const std::string &queue, bool create)
void Publish (EnvelopePtr message, size_t i)
publishe message to i's queue
void Publish (EnvelopePtr message, const std::string qname)
publishe message to i's queue
~AMQPPublisherService ()
Calls Disconnect and frees used memory with smart pointers.
Public Member Functions inherited from amqp_common::AMQPService
AMQPService ()
AMQPService (const std::string &connection_string)
void SetParameters (const std::string &connection_string)
Sets most connection parameter.
bool IsConnected () const
const std::string & GetCString () const
void Connect ()
Starts event Loop for service.
void Disconnect ()
Ends connection and channel to rabbitMQ This is the variant of soft disconnect.
~AMQPService ()
Calls Disconnect and frees used memory with smart pointers.
Private Member Functions
void Reconnect () override
std::string ServiceName () override
Private Attributes
std::vector< std::string > queues_
list of used queues ///
std::thread service_thread_
thread to run boost service
std::string default_exchange_
default exchange to bind queues
Additional Inherited Members
Protected Types inherited from amqp_common::AMQPService
using GuardType = std::scoped_lock< std::mutex >
Protected Attributes inherited from amqp_common::AMQPService
boost::asio::io_service service_
service used for async event loop
boost::asio::io_service::work * work_
work object to handle loop work
MyHandler * handler_
custom connection handler
AMQP::TcpConnection * connection_
AMQP::TcpConnection pointer.
AMQP::TcpChannel * channel_
AMQP::TcpChannel pointer.
std::string c_string_
connection string
std::thread service_thread_
thread to run boost service
std::promise< std::string > connection_promise_
bool promise_set_
Static Protected Attributes inherited from amqp_common::AMQPService
static std::mutex s_mutex_
Detailed Description
Service that allow to Publish messages to multiple queues.
Constructor & Destructor Documentation
AMQPPublisherService() [1/2]
amqp_common::AMQPPublisherService::AMQPPublisherService ()
AMQPPublisherService() [2/2]
amqp_common::AMQPPublisherService::AMQPPublisherService (const std::string & connection_string, const std::vector< std::string > & queues = {}, const std::string & exchange = "testexch")
Will declare all queues in provide array
Parameters
connection_string
queues
exchange
~AMQPPublisherService()
amqp_common::AMQPPublisherService::~AMQPPublisherService ()
Calls Disconnect and frees used memory with smart pointers.
See also
AMQPPublisherService Disconnect
References amqp_common::AMQPService::Disconnect(), and queues_.
Member Function Documentation
AddQueue()
void amqp_common::AMQPPublisherService::AddQueue (const std::string & queue, bool create)
Adds new queue
Parameters
queue
create
References amqp_common::AMQPService::channel_, amqp_common::DeclareQueue(), default_exchange_, and queues_.
GetDefaultExchange()
const std::string & amqp_common::AMQPPublisherService::GetDefaultExchange () const
References default_exchange_.
Referenced by main_services::MainNodeService::Connect(), and main_services::MainNodeService::ConnectNode().
Publish() [1/2]
void amqp_common::AMQPPublisherService::Publish (EnvelopePtr message, const std::string qname)
publishe message to i's queue
Parameters
message
qname
References amqp_common::AMQPService::channel_, and default_exchange_.
Publish() [2/2]
void amqp_common::AMQPPublisherService::Publish (EnvelopePtr message, size_t i)
publishe message to i's queue
Parameters
message
i
Exceptions
shared::outOfRange
References amqp_common::AMQPService::channel_, default_exchange_, and queues_.
Referenced by main_services::MainNodeService::PublishMessage().
Reconnect()
void amqp_common::AMQPPublisherService::Reconnect () override private virtual
Implements amqp_common::AMQPService.
References amqp_common::AMQPService::c_string_, amqp_common::AMQPService::channel_, amqp_common::AMQPService::connection_, amqp_common::AMQPService::connection_promise_, amqp_common::AMQPService::handler_, amqp_common::AMQPService::IsConnected(), amqp_common::AMQPService::promise_set_, amqp_common::AMQPService::s_mutex_, and VARIABLE_NAME.
RemoveQueue()
void amqp_common::AMQPPublisherService::RemoveQueue (size_t i)
delted i's queue
Parameters
i
Exceptions
shared::outOfRange
References queues_.
ServiceName()
std::string amqp_common::AMQPPublisherService::ServiceName () override private virtual
Implements amqp_common::AMQPService.
SetParameters()
void amqp_common::AMQPPublisherService::SetParameters (const std::string & connection_string, const std::vector< std::string > & queues, const std::string & exchange = "testexch")
References amqp_common::AMQPService::c_string_, default_exchange_, and queues_.
Referenced by main_services::MainNodeService::Connect().
Member Data Documentation
default_exchange_
std::string amqp_common::AMQPPublisherService::default_exchange_ private
default exchange to bind queues
Referenced by AddQueue(), GetDefaultExchange(), Publish(), Publish(), and SetParameters().
queues_
std::vector<std::string> amqp_common::AMQPPublisherService::queues_ private
list of used queues ///
Todo:
remove
Referenced by AddQueue(), Publish(), RemoveQueue(), SetParameters(), and ~AMQPPublisherService().
service_thread_
std::thread amqp_common::AMQPPublisherService::service_thread_ private
thread to run boost service
The documentation for this class was generated from the following files:
computationalLib/include/network_shared/AMQPPublisherService.h
computationalLib/lib/network_shared/AMQPPublisherService.cpp