Distributed math architecture: comp_services::ComputationNodeService Class Reference
comp_services::ComputationNodeService Class Reference
#include <CompNodeService.h>
Public Member Functions
ComputationNodeService ()
Json::Value GetStatus ()
Json::Value Connect (const HttpRequestPtr &req)
Json::Value Disconnect ()
void RunBench ()
Private Member Functions
bool CheckConnection ()
bool Computed ()
Private Attributes
amqp_common::AMQPConsumerService consumer_service_
BenchResVec bench_res_
std::jthread computation_thread_
std::atomic< bool > characteristic_computed_
BenchmarkRunner * benchmark_runner_
Constructor & Destructor Documentation
ComputationNodeService()
comp_services::ComputationNodeService::ComputationNodeService ()
References benchmark_runner_, shared::iter_count, shared::ns, and RunBench().
Member Function Documentation
CheckConnection()
bool comp_services::ComputationNodeService::CheckConnection () private
References consumer_service_, and amqp_common::AMQPService::IsConnected().
Computed()
bool comp_services::ComputationNodeService::Computed () inline private
Referenced by GetStatus().
Connect()
Json::Value comp_services::ComputationNodeService::Connect (const HttpRequestPtr & req)
References bench_res_, amqp_common::AMQPService::Connect(), consumer_service_, print_utils::ContinuousToJson(), amqp_common::AMQPService::GetCString(), network_types::AMQPSQLCStr::GetVerboseName(), amqp_common::AMQPService::IsConnected(), comp_services::n_message_callback, amqp_common::AMQPConsumerService::SetMessageCallback(), and amqp_common::AMQPConsumerService::SetParameters().
Referenced by rest::v1::CompNode::ConnectHandler().
Disconnect()
Json::Value comp_services::ComputationNodeService::Disconnect ()
References consumer_service_, amqp_common::AMQPService::Disconnect(), and amqp_common::AMQPService::IsConnected().
Referenced by rest::v1::CompNode::DisconnectHandler().
GetStatus()
Json::Value comp_services::ComputationNodeService::GetStatus ()
References bench_res_, Computed(), consumer_service_, print_utils::ContinuousToJson(), and amqp_common::AMQPService::IsConnected().
Referenced by rest::v1::CompNode::GetStatus().
RunBench()
void comp_services::ComputationNodeService::RunBench ()
References bench_res_, benchmark_runner_, characteristic_computed_, computation_thread_, and comp_services::BenchmarkRunner::Run().
Referenced by ComputationNodeService().
Member Data Documentation
bench_res_
BenchResVec comp_services::ComputationNodeService::bench_res_ private
Referenced by Connect(), GetStatus(), and RunBench().
benchmark_runner_
BenchmarkRunner* comp_services::ComputationNodeService::benchmark_runner_ private
Referenced by ComputationNodeService(), and RunBench().
characteristic_computed_
std::atomic<bool> comp_services::ComputationNodeService::characteristic_computed_ private
Referenced by RunBench().
computation_thread_
std::jthread comp_services::ComputationNodeService::computation_thread_ private
Referenced by RunBench().
consumer_service_
amqp_common::AMQPConsumerService comp_services::ComputationNodeService::consumer_service_ private
Referenced by CheckConnection(), Connect(), Disconnect(), and GetStatus().
The documentation for this class was generated from the following files:
computationalNode/include/service/CompNodeService.h
computationalNode/src/service/CompNodeService.cpp