Distributed math architecture: rest_utils::JsonAuthHandler Class Reference
rest_utils::JsonAuthHandler Class Reference
#include <restUtils.h>
Public Member Functions
Json::Value ToJson ()
std::pair< std::string, std::string > Retrive ()
Public Member Functions inherited from rest_utils::BasicAuthHandler
BasicAuthHandler (const std::string &user, const std::string &password, bool active=true)
BasicAuthHandler (const BasicAuthHandler &handle)=default
Public Member Functions inherited from rest_utils::AuthHandler
AuthHandler (bool active=true)
void SetActive (bool act)
void AddAuthorization (CURL *curl)
Private Member Functions
BasicAuthHandler (const std::string &user, const std::string &password, bool active=true)
BasicAuthHandler (const BasicAuthHandler &handle)=default
Additional Inherited Members
Protected Member Functions inherited from rest_utils::BasicAuthHandler
virtual void AddAuth (CURL *curl) override
Protected Attributes inherited from rest_utils::BasicAuthHandler
std::string user_
std::string password_
Protected Attributes inherited from rest_utils::AuthHandler
bool active_
Can toggle off authorization.
Member Function Documentation
BasicAuthHandler() [1/2]
rest_utils::BasicAuthHandler::BasicAuthHandler private default
BasicAuthHandler() [2/2]
rest_utils::BasicAuthHandler::BasicAuthHandler private
Retrive()
std::pair<std::string, std::string> rest_utils::JsonAuthHandler::Retrive () inline
References rest_utils::BasicAuthHandler::password_, and rest_utils::BasicAuthHandler::user_.
Referenced by main_services::MainNodeService::Connect(), and main_services::MainNodeService::ConnectNode().
ToJson()
Json::Value rest_utils::JsonAuthHandler::ToJson () inline
References rest_utils::BasicAuthHandler::password_, and rest_utils::BasicAuthHandler::user_.
Referenced by main_services::MainNodeService::ConnectNode().
The documentation for this class was generated from the following file:
computationalLib/include/network_shared/restUtils.h