Distributed math architecture: computationalLib/test/math_core/dipoleCommonTests.cpp File Reference
dipoleCommonTests.cpp File Reference
#include "../GoogleCommon.h"
#include "math_core/Dipoles.h"
#include "common/Generator.h"
#include "common/typeCasts.h"
Classes
class IsSymmetricTestSuite
class DipoleSolveMethodNevTests
Typedefs
template<typename T >
using DynEigenVec = Eigen::Vector< T, -1 >
Functions
TEST_P (IsSymmetricTestSuite, CheckGenratedMatrixes)
TEST_F (IsSymmetricTestSuite, CheckNonSymmetricMatrix)
INSTANTIATE_TEST_SUITE_P (Matrixes, IsSymmetricTestSuite, testing::Values(2, 4, 10, 100, 200, 400, 800), testing::PrintToStringParamName())
TEST (Dipoles, test_solve_result_in_zero_nev)
INSTANTIATE_TEST_SUITE_P (DipoleNevs, DipoleSolveMethodNevTests, testing::Combine(testing::Values(1, 2, 3, 4, 5, 10, 20, 40, 80, 160, 200), testing::Range(0, 10)), TupleToString< DipoleSolveMethodNevTests >)
TEST_P (DipoleSolveMethodNevTests, test_right_part_nev_solve_impl)
Variables
static FloatType aRange = 1e-6
static auto normal_gen = generators::get_normal_generator(0.0, aRange * sqrt(2))
Typedef Documentation
DynEigenVec
template<typename T > using DynEigenVec = Eigen::Vector<T, -1>
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/2]
INSTANTIATE_TEST_SUITE_P (DipoleNevs , DipoleSolveMethodNevTests , testing::Combine(testing::Values(1, 2, 3, 4, 5, 10, 20, 40, 80, 160, 200), testing::Range(0, 10)) , TupleToString< DipoleSolveMethodNevTests >)
INSTANTIATE_TEST_SUITE_P() [2/2]
INSTANTIATE_TEST_SUITE_P (Matrixes , IsSymmetricTestSuite , testing::Values(2, 4, 10, 100, 200, 400, 800) , testing::PrintToStringParamName())
TEST()
TEST (Dipoles , test_solve_result_in_zero_nev)
References dipoles::Dipoles::GetMatrixx(), dipoles::Dipoles::GetRightPart(), normal_gen, and dipoles::Dipoles::Solve().
TEST_F()
TEST_F (IsSymmetricTestSuite , CheckNonSymmetricMatrix)
References dipoles::IsSymmetric().
TEST_P() [1/2]
TEST_P (DipoleSolveMethodNevTests , test_right_part_nev_solve_impl)
References dipoles::Dipoles::GetMatrixx(), dipoles::Dipoles::GetRightPart(), normal_gen, and dipoles::Dipoles::Solve().
TEST_P() [2/2]
TEST_P (IsSymmetricTestSuite , CheckGenratedMatrixes)
References dipoles::IsSymmetric().
Variable Documentation
aRange
FloatType aRange = 1e-6 inline static
normal_gen
auto normal_gen = generators::get_normal_generator(0.0, aRange * sqrt(2)) inline static
Referenced by TEST(), and TEST_P().