Distributed math architecture: amqp_common Namespace Reference
amqp_common Namespace Reference
amqpCommon namespace
Classes
class AMQPConsumerService
Service that allow to start and end reading event Loop from specified queue.
class AMQPPublisherService
Service that allow to Publish messages to multiple queues.
class AMQPService
This class connection/disconnection semantics.
class MyHandler
Custom handler for connection events logging.
class RabbitMQRestService
This service is used to perform http requests to a RabbiMQ management interface.
Typedefs
using EnvelopePtr = std::shared_ptr< Envelope >
using WorkPtr = std::unique_ptr< boost::asio::io_service::work >
< message callback
Functions
std::string ConstructCString (const std::string &host_port, const std::string &user, const std::string &password, bool secure=false)
Constructs amqp connection string.
AMQP::Address ConstructCAddress (const std::string &host_port, const std::string &user, const std::string &password, bool secure=false)
std::optional< std::string > ExtractHost (std::string_view url)
Extract host from the Full url.
void DeclareQueue (AMQP::Channel &channel, const std::string &queue1, const std::string &exchange1)
void sendMessage (AMQP::Channel &channel, std::string_view exchange1, std::string_view routingKey, std::string_view body, bool persistent=true)
void consumeMessages (AMQP::Channel &channel, std::string_view queueName)
void DefaultMessageCallback (const AMQP::Message &message, uint64_t delivery_tag, bool redelivered)
Default message processing callback.
Detailed Description
amqpCommon namespace
Typedef Documentation
EnvelopePtr
using amqp_common::EnvelopePtr = typedef std::shared_ptr<Envelope>
WorkPtr
using amqp_common::WorkPtr = typedef std::unique_ptr<boost::asio::io_service::work>
< message callback
Function Documentation
ConstructCAddress()
AMQP::Address amqp_common::ConstructCAddress (const std::string & host_port, const std::string & user, const std::string & password, bool secure = false)
References ConstructCString().
Referenced by TEST().
ConstructCString()
std::string amqp_common::ConstructCString (const std::string & host_port, const std::string & user, const std::string & password, bool secure = false)
Constructs amqp connection string.
Parameters
host_port
user
password
secure sets with amqps protocol
Referenced by comp_services::ComputationNodeService::Connect(), main_services::MainNodeService::Connect(), ConstructCAddress(), AMQPConsumerSeviceTS::SetUp(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
consumeMessages()
void amqp_common::consumeMessages (AMQP::Channel & channel, std::string_view queueName)
Parameters
channel
queueName
DeclareQueue()
void amqp_common::DeclareQueue (AMQP::Channel & channel, const std::string & queue1, const std::string & exchange1)
Parameters
channel
queue1
exchange1
Referenced by amqp_common::AMQPPublisherService::AddQueue().
DefaultMessageCallback()
void amqp_common::DefaultMessageCallback (const AMQP::Message & message, uint64_t delivery_tag, bool redelivered)
Default message processing callback.
Parameters
message
delivery_tag
redelivered
Referenced by amqp_common::AMQPConsumerService::Reconnect().
ExtractHost()
std::optional< std::string > amqp_common::ExtractHost (std::string_view url)
Extract host from the Full url.
Parameters
url
Returns
References ExtractHost().
Referenced by ExtractHost(), AMQPConsumerSeviceTS::SetUp(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
sendMessage()
void amqp_common::sendMessage (AMQP::Channel & channel, std::string_view exchange1, std::string_view routingKey, std::string_view body, bool persistent = true)
Parameters
channel
exchange1
routingKey
body
persistent