Distributed math architecture: db_common Namespace Reference
db_common Namespace Reference
Namespace that contains database related utils.
Classes
struct Experiment
Experiment DAO.
struct Iteration
Iteration DAO.
struct Log
Log DAO.
struct myConnString
Structure to store and format connection string.
struct Node
Node DAO.
struct User
User DAO.
Typedefs
using ConnPtr = std::shared_ptr< pqxx::connection >
using TransactionT = pqxx::transaction< pqxx::isolation_level::read_committed >
using NonTransType = pqxx::nontransaction
using ResType = pqxx::result
using Subtransaction = pqxx::subtransaction
using IndexType = uint64_t
Enumerations
enum class UserRole { USER , ADMINISTRATOR }
enum class ExperimentStatus {
CREATED , QUEUED , RUNNING , SUCCEEDED ,
ERROR , ARHIVED
}
enum class IterationStatus { QUEUED , RUNNING , SUCCEEDED , ERROR }
enum class IterationType { GENERATE , SOLVE , MESH }
enum class NodeStatus { ACTIVE , BUSY , INACTIVE , ERROR }
Functions
template<typename T >
std::optional< T > GetOpt (pqxx::field &&a)
Function to retrieve optional value.
template<typename T , std::optional< T >(*)(std::string_view) func>
std::optional< T > GetFunctionOpt (pqxx::field &&a)
Function to retrieve optional value while using func to cast it to T.
template<template< typename ... > typename VecT, typename RetType >
VecT< RetType > ParseArray (const ResType &result)
Parses specified continuous struct from ResType.
std::string PaginateRequest (std::string_view initial_request, IndexType page_num, IndexType page_size)
formats request to add pagination
bool CheckConnection (const ConnPtr &conn_ptr)
Checks connection.
void Disconnect (ConnPtr &conn_ptr)
Closes connection and reset conn_ptr.
ConnPtr TryConnect (const myConnString &conn_str, const std::string service_name)
Attempt to connect to PostgrSQL with conn_str.
size_t CheckDatabaseExistence (NonTransType &non_trans, std::string_view db_name)
Checks db_name database existence.
ResType TerminateAllDbConnections (NonTransType &no_trans_exec, std::string_view db_name)
terminates all connections for the specified database
ConnPtr CreateDatabase (myConnString c_string, std::string_view db_name)
Creates database with db_name.
void DropDatabase (myConnString c_string, std::string_view db_name)
Drops specified database.
void FillDatabase (myConnString c_string, std::string_view script)
Executes the script ot inidb.
ResType ExecuteTransaction (ConnPtr &ptr, const std::function< ResType(TransactionT &)> &func, std::string_view service_name, const myConnString &conn_str)
Executes function in the form of transaction.
ResType ExecuteSubTransaction (TransactionT &txn, const std::function< ResType(Subtransaction &)> &func, std::string_view sub_name="")
Executes function inside subtransaction of txn.
Variables
static const std::vector< EnumMapping< UserRole > > kUserRoleMappings
static const auto kStrToUserRole
const auto kUserRoleToStr
static const std::vector< EnumMapping< ExperimentStatus > > kExpStatusMappings
static const auto kStrToExpStatus
const auto kExpStatusToStr
static const std::vector< EnumMapping< IterationStatus > > kIterStatusMappings
static const auto kStrToIterStatus
const auto kIterStatusToStr
static const std::vector< EnumMapping< IterationType > > kIterTypeMappings
static const auto kStrToIterType
const auto kIterTypeToStr
static const std::vector< EnumMapping< NodeStatus > > kNodeStMappings
static const auto kStrToNodeSt
const auto kNodeStToStr
static const char *const SampleTempDb = "template1"
Detailed Description
Namespace that contains database related utils.
Typedef Documentation
ConnPtr
using db_common::ConnPtr = typedef std::shared_ptr<pqxx::connection>
IndexType
using db_common::IndexType = typedef uint64_t
NonTransType
using db_common::NonTransType = typedef pqxx::nontransaction
ResType
using db_common::ResType = typedef pqxx::result
Subtransaction
using db_common::Subtransaction = typedef pqxx::subtransaction
TransactionT
using db_common::TransactionT = typedef pqxx::transaction<pqxx::isolation_level::read_committed>
Enumeration Type Documentation
ExperimentStatus
enum class db_common::ExperimentStatus strong
Enumerator
CREATED
created by user
QUEUED
waiting to be executed
RUNNING
currently executing
SUCCEEDED
all iteration were computed
ERROR
error occurred during execution
ARHIVED
experiment data is unloaded
IterationStatus
enum class db_common::IterationStatus strong
Enumerator
QUEUED
waiting to be executed
RUNNING
currently executing
SUCCEEDED
all iteration were computed
ERROR
error occurred during execution
IterationType
enum class db_common::IterationType strong
Enumerator
GENERATE
generate coordinates
SOLVE
solve system of equations
MESH
generate mesh
NodeStatus
enum class db_common::NodeStatus strong
Enumerator
ACTIVE
node is processing messages
BUSY
node is busy
INACTIVE
node is not listening to queue
ERROR
error occurred in node
UserRole
enum class db_common::UserRole strong
Enumerator
USER
default user role
ADMINISTRATOR
administrator user role
Function Documentation
CheckConnection()
bool db_common::CheckConnection (const ConnPtr & conn_ptr)
Checks connection.
Parameters
conn_ptr
Returns
connection status
References CheckConnection().
Referenced by CheckConnection(), ExecuteTransaction(), db_service::DbService::Reconnect(), and TryConnect().
CheckDatabaseExistence()
size_t db_common::CheckDatabaseExistence (NonTransType & non_trans, std::string_view db_name)
Checks db_name database existence.
Parameters
non_trans
db_name
Returns
Number of databases with name db_name
References CheckDatabaseExistence().
Referenced by CheckDatabaseExistence(), CreateDatabase(), and DropDatabase().
CreateDatabase()
ConnPtr db_common::CreateDatabase (myConnString c_string, std::string_view db_name)
Creates database with db_name.
Parameters
db_name
c_string
Returns
connection string pointer for the created database
References CheckDatabaseExistence(), CreateDatabase(), Disconnect(), db_common::myConnString::GetDbname(), db_common::myConnString::GetUser(), db_common::myConnString::SetDbname(), and TryConnect().
Referenced by CreateDatabase(), and DatabaseTestEnvironment::SetUp().
Disconnect()
void db_common::Disconnect (ConnPtr & conn_ptr)
Closes connection and reset conn_ptr.
Parameters
conn_ptr
References Disconnect().
Referenced by CreateDatabase(), db_service::DbService::Disconnect(), Disconnect(), and DropDatabase().
DropDatabase()
void db_common::DropDatabase (myConnString c_string, std::string_view db_name)
Drops specified database.
Will call TerminateAllDbConnections to end all other connections
Parameters
db_name
c_string
References CheckDatabaseExistence(), Disconnect(), DropDatabase(), db_common::myConnString::GetDbname(), db_common::myConnString::SetDbname(), TerminateAllDbConnections(), and TryConnect().
Referenced by DropDatabase(), and DatabaseTestEnvironment::TearDown().
ExecuteSubTransaction()
ResType db_common::ExecuteSubTransaction (TransactionT & txn, const std::function< ResType(Subtransaction &)> & func, std::string_view sub_name = "")
Executes function inside subtransaction of txn.
Parameters
txn
func
sub_name - name for subtransaction
Exceptions
SQL_ERROR if any sql syntax or semantics issue arises
MyException if any other error happens
References ExecuteSubTransaction(), and shared::info.
Referenced by ExecuteSubTransaction(), and db_service::DbService::InnerLog().
ExecuteTransaction()
ResType db_common::ExecuteTransaction (ConnPtr & ptr, const std::function< ResType(TransactionT &)> & func, std::string_view service_name, const myConnString & conn_str)
Executes function in the form of transaction.
Creates new transaction to execute provided function
Parameters
ptr
func
service_name
conn_str
Exceptions
SQL_ERROR if any sql syntax or semantics issue arises
MyException if any other error happens
References CheckConnection(), ExecuteTransaction(), db_common::myConnString::GetVerboseName(), and shared::info.
Referenced by ExecuteTransaction(), FillDatabase(), db_service::DbService::GetIteration(), db_service::DbService::GetNode(), db_service::DbService::ListIterations(), db_service::DbService::ListLogs(), db_service::DbService::ListNodes(), db_service::DbService::Log(), db_service::DbService::RegisterNode(), db_service::DbService::UnregisterNode(), and db_service::DbService::UpdateNodeStatus().
FillDatabase()
void db_common::FillDatabase (myConnString c_string, std::string_view script)
Executes the script ot inidb.
Parameters
c_string
script
References ExecuteTransaction(), FillDatabase(), and TryConnect().
Referenced by FillDatabase(), and DatabaseTestEnvironment::SetUp().
GetFunctionOpt()
template<typename T , std::optional< T >(*)(std::string_view) func> std::optional< T > db_common::GetFunctionOpt (pqxx::field && a) inline
Function to retrieve optional value while using func to cast it to T.
Template Parameters
T
func
Parameters
a
Returns
T optinal
GetOpt()
template<typename T > std::optional< T > db_common::GetOpt (pqxx::field && a) inline
Function to retrieve optional value.
Template Parameters
T
Parameters
a
Returns
T optional
PaginateRequest()
std::string db_common::PaginateRequest (std::string_view initial_request, IndexType page_num, IndexType page_size)
formats request to add pagination
Parameters
initial_request
page_num
page_size
Returns
References PaginateRequest().
Referenced by db_service::DbService::ListExperiments(), db_service::DbService::ListIterations(), db_service::DbService::ListLogs(), db_service::DbService::ListNodes(), db_service::DbService::ListUsers(), and PaginateRequest().
ParseArray()
template<template< typename ... > typename VecT, typename RetType > VecT< RetType > db_common::ParseArray (const ResType & result)
Parses specified continuous struct from ResType.
Note
Requires RetType to be constructible from pqxx::field
Template Parameters
VecT
RetType
Parameters
result
Returns
VecT<RetType>
TerminateAllDbConnections()
ResType db_common::TerminateAllDbConnections (NonTransType & no_trans_exec, std::string_view db_name)
terminates all connections for the specified database
Parameters
no_trans_exec
db_name
Returns
ResType for the specified terminate requests
References TerminateAllDbConnections().
Referenced by DropDatabase(), and TerminateAllDbConnections().
TryConnect()
ConnPtr db_common::TryConnect (const myConnString & conn_str, const std::string service_name)
Attempt to connect to PostgrSQL with conn_str.
Parameters
conn_str
service_name
Returns
connection pointer
Exceptions
Broken_Connection - if connection cannot be established
References CheckConnection(), db_common::myConnString::CStr(), db_common::myConnString::GetVerboseName(), and TryConnect().
Referenced by CreateDatabase(), DropDatabase(), FillDatabase(), db_service::DbService::Reconnect(), and TryConnect().
Variable Documentation
kExpStatusMappings
const std::vector<EnumMapping<ExperimentStatus> > db_common::kExpStatusMappings static
Initial value:
= {
    {ExperimentStatus::CREATED, "created"},
    {ExperimentStatus::QUEUED, "queued"},
    {ExperimentStatus::RUNNING, "running"},
    {ExperimentStatus::SUCCEEDED, "succeeded"},
    {ExperimentStatus::ERROR, "error"},
    {ExperimentStatus::ARHIVED, "archived"},
}
kExpStatusToStr
const auto db_common::kExpStatusToStr
Initial value:
=
    CreateEnumToStrMap(kExpStatusMappings)
kIterStatusMappings
const std::vector<EnumMapping<IterationStatus> > db_common::kIterStatusMappings static
Initial value:
= {
    {IterationStatus::QUEUED, "queued"},
    {IterationStatus::RUNNING, "running"},
    {IterationStatus::SUCCEEDED, "succeeded"},
    {IterationStatus::ERROR, "error"},
}
kIterStatusToStr
const auto db_common::kIterStatusToStr
Initial value:
=
    CreateEnumToStrMap(kIterStatusMappings)
kIterTypeMappings
const std::vector<EnumMapping<IterationType> > db_common::kIterTypeMappings static
Initial value:
= {
    {IterationType::GENERATE, "generate"},
    {IterationType::SOLVE, "solve"},
    {IterationType::MESH, "mesh"},
}
kIterTypeToStr
const auto db_common::kIterTypeToStr
Initial value:
=
    CreateEnumToStrMap(kIterTypeMappings)
Referenced by db_service::DbService::CreateIteration().
kNodeStMappings
const std::vector<EnumMapping<NodeStatus> > db_common::kNodeStMappings static
Initial value:
= {
    {NodeStatus::ACTIVE, "active"},
    {NodeStatus::BUSY, "busy"},
    {NodeStatus::INACTIVE, "inactive"},
    {NodeStatus::ERROR, "error"},
}
kNodeStToStr
const auto db_common::kNodeStToStr
Initial value:
=
    CreateEnumToStrMap(kNodeStMappings)
kStrToExpStatus
const auto db_common::kStrToExpStatus static
Initial value:
=
    CreateStrToEnumMap(kExpStatusMappings)
Referenced by db_common::Experiment::Experiment().
kStrToIterStatus
const auto db_common::kStrToIterStatus static
Initial value:
=
    CreateStrToEnumMap(kIterStatusMappings)
Referenced by db_common::Iteration::Iteration().
kStrToIterType
const auto db_common::kStrToIterType static
Initial value:
=
    CreateStrToEnumMap(kIterTypeMappings)
Referenced by db_common::Iteration::Iteration().
kStrToNodeSt
const auto db_common::kStrToNodeSt static
Initial value:
=
    CreateStrToEnumMap(kNodeStMappings)
Referenced by db_common::Node::Node().
kStrToUserRole
const auto db_common::kStrToUserRole static
Initial value:
=
    CreateStrToEnumMap(kUserRoleMappings)
Referenced by db_common::User::User().
kUserRoleMappings
const std::vector<EnumMapping<UserRole> > db_common::kUserRoleMappings static
Initial value:
= {
    {UserRole::USER, "user"},
    {UserRole::ADMINISTRATOR, "admin"},
}
kUserRoleToStr
const auto db_common::kUserRoleToStr
Initial value:
=
    CreateEnumToStrMap(kUserRoleMappings)
Referenced by db_service::DbService::CreateUser().
SampleTempDb
const char* const db_common::SampleTempDb = "template1" static