Distributed math architecture: generators Namespace Reference
generators Namespace Reference
namespace for the utilities related to data generation
Classes
struct generator
Interface for distribution functions handling.
Typedefs
using DistributionFunctor = std::function< FloatType()>
Enumerations
enum class DistributionType : size_t { NORMAL , UNIFORM , EXPONENTIAL , LAST }
Functions
DistributionFunctor get_normal_generator (FloatType mean, FloatType dev)
Shorthand generator getter for normal distribution.
DistributionFunctor get_uniform_generator (FloatType a, FloatType b)
Shorthand generator getter for uniform real distribution.
DistributionFunctor get_exponential_generator (FloatType lambda)
Shorthand generator getter for exponential distribution.
DistributionFunctor ParseFunc (const DistributionType &distribution_type, const std::unordered_map< std::string, JsonVariant > &args)
DistributionFunctor ParseFunc (const std::string &type, const std::unordered_map< std::string, JsonVariant > &args)
Variables
thread_local generator< std::mt19937 > gen_mt19937 = generator<std::mt19937>()
Thread local generator object.
static std::unordered_map< std::string, DistributionType > stringToDistributionType
static constexpr size_t distribution_size
static std::array< std::string, distribution_size > distros
Detailed Description
namespace for the utilities related to data generation
Typedef Documentation
DistributionFunctor
using generators::DistributionFunctor = typedef std::function<FloatType()>
Enumeration Type Documentation
DistributionType
enum generators::DistributionType : size_t strong
Enumerator
NORMAL
UNIFORM
EXPONENTIAL
LAST
Function Documentation
get_exponential_generator()
DistributionFunctor generators::get_exponential_generator (FloatType lambda) inline
Shorthand generator getter for exponential distribution.
Parameters
lambda
Returns
References gen_mt19937.
Referenced by ParseFunc().
get_normal_generator()
DistributionFunctor generators::get_normal_generator (FloatType mean, FloatType dev) inline
Shorthand generator getter for normal distribution.
Parameters
mean
dev
References gen_mt19937.
Referenced by ParseFunc().
get_uniform_generator()
DistributionFunctor generators::get_uniform_generator (FloatType a, FloatType b) inline
Shorthand generator getter for uniform real distribution.
Parameters
a
b
References gen_mt19937.
Referenced by ParseFunc().
ParseFunc() [1/2]
DistributionFunctor generators::ParseFunc (const DistributionType & distribution_type, const std::unordered_map< std::string, JsonVariant > & args)
Parameters
distribution_type
args
Returns
DistributionFunctor
References EXPONENTIAL, get_exponential_generator(), get_normal_generator(), get_uniform_generator(), NORMAL, and UNIFORM.
Referenced by ParseFunc().
ParseFunc() [2/2]
DistributionFunctor generators::ParseFunc (const std::string & type, const std::unordered_map< std::string, JsonVariant > & args)
References ParseFunc(), and stringToDistributionType.
Variable Documentation
distribution_size
constexpr size_t generators::distribution_size static constexpr
Initial value:
= static_cast<size_t>(DistributionType::LAST) -
    static_cast<size_t>(DistributionType::NORMAL)
distros
std::array<std::string, distribution_size> generators::distros inline static
Initial value:
{
        "normal",
        "uniform",
        "exponential"
    }
gen_mt19937
thread_local generator< std::mt19937 > generators::gen_mt19937 = generator<std::mt19937>()
Thread local generator object.
Referenced by get_exponential_generator(), get_normal_generator(), and get_uniform_generator().
stringToDistributionType
std::unordered_map<std::string, DistributionType> generators::stringToDistributionType inline static
Initial value:
{
        {"normal", DistributionType::NORMAL},
        {"uniform", DistributionType::UNIFORM},
        {"exponential", DistributionType::EXPONENTIAL}
    }
Referenced by ParseFunc().