Distributed math architecture: rest_utils Namespace Reference
rest_utils Namespace Reference
Namespace for httpr rest utilities.
Classes
class AuthHandler
Common interface for handling authentication.
class BasicAuthHandler
Used for Basic auth.
class CurlWrapper
Lock like class to handler curl initialization and free.
class JsonAuthHandler
Typedefs
using HttpResult = std::pair< long, std::string >
return_code,response_body pair
Functions
static size_t WriteCallback (void *contents, size_t size, size_t nmemb, void *userp)
Default curl write callback.
HttpResult PerformCurlRequest (const std::string &path, const std::string &method, const std::string &host, AuthHandler *auth_handler, const std::string &data="")
Common function to perform http request uning curl.
Detailed Description
Namespace for httpr rest utilities.
Typedef Documentation
HttpResult
using rest_utils::HttpResult = typedef std::pair<long, std::string>
return_code,response_body pair
Function Documentation
PerformCurlRequest()
HttpResult rest_utils::PerformCurlRequest (const std::string & path, const std::string & method, const std::string & host, AuthHandler * auth_handler, const std::string & data = "")
Common function to perform http request uning curl.
Parameters
path
method
host
auth_handler
data
Exceptions
shared::CurlError - if curl error occurs
shared::HttpError - if curl results in return code >=400
Returns
HttpResult
References rest_utils::AuthHandler::AddAuthorization(), rest_utils::CurlWrapper::Get(), and WriteCallback().
Referenced by amqp_common::RabbitMQRestService::PerformRequest().
WriteCallback()
size_t rest_utils::WriteCallback (void * contents, size_t size, size_t nmemb, void * userp) static
Default curl write callback.
Parameters
contents
size
nmemb
userp
Referenced by PerformCurlRequest().