Distributed math architecture: mesh_storage Namespace Reference
mesh_storage Namespace Reference
meshStorage namespace
Classes
class MeshCreator
Class that handles 3d mesh creation and parameters management.
Typedefs
using LimType = std::array< FloatType, 4 >
stores upper and lower limit pairs for meshes
template<size_t N>
using MeshArr = std::array< co::MeshStorageType, N >
Functions
template<unsigned Ndots = 61>
FloatType Integrate (const std::function< FloatType(FloatType)> &function, FloatType left, FloatType right, unsigned int max_depth=5, FloatType tol=Eigen::NumTraits< FloatType >::epsilon())
template<unsigned Ndots = 61>
FloatType IntegrateLambdaForOneVariable (const co::IntegrableFunction &function, FloatType theta, FloatType phi, FloatType left, FloatType right, unsigned int max_depth=5, FloatType tol=1e-20)
co::MeshStorageType ComputeFunction (const co::MeshStorageType &a, const co::MeshStorageType &b, const co::DirectionGraph &func)
Computes functional mesh for 2 coordinates.
FloatType GetMeshDiffNorm (const co::MeshStorageType &mesh1, const co::MeshStorageType &mesh2)
Computes square Diff norm for two meshes.
void AddMesh (co::MeshStorageType &a, const co::MeshStorageType &b)
template<template< typename ... > typename container = std::vector>
std::array< co::MeshStorageType, 2 > MyMeshGrid (const container< co::FloatType > &a, const container< co::FloatType > &b)
Computes meshes using 2 double arrays.
template<template< typename ... > typename container = std::vector, typename T = FloatType, bool end = true>
container< T > MyLinspace (T lower_bound, T upper_bound, size_t n)
Generates linearly spaced vectors.
co::MeshDrawClass Unflatten (const common_types::MeshStorageType &mm, const DimType &dims)
void PrintDec (const mesh_storage::MeshCreator &mmesh, std::ostream &out)
Prints mesh in human readable way.
MeshArr< 3 > SphericalTransformation (const MeshCreator &oth)
Detailed Description
meshStorage namespace
Typedef Documentation
LimType
using mesh_storage::LimType = typedef std::array<FloatType, 4>
stores upper and lower limit pairs for meshes
MeshArr
template<size_t N> using mesh_storage::MeshArr = typedef std::array<co::MeshStorageType, N>
Function Documentation
AddMesh()
void mesh_storage::AddMesh (co::MeshStorageType & a, const co::MeshStorageType & b)
{
  a += b;
}
ComputeFunction()
co::MeshStorageType mesh_storage::ComputeFunction (const co::MeshStorageType & a, const co::MeshStorageType & b, const co::DirectionGraph & func)
Computes functional mesh for 2 coordinates.
Parameters
a
b
func
{
  if (!a.size() || !b.size()) {
    throw shared::MyException(
        fmt::format("Zero container sizes: a.size() = {},b.size() = {}", a.size(), b.size()));
  }
  if (a.size() != b.size()) {
    throw shared::mismatchedSizes(a.size(), b.size());
  }
  auto sz = a.size();
  co::MeshStorageType result(sz);
  for (size_t i = 0; i < sz; ++i) {
    result[i] = func(a[i], b[i]);
  }
  return result;
}
Referenced by mesh_storage::MeshCreator::ApplyFunction().
GetMeshDiffNorm()
FloatType mesh_storage::GetMeshDiffNorm (const co::MeshStorageType & mesh1, const co::MeshStorageType & mesh2)
Computes square Diff norm for two meshes.
Parameters
mesh1
mesh2
{
  return sqrt(pow((mesh1 - mesh2), 2).sum());
}
Integrate()
template<unsigned Ndots = 61> FloatType mesh_storage::Integrate (const std::function< FloatType(FloatType)> & function, FloatType left, FloatType right, unsigned int max_depth = 5, FloatType tol = Eigen::NumTraits<FloatType>::epsilon())
Template Parameters
Ndots
Parameters
function
left
right
max_depth
tol
{
  FloatType error;
  double q = boost::math::quadrature::gauss_kronrod<FloatType, Ndots>::integrate(
      function,
      left,
      right,
      max_depth,
      tol,
      &error);
  return q;
}
IntegrateLambdaForOneVariable()
template<unsigned Ndots = 61> FloatType mesh_storage::IntegrateLambdaForOneVariable (const co::IntegrableFunction & function, FloatType theta, FloatType phi, FloatType left, FloatType right, unsigned int max_depth = 5, FloatType tol = 1e-20)
{
  std::function<FloatType(FloatType)> tt = [&theta, &phi, &function](FloatType t) {
    return function(theta, phi, t);
  };
  return Integrate<Ndots>(tt, left, right, max_depth, tol);
}
MyLinspace()
template<template< typename ... > typename container = std::vector, typename T = FloatType, bool end = true> container< T > mesh_storage::MyLinspace (T lower_bound, T upper_bound, size_t n)
Generates linearly spaced vectors.
Template Parameters
container
T
end
Parameters
lower_bound
upper_bound
n
Returns
{
  if (n == 0 || lower_bound - upper_bound == 0) {
    throw std::invalid_argument("Zero linspace size");
  }
  container<T> result(n);
  size_t div;
  if constexpr (end) {
    div = n - 1;
  } else {
    div = n;
  }
  T step = (upper_bound - lower_bound) / (T) div;
  for (int i = 0; i < n; ++i) {
    result[i] = i * step + lower_bound;
  }
  return result;
}
MyMeshGrid()
template<template< typename ... > typename container = std::vector> std::array< co::MeshStorageType, 2 > mesh_storage::MyMeshGrid (const container< co::FloatType > & a, const container< co::FloatType > & b)
Computes meshes using 2 double arrays.
Parameters
a
b
Returns
{
  std::array<co::MeshStorageType, 2> ret = {co::MeshStorageType(b.size() * a.size()),
                                            co::MeshStorageType(b.size() * a.size())};
  for (size_t i = 0; i < b.size(); ++i) {
    for (size_t j = 0; j < a.size(); ++j) {
      ret[0][i * a.size() + j] = a[j];
      ret[1][i * a.size() + j] = b[i];
    }
  }
  return ret;
}
Referenced by mesh_storage::MeshCreator::ConstructMeshes().
PrintDec()
void mesh_storage::PrintDec (const mesh_storage::MeshCreator & mmesh, std::ostream & out)
Prints mesh in human readable way.
Parameters
mmesh
out
{
  auto ext0 = mmesh.dimensions_[0];
  auto ext1 = mmesh.dimensions_[1];
  out << ext0 << '\t' << ext1 << '\n';
  out << "Функция I(phi,th)\n";
  out << "phi\\th\t\t";
  std::vector<FloatType> row(ext0);
  for (size_t i = 0; i < ext0 - 1; ++i) {
    row[i] = mmesh.data_[1][i * ext1];
    out << mmesh.data_[1][i * ext1] << '\t';
  }
  row[ext0 - 1] = mmesh.data_[1][(ext0 - 1) * ext1];
  out << mmesh.data_[1][(ext0 - 1) * ext1]
      << '\n';
  std::vector<FloatType> col(ext1);
  for (size_t i = 0; i < ext1; ++i) {
    auto phi = mmesh.data_[0][i];
    col[i] = phi;
    out << phi << "\t";
    for (size_t j = 0; j < ext0 - 1; ++j) {
      out << mmesh.data_[2][j * ext1 + i] << "\t";
    }
    out << mmesh.data_[2][(ext0 - 1) * ext1 + i] << "\n";
  }
}
References mesh_storage::MeshCreator::data_, and mesh_storage::MeshCreator::dimensions_.
Referenced by print_utils::PrintMesh().
SphericalTransformation()
MeshArr< 3 > mesh_storage::SphericalTransformation (const MeshCreator & oth)
Parameters
oth
Returns
{
  MeshArr<3> res;
  for (size_t i = 0; i < 3; ++i) {
    res[i] = oth.data_[i];
  }
  res[0] = oth.data_[2] * sin(oth.data_[1]) * cos(oth.data_[0]);
  res[1] = oth.data_[2] * sin(oth.data_[1]) * sin(oth.data_[0]);
  res[2] = oth.data_[2] * cos(oth.data_[1]);
  return res;
}
Unflatten()
co::MeshDrawClass mesh_storage::Unflatten (const common_types::MeshStorageType & mm, const DimType & dims)
{
  auto res = co::MeshDrawClass(dims[0], co::StdVec(dims[1], 0.0));
  for (size_t i = 0; i < dims[0]; ++i) {
    for (size_t j = 0; j < dims[1]; ++j) {
      res[i][j] = mm[i * dims[1] + j];
    }
  }
  return res;
}