Distributed math architecture: network_types Namespace Reference
network_types Namespace Reference
Namespace for network related types.
Classes
class AbstractConnectionString
us it for verbose names
class AMQPSQLCStr
Structure to store and format AMQP connection string.
struct channel
channel struct
struct connection
connection struct
struct exchange
Exchange struct.
struct global_param
global_param struct
struct message
message struct
class PostgreSQLCStr
Structure to store and format PostgreSQL connection string.
struct queue
Queue struct.
struct queueBinding
queueBinding struct
struct rabbitMQUser
rabbitMQUser class
struct TestSolveParam
Simple task sent structure.
Enumerations
enum class HttpMethod {
GET , POST , PUT , DELETE ,
HEAD , OPTIONS , PATCH , CONNECT ,
TRACE
}
Functions
std::string UrlDecode (std::string_view url)
Replaces all url delimiters with spaces for scanf parsing.
Json::Value VariantToJson (const JsonVariant &v)
Casts JsonVariant to Json::Value.
JsonVariant JsonToVariant (const Json::Value &val)
Casts Json::Value to JsonVariant.
std::string ToString (HttpMethod method)
HttpMethod FromString (const std::string &str)
Variables
static const std::vector< EnumMapping< AMQP::ExchangeType > > kExchangeTypeMappings
static const auto kStrToExchangeType
const auto kExchangeTypeToStr
static const std::vector< EnumMapping< HttpMethod > > kHttpMethodMappings
static const auto kStrToHttpMethod
static const auto kHttpMethodToStr
Detailed Description
Namespace for network related types.
Enumeration Type Documentation
HttpMethod
enum class network_types::HttpMethod strong
Enumerator
GET
POST
PUT
DELETE
HEAD
OPTIONS
PATCH
CONNECT
TRACE
Function Documentation
FromString()
HttpMethod network_types::FromString (const std::string & str) inline
References kStrToHttpMethod, and enum_utils::StrToEnum().
JsonToVariant()
JsonVariant network_types::JsonToVariant (const Json::Value & val)
Casts Json::Value to JsonVariant.
Parameters
val
Referenced by network_types::TestSolveParam::TestSolveParam().
ToString()
std::string network_types::ToString (HttpMethod method) inline
References enum_utils::EnumToStr(), and kHttpMethodToStr.
Referenced by amqp_common::RabbitMQRestService::PerformRequest().
UrlDecode()
std::string network_types::UrlDecode (std::string_view url)
Replaces all url delimiters with spaces for scanf parsing.
Since scn::scan parses strings as words, there exist a need to manually
separate them with whitespaces see
Parameters
url
See also
PostgreSQLCStr::FromString
AMQPSQLCStr::FromString
Referenced by network_types::PostgreSQLCStr::FromString(), and network_types::AMQPSQLCStr::FromString().
VariantToJson()
Json::Value network_types::VariantToJson (const JsonVariant & v)
Casts JsonVariant to Json::Value.
Parameters
v
Referenced by network_types::TestSolveParam::ToJson().
Variable Documentation
kExchangeTypeMappings
const std::vector<EnumMapping<AMQP::ExchangeType> > network_types::kExchangeTypeMappings static
Initial value:
= {
    {AMQP::fanout,"fanout"},
    {AMQP::direct,"direct"},
    {AMQP::topic,"topic"},
    {AMQP::headers,"headers"},
    {AMQP::consistent_hash,"consistent_hash"},
    {AMQP::message_deduplication,"message_deduplication"}
}
kExchangeTypeToStr
const auto network_types::kExchangeTypeToStr
Initial value:
=
    CreateEnumToStrMap(kExchangeTypeMappings)
Referenced by network_types::exchange::ToJson().
kHttpMethodMappings
const std::vector<EnumMapping<HttpMethod> > network_types::kHttpMethodMappings static
Initial value:
= {
    {HttpMethod::GET, "GET"},
    {HttpMethod::POST, "POST"},
    {HttpMethod::PUT, "PUT"},
    {HttpMethod::DELETE, "DELETE"},
    {HttpMethod::HEAD, "HEAD"},
    {HttpMethod::OPTIONS, "OPTIONS"},
    {HttpMethod::PATCH, "PATCH"},
    {HttpMethod::CONNECT, "CONNECT"},
    {HttpMethod::TRACE, "TRACE"}
}
kHttpMethodToStr
const auto network_types::kHttpMethodToStr static
Initial value:
=
    CreateEnumToStrMap(kHttpMethodMappings)
Referenced by ToString().
kStrToExchangeType
const auto network_types::kStrToExchangeType static
Initial value:
=
    CreateStrToEnumMap(kExchangeTypeMappings)
kStrToHttpMethod
const auto network_types::kStrToHttpMethod static
Initial value:
=
    CreateStrToEnumMap(kHttpMethodMappings)
Referenced by FromString().