Distributed math architecture: timing Namespace Reference
timing Namespace Reference
timing namespace
Classes
class ClockArray
Clock array template class.
struct LocationComparator
Typedefs
using ClockType = typename std::conditional< std::chrono::high_resolution_clock::is_steady, std::chrono::high_resolution_clock, std::chrono::steady_clock >::type
using ClockTimepoint = ClockType::time_point
using TimepointType = uint64_t
using LocationType = std::array< std::string, 5 >
structure to store file data
Functions
template<typename T , size_t sz>
requires std::is_floating_point_v< T > or std::is_integral_v< T > std::ostream & operator<< (std::ostream &out, std::array< T, sz > &arr)
Array printer.
template<Duration dur>
TimepointType Now ()
Returns now with specified precision.
template<typename T , size_t sz>
bool operator== (const std::array< T, sz > &arr1, const std::array< T, sz > &arr2)
Array comparator.
std::string TpToString (TimepointType system_ms)
Serializes given timepoint to string.
std::optional< TimepointType > StrToTimepoint (std::string_view ts)
Retrives TimepointType from a given string.
template<typename T , size_t sz>
requires std::is_convertible_v< T, std::string > std::ostream & operator<< (std::ostream &out, std::array< T, sz > &arr)
Array printer.
Variables
template<typename D >
concept Duration = is_specialization_of<D, std::chrono::duration>::value
Detailed Description
timing namespace
Typedef Documentation
ClockTimepoint
using timing::ClockTimepoint = typedef ClockType::time_point
ClockType
using timing::ClockType = typedef typename std::conditional<std::chrono::high_resolution_clock::is_steady, std::chrono::high_resolution_clock, std::chrono::steady_clock>::type
Global clock used for range measurement
LocationType
using timing::LocationType = typedef std::array<std::string, 5>
structure to store file data
TimepointType
using timing::TimepointType = typedef uint64_t
default portable time-point type
Function Documentation
Now()
template<Duration dur> TimepointType timing::Now () inline
Returns now with specified precision.
Template Parameters
dur
Returns
operator<<() [1/2]
template<typename T , size_t sz> requires std::is_floating_point_v<T> or std::is_integral_v<T> std::ostream& timing::operator<< (std::ostream & out, std::array< T, sz > & arr)
Array printer.
Template Parameters
T
sz
Parameters
out
arr
Returns
operator<<() [2/2]
template<typename T , size_t sz> requires std::is_convertible_v<T, std::string> std::ostream& timing::operator<< (std::ostream & out, std::array< T, sz > & arr)
Array printer.
Template Parameters
T
sz
Parameters
out
arr
Returns
operator==()
template<typename T , size_t sz> bool timing::operator== (const std::array< T, sz > & arr1, const std::array< T, sz > & arr2)
Array comparator.
Template Parameters
T
sz
Parameters
arr1
arr2
StrToTimepoint()
std::optional< TimepointType > timing::StrToTimepoint (std::string_view ts)
Retrives TimepointType from a given string.
Note
uses mktime to get timepoint representation
Parameters
ts
Referenced by db_common::Experiment::Experiment(), db_common::Iteration::Iteration(), db_common::Log::Log(), and db_common::User::User().
TpToString()
std::string timing::TpToString (timing::TimepointType system_ms)
Serializes given timepoint to string.
Note
uses localtime_r when forming time
Parameters
system_ms
Variable Documentation
Duration
template<typename D > concept timing::Duration = is_specialization_of<D, std::chrono::duration>::value