Distributed math architecture: test_common Namespace Reference
test_common Namespace Reference
Testing utilities namespace.
Classes
struct AuthParams
struct get_template
struct get_template< C< Args... > >
retrieves template template and saves it inside type
struct arrayEqualComparator
struct arrayDoubleComparator
struct twoDArrayDoubleComparator
Functions
template<typename Func >
bool WaitFor (Func condition, std::chrono::seconds timeout=std::chrono::seconds(5), std::chrono::milliseconds interval=std::chrono::milliseconds(100))
template<typename T >
bool IsNear (T val1, T val2, T abs_error)
Custom check for double near.
template<typename TestSuite , typename ... Args>
auto FirstValueTuplePrinter (const testing::TestParamInfo< typename TestSuite::ParamType > &info)
Printer function used to name tests in parameterized test suites.
std::string Demangle (std::string_view mangled_name)
Transforms typeid(...).name() into human readable type.
template<typename T >
std::string DemangledName ()
Transforms input type into a valid string for gtest.
template<typename TestSuite >
auto TupleToString (const testing::TestParamInfo< typename TestSuite::ParamType > &info)
converts tuple to string with _ as a delimiter
template<bool Expect = false, HasSizeMethod T1, HasSizeMethod T2>
requires valueTyped< T1 > &&valueTyped< T2 > &&std::common_with< typename T1::value_type, typename T2::value_type > void CompareArrays (const T1 &solution, const T2 &solution2, const std::function< bool(const typename T1::value_type &a, const typename T2::value_type &b, size_t i, FloatType tol) > &eq_operator, FloatType tol=kTool)
Compares two continious collections.
template<bool Expect = false, typename M1_t , typename M2_t >
void Compare2DArrays (const M1_t &mat1, const M2_t &mat2, const std::function< bool(const FloatType &a, const FloatType &b, size_t i, size_t j, FloatType tol) > &eq_operator, FloatType tol=kTool)
Compares 2d arrays.
Variables
constexpr double kTool = std::numeric_limits<decltype(kTool)>::epsilon()
Detailed Description
Testing utilities namespace.
Class Documentation
test_common::AuthParams
struct test_common::AuthParams
Class Members
string host
string password
string username
test_common::get_template
struct test_common::get_template
template<typename...>
struct test_common::get_template<... >
test_common::get_template< C< Args... > >
struct test_common::get_template< C< Args... > >
template<template< typename... > typename C, typename... Args>
struct test_common::get_template< C< Args... > >
retrieves template template and saves it inside type
Template Parameters
C
Args
Class Members
Type
Function Documentation
Compare2DArrays()
template<bool Expect = false, typename M1_t , typename M2_t > void test_common::Compare2DArrays (const M1_t & mat1, const M2_t & mat2, const std::function< bool(const FloatType &a, const FloatType &b, size_t i, size_t j, FloatType tol) > & eq_operator, FloatType tol = kTool)
Compares 2d arrays.
Template Parameters
Expect - if true will use Expect pred instead of assert
M1_t
M2_t
Parameters
mat1
mat2
eq_operator
tol
References my_concepts::GetMatrElement(), and my_concepts::GetShape().
CompareArrays()
template<bool Expect = false, HasSizeMethod T1, HasSizeMethod T2> requires valueTyped<T1>&& valueTyped<T2>&& std::common_with<typename T1::value_type, typename T2::value_type> void test_common::CompareArrays (const T1 & solution, const T2 & solution2, const std::function< bool(const typename T1::value_type &a, const typename T2::value_type &b, size_t i, FloatType tol) > & eq_operator, FloatType tol = kTool)
Compares two continious collections.
Template Parameters
Expect - if true will use Expect pred instead of assert
T1
T2
Parameters
solution
solution2
eq_operator - some user defined comparison function
tol
Demangle()
std::string test_common::Demangle (std::string_view mangled_name) inline
Transforms typeid(...).name() into human readable type.
Parameters
mangled_name
Returns
Demangled type - if it's successful
empty string - otherwise
Referenced by DemangledName().
DemangledName()
template<typename T > std::string test_common::DemangledName ()
Transforms input type into a valid string for gtest.
Template Parameters
T
Returns
type name suitable for parametrized tests
References Demangle().
FirstValueTuplePrinter()
template<typename TestSuite , typename ... Args> auto test_common::FirstValueTuplePrinter (const testing::TestParamInfo< typename TestSuite::ParamType > & info)
Printer function used to name tests in parameterized test suites.
Template Parameters
TestSuite
Args
Parameters
info
IsNear()
template<typename T > bool test_common::IsNear (T val1, T val2, T abs_error)
Custom check for double near.
Template Parameters
T
Parameters
val1
val2
abs_error
TupleToString()
template<typename TestSuite > auto test_common::TupleToString (const testing::TestParamInfo< typename TestSuite::ParamType > & info)
converts tuple to string with _ as a delimiter
Template Parameters
TestSuite
Parameters
info
References print_utils::TupleToString().
WaitFor()
template<typename Func > bool test_common::WaitFor (Func condition, std::chrono::seconds timeout = std::chrono::seconds(5), std::chrono::milliseconds interval = std::chrono::milliseconds(100))
Variable Documentation
kTool
constexpr double test_common::kTool = std::numeric_limits<decltype(kTool)>::epsilon() constexpr