Distributed math architecture: enum_utils Namespace Reference
enum_utils Namespace Reference
Classes
struct EnumDoubleMapping
Structure to store enum mapping to some other class.
Typedefs
template<typename Enum >
using EnumMapping = EnumDoubleMapping< Enum, std::string >
Structure to store enum mapping.
template<typename Enum , typename From >
using MapFromTypeToEnum = std::unordered_map< From, Enum >
template<typename Enum , typename To >
using MapEnumToType = std::unordered_map< Enum, To >
Functions
template<typename Enum , typename From >
requires std::is_enum_v< Enum > MapFromTypeToEnum< Enum, From > CreateFromTypeToEnumMap (const std::vector< EnumDoubleMapping< Enum, From >> &mappings)
template<typename Enum , typename To >
requires std::is_enum_v< Enum > MapEnumToType< Enum, To > CreateEnumToTypeMap (const std::vector< EnumDoubleMapping< Enum, To >> &mappings)
Generate map from Enum to To type map.
template<typename Enum >
requires std::is_enum_v< Enum > MapFromTypeToEnum< Enum, std::string > CreateStrToEnumMap (const std::vector< EnumMapping< Enum >> &mappings)
Generate map from Str to enum value.
template<typename Enum >
requires std::is_enum_v< Enum > MapEnumToType< Enum, std::string > CreateEnumToStrMap (const std::vector< EnumMapping< Enum >> &mappings)
template<typename Enum , typename From >
requires std::is_enum_v< Enum > Enum FromToEnum (const From str, const MapFromTypeToEnum< Enum, From > &map)
Casts From type value to enum.
template<typename Enum , typename To >
requires std::is_enum_v< Enum > To EnumToType (Enum value, const std::unordered_map< Enum, To > &map)
Casts Enum Value To typed value.
template<typename Enum >
requires std::is_enum_v< Enum > Enum StrToEnum (const std::string &str, const std::unordered_map< std::string, Enum > &map)
Cast string to enum.
template<typename Enum >
requires std::is_enum_v< Enum > std::string EnumToStr (Enum value, const std::unordered_map< Enum, std::string > &map)
Casts enum value to string.
Class Documentation
enum_utils::EnumDoubleMapping
struct enum_utils::EnumDoubleMapping
template<typename Enum, typename To>
struct enum_utils::EnumDoubleMapping< Enum, To >
Structure to store enum mapping to some other class.
Template Parameters
Enum
Class Members
To to
Enum value
Typedef Documentation
EnumMapping
template<typename Enum > using enum_utils::EnumMapping = typedef EnumDoubleMapping<Enum,std::string>
Structure to store enum mapping.
Template Parameters
Enum
MapEnumToType
template<typename Enum , typename To > using enum_utils::MapEnumToType = typedef std::unordered_map<Enum, To>
MapFromTypeToEnum
template<typename Enum , typename From > using enum_utils::MapFromTypeToEnum = typedef std::unordered_map<From, Enum>
Function Documentation
CreateEnumToStrMap()
template<typename Enum > requires std::is_enum_v< Enum > MapEnumToType< Enum, std::string > enum_utils::CreateEnumToStrMap (const std::vector< EnumMapping< Enum >> & mappings)
Generate map from enum value to Str
Template Parameters
Enum
Parameters
mappings
Returns
References CreateEnumToTypeMap().
CreateEnumToTypeMap()
template<typename Enum , typename To > requires std::is_enum_v< Enum > MapEnumToType< Enum, To > enum_utils::CreateEnumToTypeMap (const std::vector< EnumDoubleMapping< Enum, To >> & mappings)
Generate map from Enum to To type map.
Template Parameters
Enum
To
Parameters
mappings
Referenced by CreateEnumToStrMap().
CreateFromTypeToEnumMap()
template<typename Enum , typename From > requires std::is_enum_v< Enum > MapFromTypeToEnum< Enum, From > enum_utils::CreateFromTypeToEnumMap (const std::vector< EnumDoubleMapping< Enum, From >> & mappings)
Generate map from From to Enum
Template Parameters
Enum
From
Parameters
mappings
Referenced by CreateStrToEnumMap().
CreateStrToEnumMap()
template<typename Enum > requires std::is_enum_v< Enum > MapFromTypeToEnum< Enum, std::string > enum_utils::CreateStrToEnumMap (const std::vector< EnumMapping< Enum >> & mappings)
Generate map from Str to enum value.
Template Parameters
Enum
Parameters
mappings
References CreateFromTypeToEnumMap().
EnumToStr()
template<typename Enum > requires std::is_enum_v<Enum> std::string enum_utils::EnumToStr (Enum value, const std::unordered_map< Enum, std::string > & map) inline
Casts enum value to string.
Template Parameters
Enum
Parameters
value
map
Returns
std::string
References EnumToType().
Referenced by db_service::DbService::CreateIteration(), db_service::DbService::CreateUser(), print_utils::operator<<(), shared::operator<<(), network_types::exchange::ToJson(), network_types::ToString(), db_service::DbService::UpdateExperimentStatus(), and db_service::DbService::UpdateIterationStatus().
EnumToType()
template<typename Enum , typename To > requires std::is_enum_v<Enum> To enum_utils::EnumToType (Enum value, const std::unordered_map< Enum, To > & map) inline
Casts Enum Value To typed value.
Template Parameters
Enum
To
Parameters
value
map
Returns
To value
Referenced by EnumToStr().
FromToEnum()
template<typename Enum , typename From > requires std::is_enum_v<Enum> Enum enum_utils::FromToEnum (const From str, const MapFromTypeToEnum< Enum, From > & map) inline
Casts From type value to enum.
Template Parameters
Enum
From
Parameters
str
map
Returns
Enum value
Referenced by StrToEnum().
StrToEnum()
template<typename Enum > requires std::is_enum_v<Enum> Enum enum_utils::StrToEnum (const std::string & str, const std::unordered_map< std::string, Enum > & map) inline
Cast string to enum.
Template Parameters
Enum
Parameters
str
map
Returns
Enum value
References FromToEnum().
Referenced by db_common::Experiment::Experiment(), network_types::FromString(), db_common::Iteration::Iteration(), db_common::Node::Node(), print_utils::operator>>(), and db_common::User::User().