Distributed math architecture: print_utils Namespace Reference
print_utils Namespace Reference
printUtils namespace
Classes
struct Delimiter
Struct to parse and compare delimiters.
class IosStatePreserve
A guard class to save current iostream state.
class IosStateScientific
Sets iostream precision to a fixed value after saving it's state.
Typedefs
using EFormat = Eigen::IOFormat
Enumerations
enum class EigenPrintFormats {
BASIC_ONE_DIMENSIONAL_VECTOR = 0 , VECTOR_FORMAT_1 , MATRIX_FORMAT , MATRIX_FORMAT_1 ,
VECTOR_DB_FORMAT
}
enum class IoFormat { SERIALIZABLE , HUMAN_READABLE }
General IOformat.
Functions
template<isOneDimensionalContinuous Collection>
Collection JsonToContinuous (const Json::Value &val, std::optional< size_t > sz=std::nullopt, bool sizeless_format=false)
Parse one dimensional array from json.
ms::MeshCreator FromJson (Json::Value &val, std::optional< ms::DimType > dim_opt=std::nullopt, std::optional< ms::LimType > lim_opt=std::nullopt)
Parse MeshCreator from json.
template<isOneDimensionalContinuous Struct>
Struct ParseOneDim (std::istream &in, std::optional< size_t > size_opt=std::nullopt, const EFormat &ef=EFormat())
Parse one dimensional array from provided istream.
template<isOneDimensionalContinuous Struct>
Struct ParseOneDimS (std::string_view str, std::optional< size_t > size_opt=std::nullopt, const EFormat &ef=EFormat())
Parse one dimensional array from std::string.
ct::MatrixType ParseMatrix (std::istream &in, std::optional< ct::DimType > dim_opt=std::nullopt, const EFormat &ef=EFormat())
Parse matrix.
template<isOneDimensionalContinuous Struct>
Struct ParseSolution (std::istream &in, IoFormat format=IoFormat::SERIALIZABLE, std::optional< size_t > size_opt=std::nullopt, const EFormat &ef=EFormat())
Parse solution function interface.
template<isOneDimensionalContinuous Struct>
Struct ParseCoordinates (std::istream &in, IoFormat format=IoFormat::SERIALIZABLE, std::optional< size_t > size_opt=std::nullopt, const EFormat &ef=EFormat())
Parse coordinates function interface.
mesh_storage::MeshCreator ParseMeshFrom (std::istream &in, IoFormat format=IoFormat::SERIALIZABLE, std::optional< ms::DimType > dim_opt=std::nullopt, std::optional< ms::LimType > lim_opt=std::nullopt, const EFormat &ef=EFormat())
Parses mesh creator from provided istream.
template<isOneDimensionalContinuous Struct>
Struct JsonToContinuous (const Json::Value &val, std::optional< size_t > sz, bool sizeless_format)
Parse one dimensional array from json.
Json::Value SerializeException (const shared::MyException &ex)
void PrintMesh (std::ostream &out, const ms::MeshCreator &mesh, const IoFormat &form=IoFormat::SERIALIZABLE, bool print_dims=true, bool print_lims=true, const EFormat &eigen_form=EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Print mesh to supplied std::ostream.
template<my_concepts::isOneDimensionalContinuous Collection>
Json::Value ContinuousToJson (const Collection &col, bool print_size=true, bool sizeless_format=false)
Cast any one dimensional array to Json::value.
Json::Value ToJson (const ms::MeshCreator &mesh, bool print_dims=true, bool print_lims=true)
Transforms MeshCreator to json.
template<typename Collection >
requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> || std::is_integral_v<typename Collection::value_type>
void OneDimSerialize (std::ostream &out, const Collection &col, bool print_size=true, const EFormat &eigen_form=EFormat())
Prints one dimensional Collection using Eigen format.
template<typename Collection >
requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> || std::is_integral_v<typename Collection::value_type>
std::string OneDimToString (const Collection &col, bool print_size=true, const EFormat &eigen_form=EFormat())
Prints one dimensional Collection to string using Eigen format.
void MatrixPrint1D (std::ostream &out, const common_types::MatrixType &matr, bool print_size=true, const EFormat &eigen_form=EFormat())
void MatrixPrint2D (std::ostream &out, const common_types::MatrixType &matr, bool print_dims=true, const EFormat &eigen_form=EIGENF(EigenPrintFormats::MATRIX_FORMAT_1))
Serializes matrix with coordinates.
template<typename Collection >
requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type>
int PrintSolutionFormat1 (std::ostream &out, const Collection &solution)
Human readable way to print solution vector.
template<typename Collection >
void PrintCoordinates2 (std::ostream &out, const Collection &col)
Human readable way to print coordinates vector.
template<typename Collection >
requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type>
void PrintCoordinates (std::ostream &out, const Collection &coord, IoFormat format=IoFormat::SERIALIZABLE, bool print_size=true, const EFormat &eigen_form=EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Basic interface for printing coordinates.
template<typename Collection >
requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type>
void PrintSolution (std::ostream &out, const Collection &sol, IoFormat format=IoFormat::SERIALIZABLE, bool print_size=true, const EFormat &eigen_form=EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Basic interface for printing solution.
template<my_concepts::isOneDimensionalContinuous Struct>
Json::Value ContinuousToJson (const Struct &col, bool print_size, bool sizeless_format)
template<typename Collection >
requires (my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type>)
void PrintCoordinates (std::ostream &out, const Collection &coord, IoFormat format, bool print_size, const EFormat &eigen_form)
Basic interface for printing coordinates.
template<typename TupleT , std::size_t TupSize = std::tuple_size_v<TupleT>>
std::string TupleToString (const TupleT &tp, const char *delim=",", const char *left="(", const char *right=")")
Prints tuple to string.
const EFormat & PrintEnumToFormat (EigenPrintFormats fmt)
Casts EigenFormat to Eformat.
std::istream & operator>> (std::istream &is, const Delimiter &delim)
Parses specified Delimiter from is.
bool ParseDelim (std::istream &in, std::string_view str)
Tries to parse Delim with str content.
std::ostream & operator<< (std::ostream &out, const IoFormat &form)
Printer for ioFormat.
std::istream & operator>> (std::istream &in, IoFormat &form)
Parser for ioFormat.
std::istream & operator>> (std::istream &is, EFormat &fmt)
Parser for EFormat.
std::ostream & operator<< (std::ostream &os, const EFormat &fmt)
Printer for EFormat.
bool operator== (const EFormat &lhs, const EFormat &rhs)
elementwise comparison between EFormat
bool isOnlyWhitespace (std::string_view text)
Variables
const auto kEnumToEigenFormatMap = CreateEnumToTypeMap(kEfEnToEigenFormatMappings)
Detailed Description
printUtils namespace
Typedef Documentation
EFormat
using print_utils::EFormat = typedef Eigen::IOFormat
Enumeration Type Documentation
EigenPrintFormats
enum class print_utils::EigenPrintFormats strong
Enumerator
BASIC_ONE_DIMENSIONAL_VECTOR
VECTOR_FORMAT_1
MATRIX_FORMAT
MATRIX_FORMAT_1
VECTOR_DB_FORMAT
{
  BASIC_ONE_DIMENSIONAL_VECTOR = 0,
  VECTOR_FORMAT_1,
  MATRIX_FORMAT,
  MATRIX_FORMAT_1,
  VECTOR_DB_FORMAT
};
IoFormat
enum class print_utils::IoFormat strong
General IOformat.
Enumerator
SERIALIZABLE
Basic print format(look a lot alike json)
HUMAN_READABLE
Human-readable representation for printed struct.
                    {
  SERIALIZABLE,
  HUMAN_READABLE
};
Function Documentation
ContinuousToJson() [1/2]
template<my_concepts::isOneDimensionalContinuous Collection> Json::Value print_utils::ContinuousToJson (const Collection & col, bool print_size = true, bool sizeless_format = false)
Cast any one dimensional array to Json::value.
Template Parameters
Collection
Parameters
col
print_size
sizeless_format
Returns
Json::Value with serialized array
Referenced by comp_services::ComputationNodeService::Connect(), comp_services::ComputationNodeService::GetStatus(), main_services::WorkerManagementService::GetStatus(), and ToJson().
ContinuousToJson() [2/2]
template<my_concepts::isOneDimensionalContinuous Struct> Json::Value print_utils::ContinuousToJson (const Struct & col, bool print_size, bool sizeless_format)
{
  Json::Value res;
  if (!sizeless_format) {
    if (print_size) {
      res["size"] = col.size();
    }
    for (size_t i = 0; i < col.size(); i++) {
      res["data"][(Json::ArrayIndex) i] = col[i];
    }
  } else {
    for (size_t i = 0; i < col.size(); i++) {
      res[(Json::ArrayIndex) i] = col[i];
    }
  }
  return res;
}
FromJson()
ms::MeshCreator print_utils::FromJson (Json::Value & val, std::optional< ms::DimType > dim_opt = std::nullopt, std::optional< ms::LimType > lim_opt = std::nullopt)
Parse MeshCreator from json.
Parameters
val
dim_opt
lim_opt
Returns
{
  mesh_storage::MeshCreator mm;
  ms::DimType dims;
  if (dim_opt.has_value()) {
    dims = dim_opt.value();
  } else {
    dims[0] = val["dimensions"][0].asUInt();
    dims[1] = val["dimensions"][1].asUInt();
  }
  ms::LimType lims{};
  if (lim_opt.has_value()) {
    lims = lim_opt.value();
  } else {
    for (int i = 0; i < lims.size(); ++i) {
      lims[i] = val["limits"][i].asDouble();
    }
  }
  mm.ConstructMeshes(dims, lims);
  mm.data_[2] = JsonToContinuous<common_types::MeshStorageType>(val, dims[0] * dims[1]);
  return mm;
}
References mesh_storage::MeshCreator::ConstructMeshes(), and mesh_storage::MeshCreator::data_.
isOnlyWhitespace()
bool print_utils::isOnlyWhitespace (std::string_view text) inline
{
  return !text.empty() && std::all_of(text.begin(), text.end(), [](unsigned char c) { return std::isspace(c); });
}
Referenced by operator>>().
JsonToContinuous() [1/2]
template<isOneDimensionalContinuous Struct> Struct print_utils::JsonToContinuous (const Json::Value & val, std::optional< size_t > sz = std::nullopt, bool sizeless_format = false)
Parse one dimensional array from json.
Template Parameters
Collection
Parameters
val
sz
sizeless_format
{
  size_t size;
  if (sz.has_value()) {
    size = sz.value();
  } else {
    if (sizeless_format) {
      size = val.size();
    } else {
      size = val["size"].asUInt();
    }
  }
  Struct res(size);
  if (!sizeless_format) {
    for (int i = 0; i < size; ++i) {
      res[i] = val["data"][i].as<std::remove_all_extents_t<typename Struct::value_type>>();
    }
  } else {
    for (int i = 0; i < size; ++i) {
      res[i] = val[i].as<std::remove_all_extents_t<typename Struct::value_type>>();
    }
  }
  return res;
}
JsonToContinuous() [2/2]
template<isOneDimensionalContinuous Collection> Collection print_utils::JsonToContinuous (const Json::Value & val, std::optional< size_t > sz = std::nullopt, bool sizeless_format = false)
Parse one dimensional array from json.
Template Parameters
Collection
Parameters
val
sz
sizeless_format
{
  size_t size;
  if (sz.has_value()) {
    size = sz.value();
  } else {
    if (sizeless_format) {
      size = val.size();
    } else {
      size = val["size"].asUInt();
    }
  }
  Struct res(size);
  if (!sizeless_format) {
    for (int i = 0; i < size; ++i) {
      res[i] = val["data"][i].as<std::remove_all_extents_t<typename Struct::value_type>>();
    }
  } else {
    for (int i = 0; i < size; ++i) {
      res[i] = val[i].as<std::remove_all_extents_t<typename Struct::value_type>>();
    }
  }
  return res;
}
MatrixPrint1D()
void print_utils::MatrixPrint1D (std::ostream & out, const common_types::MatrixType & matr, bool print_size = true, const EFormat & eigen_form = EFormat())
Flattens and prints matrix as row Vector
Parameters
out
matr
print_size
eigen_form
{
  auto map = Eigen::Map<const Eigen::RowVector<FloatType, -1>>(matr.data(), matr.size());
  if (print_size) {
    out << matr.size() << '\n';
  }
  out << map.format(eigen_form);
}
MatrixPrint2D()
void print_utils::MatrixPrint2D (std::ostream & out, const common_types::MatrixType & matr, bool print_dims = true, const EFormat & eigen_form = EIGENF(EigenPrintFormats::MATRIX_FORMAT_1))
Serializes matrix with coordinates.
Parameters
out
matr
print_dims
eigen_form
{
  if (print_dims) {
    out << matr.rows() << '\t' << matr.cols() << '\n';
  }
  out << matr.format(eigen_form);
}
OneDimSerialize()
template<typename Collection > requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> || std::is_integral_v<typename Collection::value_type> void print_utils::OneDimSerialize (std::ostream & out, const Collection & col, bool print_size = true, const EFormat & eigen_form = EFormat()) inline
Prints one dimensional Collection using Eigen format.
Template Parameters
Collection
Parameters
out
col
print_size
eigen_form
{
  auto map = ToEigenRowVector(col);
  if (print_size) {
    out << col.size() << '\n';
  }
  out << map.format(eigen_form);
}
References ToEigenRowVector().
Referenced by OneDimToString(), PrintCoordinates(), and PrintSolution().
OneDimToString()
template<typename Collection > requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> || std::is_integral_v<typename Collection::value_type> std::string print_utils::OneDimToString (const Collection & col, bool print_size = true, const EFormat & eigen_form = EFormat()) inline
Prints one dimensional Collection to string using Eigen format.
Template Parameters
Collection
Parameters
col
print_size
eigen_form
{
  std::ostringstream ss;
  OneDimSerialize(ss, col, print_size, eigen_form);
  return ss.str();
}
References OneDimSerialize().
operator<<() [1/2]
std::ostream & print_utils::operator<< (std::ostream & os, const EFormat & fmt)
Printer for EFormat.
This implementation uses " " to separate escape characters inside separators
Parameters
os
fmt
{
  os << fmt.precision << ' '
     << fmt.flags << ' '
     << std::quoted(fmt.coeffSeparator) << ' '
     << std::quoted(fmt.rowSeparator) << ' '
     << std::quoted(fmt.rowPrefix) << ' '
     << std::quoted(fmt.rowSuffix) << ' '
     << std::quoted(fmt.matPrefix) << ' '
     << std::quoted(fmt.matSuffix) << ' '
     << std::quoted(std::string(1, fmt.fill));
  return os;
}
operator<<() [2/2]
std::ostream & print_utils::operator<< (std::ostream & out, const IoFormat & form)
Printer for ioFormat.
Parameters
out
form
{
  out << enum_utils::EnumToStr(form, kIoToStr);
  return out;
}
References enum_utils::EnumToStr().
operator==()
bool print_utils::operator== (const EFormat & lhs, const EFormat & rhs)
elementwise comparison between EFormat
Parameters
lhs
rhs
Returns
{
  return lhs.precision == rhs.precision &&
      lhs.flags == rhs.flags &&
      lhs.coeffSeparator == rhs.coeffSeparator &&
      lhs.rowSeparator == rhs.rowSeparator &&
      lhs.rowPrefix == rhs.rowPrefix &&
      lhs.rowSuffix == rhs.rowSuffix &&
      lhs.matPrefix == rhs.matPrefix &&
      lhs.matSuffix == rhs.matSuffix &&
      lhs.fill == rhs.fill;
}
operator>>() [1/3]
std::istream & print_utils::operator>> (std::istream & in, IoFormat & form)
Parser for ioFormat.
Parameters
in
form
Exceptions
InvalidOption
{
  std::string a;
  in >> a;
  form = enum_utils::StrToEnum(a, kStringToIoFormat);
  return in;
}
References enum_utils::StrToEnum().
operator>>() [2/3]
std::istream & print_utils::operator>> (std::istream & is, const Delimiter & delim)
Parses specified Delimiter from is.
Sets failbit if delim is not found
Parameters
is
delim
{
  char c;
  if (isOnlyWhitespace(delim.str)) {
    return is;
  }
  for (auto &kCh : delim.str) {
    if (!is.get(c) || c != kCh) {
      is.setstate(std::ios::failbit);
      return is;
    }
  }
  return is;
}
References isOnlyWhitespace(), and print_utils::Delimiter::str.
operator>>() [3/3]
std::istream & print_utils::operator>> (std::istream & is, EFormat & fmt)
Parser for EFormat.
Parameters
is
fmt
{
  int precision, flags;
  std::string coeff_separator, row_prefix, row_suffix, mat_prefix, mat_suffix, fill_str;
  std::string row_separator;
  is >> precision >> flags
     >> std::quoted(coeff_separator)
     >> std::quoted(row_separator)
     >> std::quoted(row_prefix)
     >> std::quoted(row_suffix)
     >> std::quoted(mat_prefix)
     >> std::quoted(mat_suffix)
     >> std::quoted(fill_str);
  if (fill_str.size() != 1) {
    is.setstate(std::ios::failbit);
    return is;
  }
  char fill = fill_str[0];
  fmt = EFormat(precision, flags, coeff_separator, row_separator, row_prefix, row_suffix, mat_prefix, mat_suffix, fill);
  return is;
}
ParseCoordinates()
template<isOneDimensionalContinuous Struct> Struct print_utils::ParseCoordinates (std::istream & in, IoFormat format = IoFormat::SERIALIZABLE, std::optional< size_t > size_opt = std::nullopt, const EFormat & ef = EFormat())
Parse coordinates function interface.
Template Parameters
Struct
Parameters
in
format
size_opt
ef
Returns
coordinates vector
{
  Struct res;
  switch (format) {
    case IoFormat::SERIALIZABLE:return ParseOneDim<Struct>(in, size_opt, ef);
    case IoFormat::HUMAN_READABLE: {
      std::string dummy;
      std::getline(in, dummy);
      size_t n;
      in >> n;
      if (!in) {
        throw ioError(to_string(in.rdstate()));
      }
      Struct coord(n * 2);
      for (int i = 0; i < n; i++) {
        FloatType x, y;
        in >> coord[i] >> coord[i + n];
      }
      return coord;
    }
  }
  return res;
}
References HUMAN_READABLE, and SERIALIZABLE.
ParseDelim()
bool print_utils::ParseDelim (std::istream & in, std::string_view str)
Tries to parse Delim with str content.
Parameters
in
str
Returns
in.good()
{
  Delimiter delimiter(str);
  in >> delimiter;
  return in.good();
}
Referenced by ParseOneDim().
ParseMatrix()
ct::MatrixType print_utils::ParseMatrix (std::istream & in, std::optional< ct::DimType > dim_opt = std::nullopt, const EFormat & ef = EFormat())
Parse matrix.
Parameters
in
dim_opt
ef
{
  size_t rows, cols;
  if (dim_opt.has_value()) {
    rows = dim_opt.value()[0];
    cols = dim_opt.value()[1];
  } else {
    in >> rows >> cols;
  }
  if (!in) {
    throw ioError(to_string(in.rdstate()));
  }
  common_types::MatrixType res(rows, cols);
  for (int i = 0; i < rows; ++i) {
    for (int j = 0; j < cols; ++j) {
      in >> res(i, j);
    }
  }
  return res;
}
ParseMeshFrom()
mesh_storage::MeshCreator print_utils::ParseMeshFrom (std::istream & in, IoFormat format = IoFormat::SERIALIZABLE, std::optional< ms::DimType > dim_opt = std::nullopt, std::optional< ms::LimType > lim_opt = std::nullopt, const EFormat & ef = EFormat())
Parses mesh creator from provided istream.
Parameters
in
ef
format
dim_opt
lim_opt
Returns
MeshCreator instance
{
  mesh_storage::MeshCreator mm;
  ms::DimType dims{};
  ms::LimType lims{};
  switch (format) {
    case IoFormat::SERIALIZABLE:
      if (dim_opt.has_value()) {
        dims = dim_opt.value();
      } else {
        in >> dims[0] >> dims[1];
        if (!in) {
          throw ioError(to_string(in.rdstate()));
        }
      }
      if (lim_opt.has_value()) {
        lims = lim_opt.value();
      } else {
        in >> lims[0] >> lims[1] >> lims[2] >> lims[3];
        if (!in) {
          throw ioError(to_string(in.rdstate()));
        }
      }
      mm.data_[2] = ParseOneDim<common_types::MeshStorageType>(in, dims[0] * dims[1]);
      break;
    case IoFormat::HUMAN_READABLE:
      in >> dims[0] >> dims[1];
      if (!in) {
        throw ioError(to_string(in.rdstate()));
      }
      std::string dummy;
      std::getline(in, dummy);
      std::getline(in, dummy);
      in >> dummy;
      in >> lims[0];
      FloatType a;
      for (int i = 0; i < dims[0] - 2; ++i) {
        in >> a;
      }
      in >> lims[1];
      ct::MeshStorageType m(dims[0] * dims[1]);
      for (int i = 0; i < dims[1]; ++i) {
        FloatType temp = 0;
        in >> temp;
        if (i == 0) {
          lims[2] = temp;
        }
        if (i == dims[1] - 1) {
          lims[3] = temp;
        }
        for (int j = 0; j < dims[0]; ++j) {
          FloatType val;
          in >> val;
          m[j * dims[1] + i] = val;
        }
      }
      mm.ConstructMeshes(dims, lims);
      mm.data_[2] = m;
      break;
  }
  mm.ConstructMeshes(dims, lims);
  return mm;
}
References mesh_storage::MeshCreator::ConstructMeshes(), mesh_storage::MeshCreator::data_, HUMAN_READABLE, and SERIALIZABLE.
ParseOneDim()
template<isOneDimensionalContinuous Struct> Struct print_utils::ParseOneDim (std::istream & in, std::optional< size_t > size_opt = std::nullopt, const EFormat & ef = EFormat())
Parse one dimensional array from provided istream.
Template Parameters
Struct
Parameters
in
size_opt
ef
Returns
Struct to store the values
{
  size_t size;
  if (size_opt.has_value()) {
    size = size_opt.value();
  } else {
    in >> size;
  }
  if (!in) {
    throw ioError(to_string(in.rdstate()));
  }
  Struct res(size);
  ParseDelim(in, ef.rowPrefix);
  for (size_t i = 0; i < size; ++i) {
    in >> res[i];
    if (i < size - 1) {
      ParseDelim(in, ef.coeffSeparator);
    }
  }
  ParseDelim(in, ef.rowSuffix);
  return res;
}
References ParseDelim().
ParseOneDimS()
template<isOneDimensionalContinuous Struct> Struct print_utils::ParseOneDimS (std::string_view str, std::optional< size_t > size_opt = std::nullopt, const EFormat & ef = EFormat()) inline
Parse one dimensional array from std::string.
Template Parameters
Struct
Parameters
str - input string
size_opt
ef
Returns
Struct to store the values
{
  std::istringstream is(str.data());
  return ParseOneDim<Struct>(is, size_opt, ef);
}
ParseSolution()
template<isOneDimensionalContinuous Struct> Struct print_utils::ParseSolution (std::istream & in, IoFormat format = IoFormat::SERIALIZABLE, std::optional< size_t > size_opt = std::nullopt, const EFormat & ef = EFormat())
Parse solution function interface.
Template Parameters
Struct
Parameters
in
format
size_opt
ef
Returns
solution vector
{
  Struct res;
  switch (format) {
    case IoFormat::SERIALIZABLE:return ParseOneDim<Struct>(in, size_opt, ef);
    case IoFormat::HUMAN_READABLE: {
      size_t n;
      in >> n;
      std::string dummy;
      std::getline(in, dummy);
      std::getline(in, dummy);
      std::getline(in, dummy);
      if (!in) {
        throw ioError(to_string(in.rdstate()));
      }
      Struct sol(n * 4);
      for (int i = 0; i < n; i++) {
        FloatType ax, bx, cx;
        FloatType ay, by, cy;
        in >> ax >> bx >> cx >> ay >> by >> cy;
        sol[2 * i] = ax;
        sol[2 * i + 2 * n] = bx;
        sol[2 * i + 1] = ay;
        sol[2 * i + 1 + 2 * n] = by;
      }
      return sol;
    }
  }
  return res;
}
References HUMAN_READABLE, and SERIALIZABLE.
PrintCoordinates() [1/2]
template<typename Collection > requires (my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type>) void print_utils::PrintCoordinates (std::ostream & out, const Collection & coord, IoFormat format = IoFormat::SERIALIZABLE, bool print_size = true, const EFormat & eigen_form = EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Basic interface for printing coordinates.
Template Parameters
Collection
Parameters
out
coord
format
print_size
eigen_form
{
  switch (format) {
    case IoFormat::SERIALIZABLE:OneDimSerialize(out, coord, print_size, eigen_form);
      break;
    case IoFormat::HUMAN_READABLE: {
      IosStateScientific ios_state_scientific(out, out.precision());
      PrintCoordinates2(out, coord);
      break;
    }
  }
}
References HUMAN_READABLE, OneDimSerialize(), PrintCoordinates2(), and SERIALIZABLE.
PrintCoordinates() [2/2]
template<typename Collection > requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> void print_utils::PrintCoordinates (std::ostream & out, const Collection & coord, IoFormat format = IoFormat::SERIALIZABLE, bool print_size = true, const EFormat & eigen_form = EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Basic interface for printing coordinates.
Template Parameters
Collection
Parameters
out
coord
format
print_size
eigen_form
{
  switch (format) {
    case IoFormat::SERIALIZABLE:OneDimSerialize(out, coord, print_size, eigen_form);
      break;
    case IoFormat::HUMAN_READABLE: {
      IosStateScientific ios_state_scientific(out, out.precision());
      PrintCoordinates2(out, coord);
      break;
    }
  }
}
References HUMAN_READABLE, OneDimSerialize(), PrintCoordinates2(), and SERIALIZABLE.
PrintCoordinates2()
template<typename Collection > void print_utils::PrintCoordinates2 (std::ostream & out, const Collection & col)
Human readable way to print coordinates vector.
Template Parameters
Collection
Parameters
out
col
{
  out << " \n";
  if constexpr (not my_concepts::HasBracketsNested<Collection>) {
    auto n = col.size() / 2;
    out << n << '\n';
    for (int i = 0; i < n; ++i) {
      out << col[i] << '\t' << col[i + n] << "\n";
    }
  } else {
    auto n = col[0].size();
    out << n << '\n';
    for (int i = 0; i < n; ++i) {
      out << col[0][i] << '\t' << col[1][i] << "\n";
    }
  }
}
Referenced by PrintCoordinates().
PrintEnumToFormat()
const EFormat & print_utils::PrintEnumToFormat (EigenPrintFormats fmt)
Casts EigenFormat to Eformat.
Parameters
fmt
{
  return kEnumTo.at(static_cast<size_t>(fmt));
}
PrintMesh()
void print_utils::PrintMesh (std::ostream & out, const ms::MeshCreator & mesh, const IoFormat & form = IoFormat::SERIALIZABLE, bool print_dims = true, bool print_lims = true, const EFormat & eigen_form = EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Print mesh to supplied std::ostream.
Parameters
mesh
out
form
print_dims
print_lims
eigen_form
{
  switch (form) {
    case IoFormat::SERIALIZABLE:goto ser;
    case IoFormat::HUMAN_READABLE: {
      goto human;
    }
  }
  ser:
  {
    IosStateScientific ios_state_scientific(out, out.precision());
    if (print_dims) {
      out << mesh.dimensions_[0] << '\t' << mesh.dimensions_[1] << '\n';
    }
    if (print_lims) {
      out << mesh.limits_[0] << '\t' << mesh.limits_[1] << '\n';
      out << mesh.limits_[2] << '\t' << mesh.limits_[3] << '\n';
    }
    auto mm = ToEigenRowVector(mesh.data_.back());
    out << mm.format(eigen_form);
    return;
  }
  human:
  {
    IosStateScientific ios_state_scientific(out, out.precision());
    mesh_storage::PrintDec(mesh, out);
  }
}
References mesh_storage::MeshCreator::data_, mesh_storage::MeshCreator::dimensions_, HUMAN_READABLE, mesh_storage::MeshCreator::limits_, mesh_storage::PrintDec(), SERIALIZABLE, and ToEigenRowVector().
PrintSolution()
template<typename Collection > requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> void print_utils::PrintSolution (std::ostream & out, const Collection & sol, IoFormat format = IoFormat::SERIALIZABLE, bool print_size = true, const EFormat & eigen_form = EIGENF(EigenPrintFormats::VECTOR_FORMAT_1))
Basic interface for printing solution.
Template Parameters
Collection
Parameters
out
sol
format
print_size
eigen_form
{
  switch (format) {
    case IoFormat::SERIALIZABLE:OneDimSerialize(out, sol, print_size, eigen_form);
      break;
    case IoFormat::HUMAN_READABLE: {
      IosStateScientific ios_state_scientific(out, out.precision());
      PrintSolutionFormat1(out, sol);
      break;
    }
  }
}
References HUMAN_READABLE, OneDimSerialize(), PrintSolutionFormat1(), and SERIALIZABLE.
PrintSolutionFormat1()
template<typename Collection > requires my_concepts::isOneDimensionalContinuous<Collection> && std::is_floating_point_v<typename Collection::value_type> int print_utils::PrintSolutionFormat1 (std::ostream & out, const Collection & solution)
Human readable way to print solution vector.
Template Parameters
Collection
Parameters
out
solution
Returns
{
  int n = solution.size() / 4.0;
  out << n << '\n';
  out << "  \n";
  out << " Ai(x\\ny)\tBi(x\\ny)\tCi(x\\ny)\n";
  for (int i = 0; i < n; i++) {
    auto cx = sqrt(solution[2 * i] * solution[2 * i] +
        solution[2 * i + 2 * n] * solution[2 * i + 2 * n]);
    auto cy = sqrt(solution[2 * i + 1] * solution[2 * i + 1] +
        solution[2 * i + 1 + 2 * n] * solution[2 * i + 1 + 2 * n]);
    out << solution[2 * i] << "\t"
        << solution[2 * i + 2 * n] << "\t"
        << cx << "\n";
    out << solution[2 * i + 1] << "\t"
        << solution[2 * i + 1 + 2 * n] << "\t"
        << cy << "\n";
  }
  return 0;
}
Referenced by PrintSolution().
SerializeException()
Json::Value print_utils::SerializeException (const shared::MyException & ex)
{
  Json::Value res;
  res["message"] = ex.what();
  res["severity"] = shared::kSevToStr[static_cast<unsigned long>(ex.getSev())];
  return res;
}
References shared::MyException::getSev().
ToJson()
Json::Value print_utils::ToJson (const ms::MeshCreator & mesh, bool print_dims = true, bool print_lims = true)
Transforms MeshCreator to json.
Parameters
mesh
print_dims
print_lims
Returns
Json::Value with serialized meshCreator
{
  Json::Value res = ContinuousToJson(mesh.data_[2], false);
  if (print_dims) {
    res["dimensions"][0] = mesh.dimensions_[0];
    res["dimensions"][1] = mesh.dimensions_[1];
  }
  if (print_lims) {
    for (int i = 0; i < mesh.limits_.size(); i++) {
      res["limits"][i] = mesh.limits_[i];
    }
  }
  return res;
}
References ContinuousToJson(), mesh_storage::MeshCreator::data_, mesh_storage::MeshCreator::dimensions_, and mesh_storage::MeshCreator::limits_.
TupleToString()
template<typename TupleT , std::size_t TupSize = std::tuple_size_v<TupleT>> std::string print_utils::TupleToString (const TupleT & tp, const char * delim = ",", const char * left = "(", const char * right = ")")
Prints tuple to string.
Template Parameters
TupleT
TupSize
Parameters
tp
delim - is printed after each tuple element
left - is printed before all tuple elements
right - is printed after all tuple elements
{
  return []<typename TupleTy, std::size_t... Is>(const TupleTy &tp, const char *delim, const char *left,
                                                 const char *right, std::index_sequence<Is...>) -> std::string {
    std::stringstream res;
    res << left;
    (..., (res << (Is == 0 ? "" : delim) << get<Is>(tp)));
    res << right;
    return res.str();
  }.operator()(tp, delim, left, right, std::make_index_sequence<TupSize>{});
}
Variable Documentation
kEnumToEigenFormatMap
const auto print_utils::kEnumToEigenFormatMap = CreateEnumToTypeMap(kEfEnToEigenFormatMappings)