Distributed math architecture: computationalLib/test/network_shared/networkTypesTests.cpp File Reference
networkTypesTests.cpp File Reference
#include <gtest/gtest.h>
#include "../GoogleCommon.h"
#include "network_shared/networkTypes.h"
Classes
class TestSolveParam_TS
class NetworkTypesConversionTests
Functions
void ExpectTestSolveParamEqual (const TestSolveParam &lhs, const TestSolveParam &rhs)
void ExpectQueueBindingEqual (const queueBinding &a, const queueBinding &b)
TEST_F (TestSolveParam_TS, TestValidSlice)
TEST_F (TestSolveParam_TS, TestZeroSizeSlice)
TEST_F (TestSolveParam_TS, TestTooLargeSlice)
TEST_F (TestSolveParam_TS, SerializeToJson)
TEST_F (TestSolveParam_TS, DeserializeFromJson)
TEST_F (TestSolveParam_TS, SerializeDeserializeEquality)
TEST_F (NetworkTypesConversionTests, VariantToJson_Nullptr)
TEST_F (NetworkTypesConversionTests, VariantToJson_Bool)
TEST_F (NetworkTypesConversionTests, VariantToJson_Int64)
TEST_F (NetworkTypesConversionTests, VariantToJson_UInt64)
TEST_F (NetworkTypesConversionTests, VariantToJson_Double)
TEST_F (NetworkTypesConversionTests, VariantToJson_String)
TEST_F (NetworkTypesConversionTests, JsonToVariant_Null)
TEST_F (NetworkTypesConversionTests, JsonToVariant_Boolean)
TEST_F (NetworkTypesConversionTests, JsonToVariant_Int)
TEST_F (NetworkTypesConversionTests, JsonToVariant_UInt)
TEST_F (NetworkTypesConversionTests, JsonToVariant_Double)
TEST_F (NetworkTypesConversionTests, JsonToVariant_String)
TEST_F (NetworkTypesConversionTests, JsonToVariant_UnsuprotedType)
TEST (NetworkTypesRabbitMQUserTests, JsonConstructor)
TEST (NetworkTypesExchangeTests, JsonConstructorAndToJson)
TEST (NetworkTypesExchangeTests, ParameterizedConstructor)
TEST (NetworkTypesQueueTests, JsonConstructorAndToJson)
TEST (NetworkTypesQueueTests, ParameterizedConstructor)
TEST (NetworkTypesQueueBindingTests, ConstructFromJson)
TEST (NetworkTypesQueueBindingTests, ConstructFromStrings)
TEST (NetworkTypesQueueBindingTests, ConstructJsonEquivalence)
Function Documentation
ExpectQueueBindingEqual()
void ExpectQueueBindingEqual (const queueBinding & a, const queueBinding & b)
References network_types::queueBinding::exchange, and network_types::queueBinding::routing_key.
Referenced by TEST().
ExpectTestSolveParamEqual()
void ExpectTestSolveParamEqual (const TestSolveParam & lhs, const TestSolveParam & rhs)
References network_types::TestSolveParam::args, network_types::TestSolveParam::experiment_id, network_types::TestSolveParam::N_, and network_types::TestSolveParam::range.
Referenced by TEST_F().
TEST() [1/8]
TEST (NetworkTypesExchangeTests , JsonConstructorAndToJson)
References network_types::exchange::autoDelete, network_types::exchange::creator, network_types::exchange::durable, network_types::exchange::internal, network_types::exchange::name, network_types::stringToExchangeType, network_types::exchange::ToJson(), and network_types::exchange::type.
TEST() [2/8]
TEST (NetworkTypesExchangeTests , ParameterizedConstructor)
References network_types::exchange::autoDelete, network_types::exchange::creator, network_types::exchange::durable, network_types::exchange::internal, network_types::exchange::name, network_types::stringToExchangeType, network_types::exchange::ToJson(), and network_types::exchange::type.
TEST() [3/8]
TEST (NetworkTypesQueueBindingTests , ConstructFromJson)
References network_types::queueBinding::exchange, and network_types::queueBinding::routing_key.
TEST() [4/8]
TEST (NetworkTypesQueueBindingTests , ConstructFromStrings)
References network_types::queueBinding::exchange, and network_types::queueBinding::routing_key.
TEST() [5/8]
TEST (NetworkTypesQueueBindingTests , ConstructJsonEquivalence)
References ExpectQueueBindingEqual().
TEST() [6/8]
TEST (NetworkTypesQueueTests , JsonConstructorAndToJson)
References network_types::queue::autoDelete, network_types::queue::creator, network_types::queue::durable, network_types::queue::name, and network_types::queue::ToJson().
TEST() [7/8]
TEST (NetworkTypesQueueTests , ParameterizedConstructor)
References network_types::queue::autoDelete, network_types::queue::creator, network_types::queue::durable, network_types::queue::name, and network_types::queue::ToJson().
TEST() [8/8]
TEST (NetworkTypesRabbitMQUserTests , JsonConstructor)
References network_types::rabbitMQUser::name, network_types::rabbitMQUser::password_hash, and network_types::rabbitMQUser::tags.
TEST_F() [1/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_Boolean)
References network_types::JsonToVariant().
TEST_F() [2/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_Double)
References network_types::JsonToVariant().
TEST_F() [3/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_Int)
References network_types::JsonToVariant().
TEST_F() [4/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_Null)
References network_types::JsonToVariant().
TEST_F() [5/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_String)
References network_types::JsonToVariant().
TEST_F() [6/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_UInt)
References network_types::JsonToVariant().
TEST_F() [7/19]
TEST_F (NetworkTypesConversionTests , JsonToVariant_UnsuprotedType)
References EXPECT_EXCEPTION_WITH_ARGS, and network_types::JsonToVariant().
TEST_F() [8/19]
TEST_F (NetworkTypesConversionTests , VariantToJson_Bool)
References network_types::VariantToJson().
TEST_F() [9/19]
TEST_F (NetworkTypesConversionTests , VariantToJson_Double)
References network_types::VariantToJson().
TEST_F() [10/19]
TEST_F (NetworkTypesConversionTests , VariantToJson_Int64)
References network_types::VariantToJson().
TEST_F() [11/19]
TEST_F (NetworkTypesConversionTests , VariantToJson_Nullptr)
References network_types::VariantToJson().
TEST_F() [12/19]
TEST_F (NetworkTypesConversionTests , VariantToJson_String)
References network_types::VariantToJson().
TEST_F() [13/19]
TEST_F (NetworkTypesConversionTests , VariantToJson_UInt64)
References network_types::VariantToJson().
TEST_F() [14/19]
TEST_F (TestSolveParam_TS , DeserializeFromJson)
References network_types::TestSolveParam::args, network_types::TestSolveParam::experiment_id, network_types::TestSolveParam::N_, and network_types::TestSolveParam::range.
TEST_F() [15/19]
TEST_F (TestSolveParam_TS , SerializeDeserializeEquality)
References network_types::TestSolveParam::args, ExpectTestSolveParamEqual(), network_types::TestSolveParam::experiment_id, network_types::TestSolveParam::N_, network_types::TestSolveParam::range, and network_types::TestSolveParam::ToJson().
TEST_F() [16/19]
TEST_F (TestSolveParam_TS , SerializeToJson)
References network_types::TestSolveParam::args, network_types::TestSolveParam::experiment_id, network_types::TestSolveParam::N_, network_types::TestSolveParam::range, and network_types::TestSolveParam::ToJson().
TEST_F() [17/19]
TEST_F (TestSolveParam_TS , TestTooLargeSlice)
References EXPECT_EXCEPTION_WITH_ARGS.
TEST_F() [18/19]
TEST_F (TestSolveParam_TS , TestValidSlice)
TEST_F() [19/19]
TEST_F (TestSolveParam_TS , TestZeroSizeSlice)
References EXPECT_EXCEPTION_WITH_ARGS.