Distributed math architecture: computationalLib/test/math_core/smokeTests.cpp File Reference
smokeTests.cpp File Reference
#include <chrono>
#include "common/sharedDeclarations.h"
#include "math_core/Dipoles.h"
#include "common/commonTypes.h"
#include "common/Parsers.h"
#include "common/Printers.h"
#include "../GoogleCommon.h"
Classes
class DipolesVerificationTs
Typedefs
using Ttype = std::tuple< std::string, std::vector< FloatType >, ct::MatrixType, ct::EigenVec, MeshCreator >
Functions
std::vector< Ttype > TestFixtureGetter ()
INSTANTIATE_TEST_SUITE_P (ValidationTest, DipolesVerificationTs, ::testing::ValuesIn(TestFixtureGetter()), FirstValueTuplePrinter< DipolesVerificationTs >)
TEST_P (DipolesVerificationTs, test_on_10_basik_conf_matrixes)
TEST_P (DipolesVerificationTs, test_on_10_basik_conf_solutions)
TEST_P (DipolesVerificationTs, test_on_10_basik_conf_meshes)
TEST_F (DipolesVerificationTs, TestAllSolutionSpecializations)
TEST_F (DipolesVerificationTs, TestFunctionImplEqualRes)
TEST_F (DipolesVerificationTs, TestSetNewCoords)
Variables
std::string res_dir_path = "../../../res/"
std::string filename = res_dir_path.append("config.txt")
std::string subdir = filename.substr(0, filename.rfind('.')) + "data7_25"
Typedef Documentation
Ttype
using Ttype = std::tuple<std::string, std::vector<FloatType>, ct::MatrixType, ct::EigenVec, MeshCreator>
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (ValidationTest , DipolesVerificationTs , ::testing::ValuesIn(TestFixtureGetter()) , FirstValueTuplePrinter< DipolesVerificationTs >)
TEST_F() [1/3]
TEST_F (DipolesVerificationTs , TestAllSolutionSpecializations)
References test_common::CompareArrays(), dipoles::Dipoles::LoadFromMatrix(), dipoles::Dipoles::Solve(), and TestFixtureGetter().
TEST_F() [2/3]
TEST_F (DipolesVerificationTs , TestFunctionImplEqualRes)
References mesh_storage::MeshCreator::ApplyIntegrate(), mesh_storage::MeshCreator::ConstructMeshes(), mesh_storage::MeshCreator::data_, mesh_storage::MeshCreator::dimensions_, dipoles::Dipoles::GetFullFunction(), dipoles::Dipoles::GetIfunction(), TestFixtureGetter(), and mesh_storage::Unflatten().
TEST_F() [3/3]
TEST_F (DipolesVerificationTs , TestSetNewCoords)
References test_common::Compare2DArrays(), dipoles::Dipoles::GetMatrixx(), dipoles::Dipoles::SetNewCoordinates(), and TestFixtureGetter().
TEST_P() [1/3]
TEST_P (DipolesVerificationTs , test_on_10_basik_conf_matrixes)
References test_common::Compare2DArrays(), and dipoles::Dipoles::GetMatrixx().
TEST_P() [2/3]
TEST_P (DipolesVerificationTs , test_on_10_basik_conf_meshes)
References mesh_storage::MeshCreator::ApplyFunction(), mesh_storage::MeshCreator::ConstructMeshes(), mesh_storage::MeshCreator::data_, mesh_storage::MeshCreator::dimensions_, dipoles::Dipoles::GetFullFunction(), dipoles::Dipoles::GetI2Function(), and mesh_storage::Unflatten().
TEST_P() [3/3]
TEST_P (DipolesVerificationTs , test_on_10_basik_conf_solutions)
References test_common::CompareArrays(), dipoles::Dipoles::LoadFromMatrix(), and dipoles::Dipoles::Solve().
TestFixtureGetter()
std::vector< Ttype > TestFixtureGetter ()
References print_utils::ParseMeshFrom(), and subdir.
Referenced by TEST_F(), TEST_F(), and TEST_F().
Variable Documentation
filename
std::string filename = res_dir_path.append("config.txt")
Referenced by file_utils::fileHandler::Close(), file_utils::fileHandler::Contains(), file_utils::fileHandler::Open(), file_utils::fileHandler::output(), mesh_storage::MeshCreator::PlotAndSave(), and file_utils::fileHandler::Upsert().
res_dir_path
std::string res_dir_path = "../../../res/"
subdir
std::string subdir = filename.substr(0, filename.rfind('.')) + "data7_25"
Referenced by TestFixtureGetter().