Distributed math architecture: network_types::myConnString Struct Reference
network_types::myConnString Struct Reference
Structure to store and format connection string.
Public Member Functions
myConnString ()
myConnString (std::string_view user, std::string_view password, std::string_view host, std::string_view dbname, unsigned port)
operator std::string ()
operator std::string_view ()
const char * CStr () const
void SetUser (std::string_view new_user)
void SetPassword (std::string_view new_password)
void SetHost (std::string_view new_host)
void SetPort (unsigned new_port)
void SetDbname (std::string_view new_dbname)
const std::string & GetUser () const
const std::string & GetPassword () const
const std::string & GetHost () const
const std::string & GetDbname () const
unsigned int GetPort () const
std::string GetVerboseName () const
bool operator== (const myConnString &rhs) const
Private Member Functions
void UpdateFormat ()
Private Attributes
std::string user
std::string password
std::string host
std::string dbname
unsigned port
std::string formatted_string
Detailed Description
Structure to store and format connection string.
Todo:
create common interface for c string use it in queue us it for verbose names
Constructor & Destructor Documentation
myConnString() [1/2]
network_types::myConnString::myConnString () inline
myConnString() [2/2]
network_types::myConnString::myConnString (std::string_view user, std::string_view password, std::string_view host, std::string_view dbname, unsigned port)
Member Function Documentation
CStr()
const char * network_types::myConnString::CStr () const
Referenced by db_common::TryConnect().
GetDbname()
const std::string & network_types::myConnString::GetDbname () const
Referenced by db_common::CreateDatabase(), and db_common::DropDatabase().
GetHost()
const std::string & network_types::myConnString::GetHost () const
GetPassword()
const std::string & network_types::myConnString::GetPassword () const
GetPort()
unsigned int network_types::myConnString::GetPort () const
GetUser()
const std::string & network_types::myConnString::GetUser () const
Referenced by db_common::CreateDatabase().
GetVerboseName()
std::string network_types::myConnString::GetVerboseName () const
Referenced by db_common::ExecuteTransaction(), and db_common::TryConnect().
operator std::string()
network_types::myConnString::operator std::string () inline explicit
References formatted_string.
operator std::string_view()
network_types::myConnString::operator std::string_view ()
operator==()
bool network_types::myConnString::operator== (const myConnString & rhs) const
References dbname, formatted_string, host, password, port, and user.
SetDbname()
void network_types::myConnString::SetDbname (std::string_view new_dbname)
Referenced by db_common::CreateDatabase(), and db_common::DropDatabase().
SetHost()
void network_types::myConnString::SetHost (std::string_view new_host)
SetPassword()
void network_types::myConnString::SetPassword (std::string_view new_password)
SetPort()
void network_types::myConnString::SetPort (unsigned new_port)
SetUser()
void network_types::myConnString::SetUser (std::string_view new_user)
UpdateFormat()
void network_types::myConnString::UpdateFormat () private
Member Data Documentation
dbname
std::string network_types::myConnString::dbname private
Referenced by operator==().
formatted_string
std::string network_types::myConnString::formatted_string private
Referenced by operator std::string(), and operator==().
host
std::string network_types::myConnString::host private
Referenced by operator==().
password
std::string network_types::myConnString::password private
Referenced by operator==().
port
unsigned network_types::myConnString::port private
Referenced by operator==().
user
std::string network_types::myConnString::user private
Referenced by operator==().
The documentation for this struct was generated from the following files:
computationalLib/include/network_shared/connectionString.h
computationalLib/lib/network_shared/connectionString.cpp