name: Run benchmark

on:
  workflow_dispatch:
jobs:
  run-bench:
    runs-on: ubuntu-latest
    container:
      image: alexandermey/distirbutedmastservice:env1
      options:
        --cap-add=CAP_PERFMON
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          repo: AlexanderMeynik/distributedMathArh
          workflow: ci.yml
          path: /__w/distributedMathArh/distributedMathArh/build/
          search_artifacts: true
      - name: install testFixture
        run: |
          cd ${GITHUB_WORKSPACE}
          
          chmod -R +x build/
          wget -q https://github.com/AlexanderMeynik/distributedMathArh/releases/download/fixture/res.zip
          unzip -q res.zip
          rm res.zip
#      - name : draw flamegraphs
#        if: success() || failure()
#        run: |
#           cd ${GITHUB_WORKSPACE}/build/computationalNode
#           git clone https://github.com/brendangregg/FlameGraph
#           mkdir FlameGraph/res && cd FlameGraph/res
#           perf record --call-graph dwarf ./../../test/samplePerExample
#           perf script | ../stackcollapse-perf.pl |../flamegraph.pl > perf.svg
#      - name: Save flame graphs and perf files
#        if: success() || failure()
#        uses: actions/upload-artifact@v4
#        with:
#          name: flameGraphs
#          path: /__w/distributedMathArh/distributedMathArh/build/computationalNode/FlameGraph/res
#          if-no-files-found: warn
#          include-hidden-files: true
      - name: Run benchmark
        if: success() || failure()
        run: |
          cd ${GITHUB_WORKSPACE}/build/computationalNode/test
          ./benchmark
      - name: Save benchmake results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: bench
          path: /__w/distributedMathArh/distributedMathArh/build/computationalNode/test
          if-no-files-found: warn
          include-hidden-files: true
