name: Build and test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci.yml
      - computationalNode/**
      - utilLib/**
      - server/**
      - somestuff/**
      - CMakeLists.txt
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: alexandermey/distirbutedmastservice:env1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./src
      - name: Build
        run: |  
          cp -r src/res/ res/
        
          mkdir build && cd build
          
          cmake -G Ninja \
          ../src/
          ninja
      - name: Save build
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /__w/distributedMathArh/distributedMathArh/build
          if-no-files-found: warn
          include-hidden-files: true
      - name: Collect metrics
        run: |
          cd ${GITHUB_WORKSPACE}/src
          mkdir metrixpp && cd metrixpp
          
          /opt/venv/bin/metrix++ collect --db-file=source.db --exclude-files ".*test.*" \ 
          --std.code.filelines.total --std.code.complexity.cyclomatic --std.code.complexity.cyclomatic_switch_case_once \ 
          --std.code.filelines.comments --std.code.filelines.code --std.code.todo.comments --std.general.procerrors  \ 
          -- ../computationalNode/ ../server/ ../utilLib/
          
          /opt/venv/bin/metrix++ collect --db-file=wtests.db \ 
          --std.code.filelines.total --std.code.complexity.cyclomatic --std.code.complexity.cyclomatic_switch_case_once \ 
          --std.code.filelines.comments --std.code.filelines.code --std.code.todo.comments --std.general.procerrors  \ 
          -- ../computationalNode/ ../server/ ../utilLib/
          
          /opt/venv/bin/metrix++ view --db-file=source.db > source.txt  
          /opt/venv/bin/metrix++ view --db-file=wtests.db > wtests.txt
          /opt/venv/bin/metrix++ view --db-file=source.db --db-file-prev=wtests.db > sourceTestDiff.txt
      - name: Save metrics
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: metrixpp
          path: /__w/distributedMathArh/distributedMathArh/src/metrixpp
          if-no-files-found: warn
          include-hidden-files: true
      - name: Run core_tests
        run: |
          cd ${GITHUB_WORKSPACE}/build/computationalNode/test
          ./core_Tests
      - name: Run clock_tests
        if: success() || failure()
        run: |
          cd ${GITHUB_WORKSPACE}/build/utilLib/test
          ./par_Tests