name: Build and test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci.yml
      - computationalLib/**
      - utilLib/**
      - computationalNode/**
      - mainNode/**
      - CMakeLists.txt
      - scripts/collect_coverage.sh
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      host: http://rabbitmq:15672
      pghost: http://postgres:5432
      username: sysadmin
      password: syspassword
      coverageD: build-cov
    services:
      rabbitmq:
        image: rabbitmq:4-management
        env:
          RABBITMQ_DEFAULT_USER: ${{ env.username }}
          RABBITMQ_DEFAULT_PASS: ${{ env.password }}
        ports:
          - 5672:5672
          - 15672:15672
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ env.username }}
          POSTGRES_PASSWORD: ${{ env.password }}
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: alexandermey/distirbutedmastservice:env1
    steps:
      - name: LoadTools
        run: |
          apt-get update
          apt-get install -y lcov
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./src
      - name: Build
        run: |
          cp -r src/res/ res/
          
          mkdir build && cd build
          
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release  \
          -DBUILD_TESTS=ON ../src/
          ninja
      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /__w/distributedMathArh/distributedMathArh/build
          if-no-files-found: warn
          include-hidden-files: true
      - name: Run tests
        run: |
          
          mkdir $coverageD && cd $coverageD
          
  
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release-Coverage  \
          -DBUILD_TESTS=ON ../src/
          ctest -T Build -T Test --output-on-failure

      - name: Collect coverage
        if: success() || failure()
        working-directory: ./src
        run: bash scripts/collect_coverage.sh

      - name: Save coverage report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: /__w/distributedMathArh/distributedMathArh/cov_report
          if-no-files-found: warn
          include-hidden-files: true
