name: Build and test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci.yml
      - computationalNode/**
      - utilLib/**
      - server/**
      - somestuff/**
      - CMakeLists.txt
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: alexandermey/distirbutedmastservice:env1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./src
      - name: Build
        run: |  
          cp -r src/res/ res/
        
          mkdir build && cd build
          
          cmake -G Ninja \
          ../src/
          ninja
      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /__w/distributedMathArh/distributedMathArh/build
          if-no-files-found: warn
          include-hidden-files: true
      - name: Run core_tests
        run: |
          cd ${GITHUB_WORKSPACE}/build/computationalNode/test
          ./core_Tests
      - name: Run clock_tests
        if: success() || failure()
        run: |
          cd ${GITHUB_WORKSPACE}/build/utilLib/test
          ./par_Tests