name: Build and push docker image
on:
  workflow_dispatch:
  push:
    paths:
      - confFiles/**
      - .github/workflows/docker_build.yml
jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_include: ${{ steps.dockerxparams.outputs.matrix_include }}
    steps:
      - name: Define matrix params
        id: dockerxparams
        run: |
          PAIRS=(
          "./confFiles/multiStage.Dockerfile:alexandermey/distirbutedmastservice:env1"
          "./confFiles/collectMetrics.Dockerfile:alexandermey/distirbutedmastservice:metrics"
          )
          
          HANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          
          FILTERED_PAIRS=()
            for pair in "${PAIRS[@]}"; do
            DF="${pair%%:*}"
            TAG="${pair#*:}"
          
            if echo "$CHANGED_FILES" | grep -q "^$DF$"; then
              FILTERED_PAIRS+=("{\"dockerfile\": \"$DF\", \"tags\": \"$TAG\"}")
            fi
          done
          echo "matrix_include=[$(IFS=,; echo "${FILTERED_PAIRS[*]}")]" >> "$GITHUB_OUTPUT"
          echo "matrix_include=[$(IFS=,; echo "${FILTERED_PAIRS[*]}")]"

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.define-matrix.outputs.matrix_include) }}
    steps:
      - name: Build and push
        uses: ./.github/workflows/common/docker_build_push.yml
        with:
          dockerfile: ${{ matrix.dockerfile }}
          tags: ${{ matrix.tags }}