name: Deploy documentation

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download metrics output
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: metrics
          repo: AlexanderMeynik/distributedMathArh
          workflow: collect_metrics.yml
          path: ./metrics/
          search_artifacts: true
      - name: Install deps
        run: |
          sudo apt-get update
          pip3 install coverxygen
          sudo apt-get install doxygen graphviz -y
          doxygen --version
      - name: Build documentation
        run: bash scripts/build_doc.sh
      - name: Save doc
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: /home/runner/work/distributedMathArh/distributedMathArh/build/doc
          if-no-files-found: warn
          include-hidden-files: true
      - name: Update coverage badge
        if: ${{ github.ref == 'refs/heads/master'&&(success() || failure())}}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.BADGES_GIST_ID }}
          filename: doc_coverage.json
          label: Doc coverage
          message: ${{ env.DOC_COVERAGE_LABEL }}
          valColorRange: ${{ env.DOC_COVERAGE_VALUE }}
          minColorRange: 40
          maxColorRange: 80
      - name: Deploy
        if: success() || failure()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/doc/doxygen-html
