name: Deploy documentation

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read-write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download metrics output
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: metrics
          repo: AlexanderMeynik/distributedMathArh
          workflow: collect_metrics.yml
          path: /__w/distributedMathArh/distributedMathArh/metrics/
          search_artifacts: true
      - name: Build documentation
        run: |
          sudo apt-get install doxygen graphviz -y
          mkdir -p build/doc 
          cp -r doc/. build/doc 
          cd build/doc
          doxygen Doxyfile.in
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/doc/doxygen-html
