name: Build and test
run-name: ${{ github.actor }} is testing out Download Artifact 🚀
on:
  workflow_dispatch:
jobs:
  load_and_test:
    runs-on: ubuntu-latest
    container:
      image: alexandermey/distirbutedmastservice:env1
    steps:
    - name: "Download artifact"
      run: |
        mkdir build && cd build
        OTHER_REPO="AlexanderMeynik/distributedMathArh"
        WF_NAME="ci.yml"
        ARTIFACT_NAME="build"
        RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
        gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        ls -lR
      env:
        GITHUB_TOKEN: ${{ secrets.ARTIFACT_DEPLOY_TOKEN }}
    - name: Run core_tests
      run: |
          cd ${GITHUB_WORKSPACE}/build/computationalNode/test
          ./core_Tests
    - name: Run clock_tests
      if: success() || failure()
      run: |
        cd ${GITHUB_WORKSPACE}/build/utilLib/test
        ./par_Tests
