name: Build and test
run-name: ${{ github.actor }} is testing out Download Artifact 🚀
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/loadArtifactTest.yml
jobs:
  load_and_test:
    runs-on: ubuntu-latest
    container:
      image: alexandermey/distirbutedmastservice:env1
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: build
        repo: AlexanderMeynik/distributedMathArh
        workflow: ci.yml
        path: /__w/distributedMathArh/distributedMathArh/build/
        search_artifacts: true
    - name: Run core_tests
      run: |
          cd ${GITHUB_WORKSPACE}/build/computationalNode/test
          ./core_Tests
    - name: Run clock_tests
      if: success() || failure()
      run: |
        cd ${GITHUB_WORKSPACE}/build/utilLib/test
        ./par_Tests
