name: Run Tests with RabbitMQ

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      host: http://localhost:15672
      username: sysadmin
      password: syspassword
    services:
      rabbitmq:
        image: rabbitmq:4.0
        env:
          RABBITMQ_DEFAULT_USER: ${username}
          RABBITMQ_DEFAULT_PASS: ${password}
        ports:
          - 5672
          - 15672
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./src

      - name: Download build
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: build
          repo: AlexanderMeynik/distributedMathArh
          workflow: ci.yml
          path: build
          search_artifacts: true

      - name: Run tests
        run: |
          cd build/mainNode/test
          ./serviceTest ${host} ${username} ${password}